module.exports = {
    range: ['f', 'g', 'h', 'i', 'j'],
    words: [
        { "slang": "f u", "original": "fuck you" },
        { "slang": "f#cking", "original": "Fucking" },
        { "slang": "f&e", "original": "forever and ever" },
        { "slang": "f'n", "original": "fucking" },
        { "slang": "f-ing", "original": "fucking" },
        { "slang": "f.b.", "original": "facebook" },
        { "slang": "f.m.l.", "original": "fuck my life" },
        { "slang": "f.u.", "original": "fuck you" },
        { "slang": "f/o", "original": "fuck off" },
        { "slang": "f00k", "original": "Fuck." },
        { "slang": "f2f", "original": "face to face" },
        { "slang": "f2m", "original": "female to male" },
        { "slang": "f2p", "original": "free to play" },
        { "slang": "f2t", "original": "Free to talk" },
        { "slang": "f4c3", "original": "face" },
        { "slang": "f4eaa", "original": "friends forever and always" },
        { "slang": "f4f", "original": "female for female" },
        { "slang": "f4m", "original": "female for male" },
        { "slang": "f8", "original": "fate" },
        { "slang": "f9", "original": "fine" },
        { "slang": "f@", "original": "fat" },
        { "slang": "fa-q", "original": "Fuck you" },
        { "slang": "faa", "original": "forever and always" },
        { "slang": "fab", "original": "fabulous" },
        { "slang": "faggit", "original": "faggot" },
        { "slang": "fah", "original": "Funny as hell" },
        { "slang": "faic", "original": "For All I Care" },
        { "slang": "fam", "original": "family" },
        { "slang": "fankle", "original": "area between foot and ankle" },
        { "slang": "fao", "original": "for attention of" },
        { "slang": "fap", "original": "masturbate" },
        { "slang": "fapping", "original": "masterbating" },
        { "slang": "faq", "original": "frequently asked question" },
        { "slang": "farg", "original": "fuck" },
        { "slang": "fashizzle", "original": "for sure" },
        { "slang": "fav", "original": "Favorite" },
        { "slang": "fave", "original": "favorite" },
        { "slang": "fawk", "original": "fuck" },
        { "slang": "fbimcl", "original": "Fall Back In My Chair Laughing" },
        { "slang": "fbk", "original": "facebook" },
        { "slang": "fbtw", "original": "Fine Be That Way" },
        { "slang": "fc", "original": "fruit cake" },
        { "slang": "fcbk", "original": "facebook" },
        { "slang": "fcfs", "original": "first come first served" },
        { "slang": "fck", "original": "fuck" },
        { "slang": "fckd", "original": "fucked" },
        { "slang": "fckin", "original": "fucking" },
        { "slang": "fcking", "original": "fucking" },
        { "slang": "fckm3hdbayb", "original": "Fuck Me Hard Baby" },
        { "slang": "fcku", "original": "fuck you" },
        { "slang": "fcol", "original": "for crying out loud" },
        { "slang": "fcuk", "original": "fuck" },
        { "slang": "fe", "original": "fatal error" },
        { "slang": "feat", "original": "Featuring" },
        { "slang": "feck", "original": "fuck" },
        { "slang": "fer", "original": "for" },
        { "slang": "ferr", "original": "For" },
        { "slang": "ff", "original": "friendly fire" },
        { "slang": "ffa", "original": "free for all" },
        { "slang": "ffcl", "original": "falling from chair laughing" },
        { "slang": "ffr", "original": "for future reference" },
        { "slang": "ffs", "original": "for fuck's sake" },
        { "slang": "fft", "original": "food for thought" },
        { "slang": "ffxi", "original": "Final Fantasy 11" },
        { "slang": "fg", "original": "fucking gay" },
        { "slang": "fgi", "original": "fucking google it" },
        { "slang": "fgs", "original": "for God's sake" },
        { "slang": "fgssu", "original": "For Gods sake shut up" },
        { "slang": "fgt", "original": "faggot" },
        { "slang": "fi", "original": "fuck it" },
        { "slang": "fi9", "original": "fine" },
        { "slang": "fibijar", "original": "fuck it buddy, I'm just a reserve" },
        { "slang": "fifo", "original": "first in, first out" },
        { "slang": "fify", "original": "Fixed It For You" },
        { "slang": "figjam", "original": "fuck I'm good, just ask me" },
        { "slang": "figmo", "original": "F*ck it - got my orders" },
        { "slang": "fiic", "original": "Fucked If I Care" },
        { "slang": "fiik", "original": "Fucked If I Know" },
        { "slang": "fimh", "original": "forever in my heart" },
        { "slang": "fio", "original": "figure it out" },
        { "slang": "fitb", "original": "fill in the blank" },
        { "slang": "fiv", "original": "five" },
        { "slang": "fk", "original": "fuck" },
        { "slang": "fka", "original": "formerly known as" },
        { "slang": "fkd", "original": "fucked" },
        { "slang": "fker", "original": "fucker" },
        { "slang": "fkin", "original": "fucking" },
        { "slang": "fking", "original": "Fucking" },
        { "slang": "fkn", "original": "Fucking" },
        { "slang": "fku", "original": "fuck you" },
        { "slang": "flamer", "original": "angry poster" },
        { "slang": "flames", "original": "angry comments" },
        { "slang": "flicks", "original": "pictures" },
        { "slang": "floabt", "original": "for lack of a better term" },
        { "slang": "fm", "original": "fuck me" },
        { "slang": "fmah", "original": "fuck my ass hole" },
        { "slang": "fmao", "original": "freezing my ass of" },
        { "slang": "fmb", "original": "fuck me bitch" },
        { "slang": "fmbb", "original": "Fuck Me Baby" },
        { "slang": "fmbo", "original": "fuck my brains out" },
        { "slang": "fmfl", "original": "Fuck my Fucking life" },
        { "slang": "fmflth", "original": "Fuck My Fucking Life To Hell" },
        { "slang": "fmh", "original": "Fuck me hard" },
        { "slang": "fmhb", "original": "fuck me hard bitch" },
        { "slang": "fmi", "original": "for my information" },
        { "slang": "fmir", "original": "family member in room" },
        { "slang": "fmita", "original": "fuck me in the ass" },
        { "slang": "fml", "original": "fuck my life" },
        { "slang": "fmltwia", "original": "fuck me like the whore I am" },
        { "slang": "fmn", "original": "Fuck me now" },
        { "slang": "fmnb", "original": "fuck me now bitch" },
        { "slang": "fmnkml", "original": "fuck me now kiss me later" },
        { "slang": "fmph", "original": "fuck my pussy hard" },
        { "slang": "fmq", "original": "fuck me quick" },
        { "slang": "fmr", "original": "fuck me runnig" },
        { "slang": "fmsh", "original": "Fuck me so hard" },
        { "slang": "fmth", "original": "fuck me to hell" },
        { "slang": "fmuta", "original": "fuck me up the ass" },
        { "slang": "fmutp", "original": "fuck me up the pussy" },
        { "slang": "fn", "original": "first name" },
        { "slang": "fnar", "original": "For No Apparent Reason" },
        { "slang": "fnci", "original": "fancy" },
        { "slang": "fnny", "original": "funny" },
        { "slang": "fnpr", "original": "for no particular reason" },
        { "slang": "fny", "original": "funny" },
        { "slang": "fo", "original": "fuck off" },
        { "slang": "fo shizzle", "original": "for sure" },
        { "slang": "fo sho", "original": "for sure" },
        { "slang": "foa", "original": "fuck off asshole" },
        { "slang": "foad", "original": "fuck off and die" },
        { "slang": "foaf", "original": "friend of a friend" },
        { "slang": "foah", "original": "fuck off asshole" },
        { "slang": "fob", "original": "fresh off the boat" },
        { "slang": "focl", "original": "Falling Off Chair Laughing." },
        { "slang": "fofl", "original": "fall on the floor laughing" },
        { "slang": "foia", "original": "freedom of information act" },
        { "slang": "fol", "original": "farting out loud" },
        { "slang": "folo", "original": "Follow" },
        { "slang": "fomofo", "original": "fuck off mother fucker" },
        { "slang": "fone", "original": "phone" },
        { "slang": "foo", "original": "fool" },
        { "slang": "foobar", "original": "fucked up beyond all recognition" },
        { "slang": "foocl", "original": "falls out of chair laughing" },
        { "slang": "fook", "original": "fuck" },
        { "slang": "for sheeze", "original": "for sure" },
        { "slang": "fos", "original": "full of shit" },
        { "slang": "foshizzle", "original": "for sure" },
        { "slang": "fosho", "original": "for sure" },
        { "slang": "foss", "original": "free, open source software" },
        { "slang": "fotcl", "original": "fell off the chair laughing" },
        { "slang": "fotm", "original": "Flavour of the month" },
        { "slang": "fouc", "original": "Fuck off you cunt " },
        { "slang": "fov", "original": "Field of View" },
        { "slang": "foyb", "original": "fuck off you bitch" },
        { "slang": "fo`", "original": "for" },
        { "slang": "fp", "original": "first post" },
        { "slang": "fpmitap", "original": "federal pound me in the ass prison" },
        { "slang": "fpos", "original": "fucking piece of shit" },
        { "slang": "fps", "original": "First Person Shooter" },
        { "slang": "frag", "original": "kill" },
        { "slang": "fragged", "original": "killed" },
        { "slang": "fren", "original": "friend" },
        { "slang": "frens", "original": "friends" },
        { "slang": "frgt", "original": "forgot" },
        { "slang": "fri.", "original": "Friday" },
        { "slang": "friggin", "original": "freaking" },
        { "slang": "frk", "original": "freak" },
        { "slang": "frm", "original": "from" },
        { "slang": "frnd", "original": "friend" },
        { "slang": "frnds", "original": "friends" },
        { "slang": "fs", "original": "For Sure" },
        { "slang": "fse", "original": "Funniest Shit Ever" },
        { "slang": "fsho", "original": "for sure" },
        { "slang": "fsm", "original": "flying spaghetti monster" },
        { "slang": "fsob", "original": "Fucking son of a bitch" },
        { "slang": "fsod", "original": "frosn screen of death" },
        { "slang": "fsr", "original": "for some reason" },
        { "slang": "fst", "original": "fast" },
        { "slang": "ft", "original": "FUCK THAT" },
        { "slang": "ft2t", "original": "From time to time" },
        { "slang": "fta", "original": "From The Article" },
        { "slang": "ftb", "original": "Fuck That Bitch" },
        { "slang": "ftbfs", "original": "Failed to build from source" },
        { "slang": "ftf", "original": "face to face" },
        { "slang": "ftfa", "original": "From The Fucking Article" },
        { "slang": "ftfw", "original": "For the fucking win!" },
        { "slang": "ftfy", "original": "Fixed that for you" },
        { "slang": "ftio", "original": "fun time is over" },
        { "slang": "ftk", "original": "For the Kill" },
        { "slang": "ftl", "original": "For The Lose" },
        { "slang": "ftlog", "original": "for the love of god" },
        { "slang": "ftlt", "original": "For the last time" },
        { "slang": "ftmfw", "original": "for the mother fucking win" },
        { "slang": "ftmp", "original": "For the most part" },
        { "slang": "ftp", "original": "file transfer protocol" },
        { "slang": "ftr", "original": "For The Record" },
        { "slang": "fts", "original": "fuck that shit" },
        { "slang": "fttp", "original": "for the time being" },
        { "slang": "ftw", "original": "For the win!" },
        { "slang": "fu", "original": "fuck you" },
        { "slang": "fua", "original": "fuck you all" },
        { "slang": "fuah", "original": "fuck you ass hole" },
        { "slang": "fub", "original": "fuck you bitch" },
        { "slang": "fubah", "original": "fucked up beyond all hope" },
        { "slang": "fubalm", "original": "fucked up beyond all local maintenance" },
        { "slang": "fubar", "original": "fucked up beyond all recognition" },
        { "slang": "fubb", "original": "fucked up beyond belief" },
        { "slang": "fubh", "original": "fucked up beyond hope" },
        { "slang": "fubohic", "original": "fuck you Bend over here it comes" },
        { "slang": "fubr", "original": "Fucked Up Beyond Recognition" },
        { "slang": "fucken", "original": "Fucking" },
        { "slang": "fucktard", "original": "fucking retard" },
        { "slang": "fuctard", "original": "fucking retard" },
        { "slang": "fud", "original": "fear, uncertainty and doubt" },
        { "slang": "fudh", "original": "fuck you dick head" },
        { "slang": "fudie", "original": "fuck you and die" },
        { "slang": "fugly", "original": "fucking ugly" },
        { "slang": "fuh-q", "original": "fuck you" },
        { "slang": "fuhget", "original": "forget" },
        { "slang": "fuk", "original": "fuck" },
        { "slang": "fukin", "original": "fucking" },
        { "slang": "fukk", "original": "fuck" },
        { "slang": "fukkin", "original": "fucking" },
        { "slang": "fukn", "original": "fucking" },
        { "slang": "fukr", "original": "fucker" },
        { "slang": "fulla", "original": "Full of" },
        { "slang": "fumfer", "original": "fuck you mother fucker" },
        { "slang": "funee", "original": "funny" },
        { "slang": "funner", "original": "more fun" },
        { "slang": "funy", "original": "funny" },
        { "slang": "fuq", "original": "fuck you" },
        { "slang": "fus", "original": "fuck yourself" },
        { "slang": "fut", "original": "Fuck You Too" },
        { "slang": "fuu", "original": "fuck you up" },
        { "slang": "fux", "original": "fuck" },
        { "slang": "fuxing", "original": "fucking" },
        { "slang": "fuxor", "original": "fucker" },
        { "slang": "fuxored", "original": "Fucked" },
        { "slang": "fvck", "original": "fuck" },
        { "slang": "fwb", "original": "Friends with Benefits" },
        { "slang": "fwd", "original": "forward" },
        { "slang": "fwiw", "original": "for what it's worth" },
        { "slang": "fwm", "original": "Fine With Me" },
        { "slang": "fwob", "original": "friends with occasional benefits" },
        { "slang": "fwp", "original": "first world problems" },
        { "slang": "fxe", "original": "foxy" },
        { "slang": "fxp", "original": "file exchange protocol" },
        { "slang": "fy", "original": "fuck you" },
        { "slang": "fya", "original": "for your attention" },
        { "slang": "fyad", "original": "fuck you and die" },
        { "slang": "fyah", "original": "fuck you asshole" },
        { "slang": "fyb", "original": "fuck you bitch" },
        { "slang": "fyc", "original": "fuck your couch" },
        { "slang": "fye", "original": "For Your Entertainment" },
        { "slang": "fyeo", "original": "For your eyes only" },
        { "slang": "fyf", "original": "fuck your face" },
        { "slang": "fyfi", "original": "For Your Fucking Information" },
        { "slang": "fyi", "original": "for your information" },
        { "slang": "fyk", "original": "for your knowledge" },
        { "slang": "fyl", "original": "For your Love" },
        { "slang": "fym", "original": "fuck your mom" },
        { "slang": "fyp", "original": "fixed your post" },
        { "slang": "fyrb", "original": "fuck you right back" },
        { "slang": "fytd", "original": "fuck you to death" },
        { "slang": "*g*", "original": "grin" },
        { "slang": "g'nite", "original": "good night" },
        { "slang": "g/f", "original": "girlfriend" },
        { "slang": "g/g", "original": "got to go" },
        { "slang": "g0", "original": "go" },
        { "slang": "g00g13", "original": "Google" },
        { "slang": "g1", "original": "good one" },
        { "slang": "g2", "original": "go to" },
        { "slang": "g2/-/", "original": "go to hell" },
        { "slang": "g2bg", "original": "got to be going" },
        { "slang": "g2bl8", "original": "going to be late" },
        { "slang": "g2cu", "original": "glad to see you" },
        { "slang": "g2e", "original": "got to eat" },
        { "slang": "g2g", "original": "got to go" },
        { "slang": "g2g2tb", "original": "got to go to the bathroom" },
        { "slang": "g2g2w", "original": "got to go to work" },
        { "slang": "g2g4aw", "original": "got to go for a while" },
        { "slang": "g2gb", "original": "got to go bye" },
        { "slang": "g2gb2wn", "original": "got to go back to work now" },
        { "slang": "g2ge", "original": "got to go eat" },
        { "slang": "g2gn", "original": "got to go now" },
        { "slang": "g2gp", "original": "got to go pee" },
        { "slang": "g2gpc", "original": "got 2 go parents coming" },
        { "slang": "g2gpp", "original": "got to go pee pee" },
        { "slang": "g2gs", "original": "got to go sorry" },
        { "slang": "g2h", "original": "go to hell" },
        { "slang": "g2hb", "original": "go to hell bitch" },
        { "slang": "g2k", "original": "good to know" },
        { "slang": "g2p", "original": "got to pee" },
        { "slang": "g2t2s", "original": "got to talk to someone" },
        { "slang": "g3y", "original": "gay" },
        { "slang": "g4u", "original": "good for you" },
        { "slang": "g4y", "original": "good for you" },
        { "slang": "g8", "original": "gate" },
        { "slang": "g9", "original": "good night" },
        { "slang": "g@y", "original": "gay" },
        { "slang": "ga", "original": "go ahead" },
        { "slang": "gaalma", "original": "go away and leave me alone" },
        { "slang": "gaf", "original": "good as fuck" },
        { "slang": "gafi", "original": "get away from it" },
        { "slang": "gafl", "original": "get a fucking life" },
        { "slang": "gafm", "original": "Get away from me" },
        { "slang": "gagf", "original": "go and get fucked" },
        { "slang": "gagp", "original": "go and get pissed" },
        { "slang": "gah", "original": "gay ass homo" },
        { "slang": "gai", "original": "gay" },
        { "slang": "gaj", "original": "get a job" },
        { "slang": "gal", "original": "get a life" },
        { "slang": "gamez", "original": "illegally obtained games" },
        { "slang": "gangsta", "original": "gangster" },
        { "slang": "gank", "original": "kill" },
        { "slang": "gaoep", "original": "generally accepted office etiquette principles" },
        { "slang": "gaw", "original": "grandparents are watching" },
        { "slang": "gawd", "original": "god" },
        { "slang": "gb", "original": "Go back" },
        { "slang": "gb2", "original": "go back to" },
        { "slang": "gba", "original": "game boy advance" },
        { "slang": "gbioua", "original": "Go blow it out your ass" },
        { "slang": "gbnf", "original": "Gone but not forgotten " },
        { "slang": "gbtw", "original": "go back to work" },
        { "slang": "gbu", "original": "god bless you" },
        { "slang": "gby", "original": "good bye" },
        { "slang": "gcad", "original": "get cancer and die" },
        { "slang": "gcf", "original": "Google Click Fraud" },
        { "slang": "gd", "original": "good" },
        { "slang": "gd&r", "original": "grins, ducks, and runs" },
        { "slang": "gd4u", "original": "Good For You" },
        { "slang": "gday", "original": "Good Day" },
        { "slang": "gdby", "original": "good bye" },
        { "slang": "gded", "original": "grounded" },
        { "slang": "gdgd", "original": "good good" },
        { "slang": "gdi", "original": "God Damn it" },
        { "slang": "gdiaf", "original": "go die in a fire" },
        { "slang": "gdih", "original": "Go die in hell" },
        { "slang": "gdilf", "original": "Grandad I'd Like To Fuck" },
        { "slang": "gdmfpos", "original": "god damn mother fucking piece of shit" },
        { "slang": "gdr", "original": "grinning, ducking, running" },
        { "slang": "gemo", "original": "gay emo" },
        { "slang": "getcha", "original": "get you" },
        { "slang": "geto", "original": "ghetto" },
        { "slang": "gewd", "original": "good" },
        { "slang": "gey", "original": "gay" },
        { "slang": "gf", "original": "girlfriend" },
        { "slang": "gfad", "original": "go fuck a duck" },
        { "slang": "gfadh", "original": "go fuck a dead horse" },
        { "slang": "gfak", "original": "go fly a kite" },
        { "slang": "gfam", "original": "Go Fuck A Monkey" },
        { "slang": "gfar2cu", "original": "go find a rock to crawl under" },
        { "slang": "gfas", "original": "go fuck a sheep" },
        { "slang": "gfd", "original": "god fucking damnit" },
        { "slang": "gfe", "original": "Girl Friend experience" },
        { "slang": "gfe2e", "original": "grinning from ear to ear" },
        { "slang": "gfg", "original": "good fucking game" },
        { "slang": "gfgi", "original": "go fucking google it" },
        { "slang": "gfi", "original": "good fucking idea" },
        { "slang": "gfj", "original": "good fucking job" },
        { "slang": "gfl", "original": "grounded for life" },
        { "slang": "gfo", "original": "go fuck off" },
        { "slang": "gfu", "original": "go fuck yourself" },
        { "slang": "gfurs", "original": "go fuck yourself" },
        { "slang": "gfus", "original": "go fuck yourself" },
        { "slang": "gfx", "original": "graphics" },
        { "slang": "gfy", "original": "good for you" },
        { "slang": "gfyd", "original": "go fuck your dad" },
        { "slang": "gfym", "original": "go fuck your mom" },
        { "slang": "gfys", "original": "go fuck yourself" },
        { "slang": "gg", "original": "good game" },
        { "slang": "gga", "original": "good game all" },
        { "slang": "ggal", "original": "go get a life" },
        { "slang": "ggf", "original": "go get fucked" },
        { "slang": "ggg", "original": "Go, go, go! " },
        { "slang": "ggi", "original": "go google it" },
        { "slang": "ggnore", "original": "good game no rematch" },
        { "slang": "ggp", "original": "gotta go pee" },
        { "slang": "ggpaw", "original": "gotta go parents are watching" },
        { "slang": "ggs", "original": "good games" },
        { "slang": "gh", "original": "good half" },
        { "slang": "ghei", "original": "Gay" },
        { "slang": "ghey", "original": "gay" },
        { "slang": "gigig", "original": "get it got it good" },
        { "slang": "gigo", "original": "garbage in garbage out" },
        { "slang": "gilf", "original": "Grandma I'd like to fuck" },
        { "slang": "gim", "original": "google instant messanger" },
        { "slang": "gimme", "original": "give me" },
        { "slang": "gimmie", "original": "give me" },
        { "slang": "gir", "original": "google it retard" },
        { "slang": "gis", "original": "Google Image Search" },
        { "slang": "gitar", "original": "guitar" },
        { "slang": "giv", "original": "give" },
        { "slang": "giyf", "original": "google is your friend" },
        { "slang": "gj", "original": "good job" },
        { "slang": "gjial", "original": "go jump in a lake" },
        { "slang": "gjp", "original": "good job partner" },
        { "slang": "gjsu", "original": "god just shut up" },
        { "slang": "gjt", "original": "good job team" },
        { "slang": "gky", "original": "Go kill yourself" },
        { "slang": "gkys", "original": "Go kill yourself" },
        { "slang": "gl", "original": "good luck" },
        { "slang": "gl hf", "original": "good luck, have fun" },
        { "slang": "gl&hf", "original": "good luck and have fun" },
        { "slang": "gla", "original": "good luck all" },
        { "slang": "glbt", "original": "Gay, lesbian, bisexual, transgenderd" },
        { "slang": "glf", "original": "group looking for" },
        { "slang": "glhf", "original": "good luck have fun" },
        { "slang": "glln", "original": "Got Laid Last Night" },
        { "slang": "glnhf", "original": "Good Luck and Have Fun" },
        { "slang": "glty", "original": "Good luck this year" },
        { "slang": "glu", "original": "girl like us" },
        { "slang": "glu2", "original": "good luck to you too" },
        { "slang": "glux", "original": "good luck" },
        { "slang": "glwt", "original": "good luck with that" },
        { "slang": "gm", "original": "good morning" },
        { "slang": "gma", "original": "grandma" },
        { "slang": "gmab", "original": "give me a break" },
        { "slang": "gmabj", "original": "give me a blowjob" },
        { "slang": "gmafb", "original": "give me a fucking break" },
        { "slang": "gmao", "original": "Giggling my ass off" },
        { "slang": "gmfao", "original": "Giggling My Fucking Ass Off" },
        { "slang": "gmilf", "original": "grandmother i'd like to fuck" },
        { "slang": "gmod", "original": "Global Moderator" },
        { "slang": "gmta", "original": "great minds think alike" },
        { "slang": "gmtyt", "original": "good morning to you too" },
        { "slang": "gmv", "original": "Got my vote" },
        { "slang": "gmybs", "original": "give me your best shot" },
        { "slang": "gn", "original": "good night" },
        { "slang": "gn8", "original": "good night" },
        { "slang": "gnasd", "original": "good night and sweet dreams" },
        { "slang": "gndn", "original": "Goes nowhere,does nothing" },
        { "slang": "gnfpwlbn", "original": "good news for people who love bad news" },
        { "slang": "gng", "original": "going" },
        { "slang": "gng2", "original": "going to" },
        { "slang": "gngbng", "original": "gang bang" },
        { "slang": "gnight", "original": "good night" },
        { "slang": "gnite", "original": "good night" },
        { "slang": "gnn", "original": "get naked now" },
        { "slang": "gno", "original": "going to do" },
        { "slang": "gnoc", "original": "get naked on cam" },
        { "slang": "gnos", "original": "get naked on screen" },
        { "slang": "gnr", "original": "Guns n' roses" },
        { "slang": "gnrn", "original": "get naked right now" },
        { "slang": "gnst", "original": "goodnight sleep tight" },
        { "slang": "gnstdltbbb", "original": "good night sleep tight don't let the bed bugs bite" },
        { "slang": "goc", "original": "get on camera" },
        { "slang": "goi", "original": "get over it " },
        { "slang": "goia", "original": "get over it already" },
        { "slang": "goin", "original": "going" },
        { "slang": "gok", "original": "God Only Knows" },
        { "slang": "gokid", "original": "got observers - keep it decent" },
        { "slang": "gokw", "original": "God Only Knows Why" },
        { "slang": "gol", "original": "giggle out loud" },
        { "slang": "gomb", "original": "get off my back" },
        { "slang": "goml", "original": "get out of my life" },
        { "slang": "gona", "original": "Gonna" },
        { "slang": "gonna", "original": "going to" },
        { "slang": "good9", "original": "goodnite" },
        { "slang": "gooh", "original": "get out of here!" },
        { "slang": "goomh", "original": "get out of my head" },
        { "slang": "gork", "original": "God only really knows" },
        { "slang": "gosad", "original": "go suck a dick" },
        { "slang": "gotc", "original": "get on the computer" },
        { "slang": "gotcha", "original": "got you" },
        { "slang": "gotta", "original": "got to" },
        { "slang": "gow", "original": "gears of war" },
        { "slang": "goya", "original": "Get Off Your Ass" },
        { "slang": "goyhh", "original": "get off your high horse" },
        { "slang": "gp", "original": "good point" },
        { "slang": "gpb", "original": "gotta pee bad" },
        { "slang": "gpwm", "original": "good point well made" },
        { "slang": "gpytfaht", "original": "gladly pay you tuesday for a hamburger today" },
        { "slang": "gr8", "original": "great" },
        { "slang": "gr8t", "original": "great" },
        { "slang": "grats", "original": "congratulations" },
        { "slang": "gratz", "original": "congratulations" },
        { "slang": "grfx", "original": "graphics" },
        { "slang": "grillz", "original": "metal teeth" },
        { "slang": "grl", "original": "girl" },
        { "slang": "grmbl", "original": "grumble" },
        { "slang": "grog", "original": "beer" },
        { "slang": "grrl", "original": "Girl" },
        { "slang": "grtg", "original": "Getting ready to go" },
        { "slang": "grvy", "original": "groovy" },
        { "slang": "gsad", "original": "go suck a dick" },
        { "slang": "gsave", "original": "global struggle against violent extremists" },
        { "slang": "gsd", "original": "getting shit done" },
        { "slang": "gsfg", "original": "Go search fucking google" },
        { "slang": "gsi", "original": "go suck it" },
        { "slang": "gsoh", "original": "Good Sense of Humor" },
        { "slang": "gsp", "original": "get some pussy" },
        { "slang": "gsta", "original": "Gangster" },
        { "slang": "gt", "original": "get" },
        { "slang": "gta", "original": "Grand Theft Auto" },
        { "slang": "gtas", "original": "go take a shit" },
        { "slang": "gtb", "original": "Go To Bed" },
        { "slang": "gtf", "original": "get the fuck" },
        { "slang": "gtfa", "original": "Go The Fuck Away" },
        { "slang": "gtfbtw", "original": "get the fuck back to work" },
        { "slang": "gtfh", "original": "go to fucking hell" },
        { "slang": "gtfo", "original": "get the fuck out" },
        { "slang": "gtfoi", "original": "get the fuck over it" },
        { "slang": "gtfon", "original": "Get the fuck out noob" },
        { "slang": "gtfooh", "original": "get the fuck out of here" },
        { "slang": "gtfoomf", "original": "get the fuck out of my face" },
        { "slang": "gtfu", "original": "grow the fuck up" },
        { "slang": "gtfuotb", "original": "get the fuck up out this bitch" },
        { "slang": "gtg", "original": "got to go" },
        { "slang": "gtgb", "original": "got to go bye" },
        { "slang": "gtgbb", "original": "got to go bye bye" },
        { "slang": "gtgfn", "original": "got to go for now" },
        { "slang": "gtglyb", "original": "got to go love you bye" },
        { "slang": "gtgmmiloms", "original": "got to go my mum is looking over my shoulder" },
        { "slang": "gtgn", "original": "got to go now" },
        { "slang": "gtgp", "original": "got to go pee" },
        { "slang": "gtgpp", "original": "got to go pee pee" },
        { "slang": "gtgtb", "original": "got to go to bed" },
        { "slang": "gtgtpirio", "original": "got to go the price is right is on" },
        { "slang": "gtgtwn", "original": "Got to go to work now" },
        { "slang": "gth", "original": "go to hell" },
        { "slang": "gtha", "original": "go the hell away" },
        { "slang": "gthb", "original": "go to hell bitch" },
        { "slang": "gthmf", "original": "go to hell mothafucka" },
        { "slang": "gtho", "original": "get the hell out" },
        { "slang": "gthu", "original": "grow the heck up" },
        { "slang": "gthyfah", "original": "go to hell you fucking asshole" },
        { "slang": "gtk", "original": "good to know" },
        { "slang": "gtm", "original": "giggling to myself" },
        { "slang": "gtn", "original": "getting" },
        { "slang": "gtp", "original": "Got to pee" },
        { "slang": "gtr", "original": "Got to run" },
        { "slang": "gts", "original": "going to school" },
        { "slang": "gtsy", "original": "good to see you" },
        { "slang": "gttp", "original": "get to the point" },
        { "slang": "gtty", "original": "good talking to you" },
        { "slang": "gu", "original": "grow up" },
        { "slang": "gu2i", "original": "get used to it " },
        { "slang": "gud", "original": "good" },
        { "slang": "gudd", "original": "good" },
        { "slang": "gui", "original": "graphical user interface" },
        { "slang": "gurl", "original": "girl" },
        { "slang": "gurlz", "original": "girls" },
        { "slang": "guru", "original": "expert" },
        { "slang": "gw", "original": "good work" },
        { "slang": "gwijd", "original": "guess what i just did" },
        { "slang": "gwm", "original": "gay white male" },
        { "slang": "gwork", "original": "good work" },
        { "slang": "gwrk", "original": "good work" },
        { "slang": "gws", "original": "get well soon" },
        { "slang": "gwytose", "original": "go waste your time on someone else" },
        { "slang": "gy", "original": "gay" },
        { "slang": "gyal", "original": "girl" },
        { "slang": "gypo", "original": "Get Your Penis Out" },
        { "slang": "h&k", "original": "hugs and kisses" },
        { "slang": "h*r", "original": "homestar runner" },
        { "slang": "h+k", "original": "hugs and kisses" },
        { "slang": "h.o", "original": "hold on" },
        { "slang": "h/e", "original": "However" },
        { "slang": "h/mo", "original": "homo" },
        { "slang": "h/o", "original": "hold on" },
        { "slang": "h/u", "original": "hold up" },
        { "slang": "h/w", "original": "homework" },
        { "slang": "h2", "original": "Halo 2" },
        { "slang": "h2gtb", "original": "have to go to the bathroom" },
        { "slang": "h2o", "original": "water" },
        { "slang": "h2sys", "original": "hope to see you soon" },
        { "slang": "h3y", "original": "hey" },
        { "slang": "h4kz0r5", "original": "hackers" },
        { "slang": "h4x", "original": "Hacks" },
        { "slang": "h4x0r", "original": "hacker" },
        { "slang": "h4xor", "original": "hacker" },
        { "slang": "h4xr", "original": "hacker" },
        { "slang": "h4xrz", "original": "hackers" },
        { "slang": "h4xx0rz", "original": "hacker" },
        { "slang": "h4xxor", "original": "hacker" },
        { "slang": "h8", "original": "hate" },
        { "slang": "h80r", "original": "hater" },
        { "slang": "h82sit", "original": "hate to say it" },
        { "slang": "h83r", "original": "hater" },
        { "slang": "h8ed", "original": "hated" },
        { "slang": "h8er", "original": "hater" },
        { "slang": "h8r", "original": "hater" },
        { "slang": "h8red", "original": "Hatred" },
        { "slang": "h8s", "original": "hates" },
        { "slang": "h8t", "original": "hate" },
        { "slang": "h8t0r", "original": "hater" },
        { "slang": "h8t3r", "original": "hater" },
        { "slang": "h8te", "original": "hate" },
        { "slang": "h8tr", "original": "hater" },
        { "slang": "h8u", "original": "I Hate You" },
        { "slang": "h9", "original": "Husband in Room" },
        { "slang": "habt", "original": "how about this" },
        { "slang": "hafta", "original": "have to" },
        { "slang": "hagd", "original": "have a good day" },
        { "slang": "hagl", "original": "have a great life" },
        { "slang": "hagn", "original": "have a good night" },
        { "slang": "hago", "original": "have a good one" },
        { "slang": "hags", "original": "have a great summer" },
        { "slang": "hai", "original": "hello" },
        { "slang": "hait", "original": "hate" },
        { "slang": "hak", "original": "here's a kiss" },
        { "slang": "hakas", "original": "have a kick ass summer" },
        { "slang": "hammrd", "original": "hammered" },
        { "slang": "han", "original": "how about now" },
        { "slang": "hau", "original": "How Are You" },
        { "slang": "hav", "original": "have" },
        { "slang": "havnt", "original": "haven't" },
        { "slang": "hawf", "original": "Husband and Wife forever" },
        { "slang": "hawt", "original": "hot" },
        { "slang": "hawtie", "original": "hottie" },
        { "slang": "hax", "original": "Hacks" },
        { "slang": "hax0r", "original": "hacker" },
        { "slang": "hax0red", "original": "hacked" },
        { "slang": "hax0rz", "original": "Hackers" },
        { "slang": "haxer", "original": "Hacker" },
        { "slang": "haxor", "original": "hacker" },
        { "slang": "haxoring", "original": "hacking" },
        { "slang": "haxors", "original": "hackers" },
        { "slang": "haxorz", "original": "hackers" },
        { "slang": "haxxor", "original": "hacker" },
        { "slang": "haxxzor", "original": "Hacker" },
        { "slang": "haxz0r", "original": "Hacker" },
        { "slang": "haxzor", "original": "hacker" },
        { "slang": "hayd", "original": "how are you doing" },
        { "slang": "hb", "original": "hurry back" },
        { "slang": "hb4b", "original": "hoes before bros" },
        { "slang": "hbd", "original": "happy birthday" },
        { "slang": "hbic", "original": "head bitch in charge" },
        { "slang": "hbii", "original": "how big is it" },
        { "slang": "hbu", "original": "how about you" },
        { "slang": "hby", "original": "how about you" },
        { "slang": "hc", "original": "how come" },
        { "slang": "hcbt1", "original": "he could be the one" },
        { "slang": "hcib", "original": "how can it be" },
        { "slang": "hcihy", "original": "how can I help you" },
        { "slang": "hdop", "original": "Help Delete Online Predators" },
        { "slang": "hdu", "original": "how dare you" },
        { "slang": "hdydi", "original": "How do you do it" },
        { "slang": "hdydt", "original": "how did you do that" },
        { "slang": "heh", "original": "haha" },
        { "slang": "hella", "original": "very" },
        { "slang": "heya", "original": "hey" },
        { "slang": "heyt", "original": "hate" },
        { "slang": "heyy", "original": "hello" },
        { "slang": "heyya", "original": "hello" },
        { "slang": "hf", "original": "have fun" },
        { "slang": "hfn", "original": "Hell fucking no" },
        { "slang": "hfs", "original": "holy fucking shit!" },
        { "slang": "hfsbm", "original": "holy fucking shit batman" },
        { "slang": "hfwt", "original": "have fun with that" },
        { "slang": "hg", "original": "HockeyGod" },
        { "slang": "hght", "original": "height" },
        { "slang": "hhiad", "original": "holy hole in a doughnut" },
        { "slang": "hhiadb", "original": "Holy Hole in a Donut Batman" },
        { "slang": "hhok", "original": "Ha Ha Only Kidding" },
        { "slang": "hhyb", "original": "how have you been" },
        { "slang": "hi2u", "original": "hello" },
        { "slang": "hi2u2", "original": "hello to you too" },
        { "slang": "hiet", "original": "height" },
        { "slang": "hiik", "original": "Hell If I Know" },
        { "slang": "hijack", "original": "start an off topic discussion" },
        { "slang": "hith", "original": "how in the hell" },
        { "slang": "hiw", "original": "husband is watching" },
        { "slang": "hiya", "original": "hello " },
        { "slang": "hiybbprqag", "original": "copying somebody else's search results" },
        { "slang": "hj", "original": "hand job" },
        { "slang": "hl", "original": "Half-Life" },
        { "slang": "hl2", "original": "Half-Life 2" },
        { "slang": "hla", "original": "Hot lesbian action" },
        { "slang": "hlb", "original": "horny little bastard" },
        { "slang": "hld", "original": "hold" },
        { "slang": "hldn", "original": "hold on" },
        { "slang": "hldon", "original": "hold on" },
        { "slang": "hll", "original": "Hell" },
        { "slang": "hlm", "original": "he loves me" },
        { "slang": "hlo", "original": "hello" },
        { "slang": "hlp", "original": "help" },
        { "slang": "hly", "original": "holy" },
        { "slang": "hlysht", "original": "Holy shit" },
        { "slang": "hmb", "original": "hold me back" },
        { "slang": "hmewrk", "original": "homework" },
        { "slang": "hmfic", "original": "head mother fucker in charge" },
        { "slang": "hml", "original": "hate my life" },
        { "slang": "hmoj", "original": "holy mother of jesus" },
        { "slang": "hmp", "original": "help me please" },
        { "slang": "hmu", "original": "Hit Me Up" },
        { "slang": "hmul", "original": "Hit me up later" },
        { "slang": "hmus", "original": "Hit me up sometime" },
        { "slang": "hmw", "original": "homework" },
        { "slang": "hmwk", "original": "homework" },
        { "slang": "hmwrk", "original": "Homework" },
        { "slang": "hng", "original": "horny net geek" },
        { "slang": "hngry", "original": "hungry" },
        { "slang": "hnic", "original": "head nigger in charge" },
        { "slang": "ho", "original": "hold on" },
        { "slang": "hoas", "original": "Hang on a second" },
        { "slang": "hoay", "original": "how old are you" },
        { "slang": "hoh", "original": "head of household" },
        { "slang": "hom", "original": "home" },
        { "slang": "homey", "original": "Friend" },
        { "slang": "homie", "original": "good friend" },
        { "slang": "homo", "original": "homosexual" },
        { "slang": "hoopty", "original": "broke down automobile" },
        { "slang": "hott", "original": "hot" },
        { "slang": "howdey", "original": "hello" },
        { "slang": "howz", "original": "hows" },
        { "slang": "hpb", "original": "high ping bastard" },
        { "slang": "hpoa", "original": "Hot Piece of Ass" },
        { "slang": "hppy", "original": "Happy" },
        { "slang": "hpy", "original": "happy" },
        { "slang": "hpybdy", "original": "happy birthday" },
        { "slang": "hr", "original": "hour" },
        { "slang": "hre", "original": "here" },
        { "slang": "hrny", "original": "horny" },
        { "slang": "hrs", "original": "hours" },
        { "slang": "hru", "original": "how are you" },
        { "slang": "hrud", "original": "how are you doing" },
        { "slang": "hs", "original": "headshot" },
        { "slang": "hsd", "original": "high school dropout" },
        { "slang": "hsik", "original": "how should i know" },
        { "slang": "hsr", "original": "homestar runner" },
        { "slang": "hss", "original": "horse shit and splinters" },
        { "slang": "hswm", "original": "Have Sex With me" },
        { "slang": "ht", "original": "Heard Through" },
        { "slang": "htc", "original": "hit the cell" },
        { "slang": "htf", "original": "how the fuck" },
        { "slang": "htfu", "original": "Hurry the fuck up" },
        { "slang": "hth", "original": "hope that helps" },
        { "slang": "hthu", "original": "Hurry the hell up" },
        { "slang": "htr", "original": "hater" },
        { "slang": "http", "original": "hyper text transfer protocol" },
        { "slang": "hu", "original": "Hey you" },
        { "slang": "hubby", "original": "husband" },
        { "slang": "hud", "original": "Heads Up Display" },
        { "slang": "huggle", "original": "hug and cuddle" },
        { "slang": "hugz", "original": "hugs" },
        { "slang": "hun", "original": "honey" },
        { "slang": "hv", "original": "have" },
        { "slang": "hve", "original": "have" },
        { "slang": "hvnt", "original": "haven't" },
        { "slang": "hw", "original": "homework" },
        { "slang": "hw/hw", "original": "help me with homework " },
        { "slang": "hwg", "original": "here we go" },
        { "slang": "hwga", "original": "here we go again" },
        { "slang": "hwik", "original": "how would i know" },
        { "slang": "hwk", "original": "homework" },
        { "slang": "hwmbo", "original": "he who must be obeyed" },
        { "slang": "hwmnbn", "original": "he who must not be named" },
        { "slang": "hwms", "original": "hot wild monkey sex" },
        { "slang": "hwu", "original": "hey what's up" },
        { "slang": "hwz", "original": "how is" },
        { "slang": "hxc", "original": "hardcore" },
        { "slang": "hy", "original": "hell yeah" },
        { "slang": "hyb", "original": "how you been" },
        { "slang": "hyg", "original": "here you go" },
        { "slang": "hyk", "original": "how you know" },
        { "slang": "i <3 u", "original": "I love you" },
        { "slang": "i c", "original": "i see" },
        { "slang": "i8", "original": "alright" },
        { "slang": "i8u", "original": "i hate you" },
        { "slang": "i<3 u", "original": "i love you" },
        { "slang": "i<3u", "original": "I love you" },
        { "slang": "iab", "original": "I Am Bored" },
        { "slang": "iafh", "original": "I Am Fucking Hot" },
        { "slang": "iafi", "original": "I am from India" },
        { "slang": "iag", "original": "it's all good" },
        { "slang": "iah", "original": "i am horny" },
        { "slang": "iai", "original": "i am interested" },
        { "slang": "ianabs", "original": "I am not a brain surgeon" },
        { "slang": "ianacl", "original": "I am not a copyright lawyer" },
        { "slang": "ianal", "original": "I am not a lawyer" },
        { "slang": "ianalb", "original": "I am not a lawyer, but.." },
        { "slang": "ianars", "original": "I am not a rocket scientist" },
        { "slang": "ians", "original": "I am Not Sure" },
        { "slang": "ianyl", "original": "I am not your lawyer" },
        { "slang": "iap", "original": "I Am Pissed" },
        { "slang": "iasb", "original": "i am so bored" },
        { "slang": "iaspfm", "original": "i am sorry please forgive\nme" },
        { "slang": "iatb", "original": "I am the best" },
        { "slang": "iateu", "original": "i hate you" },
        { "slang": "iavb", "original": "i am very bored" },
        { "slang": "iaw", "original": "In Another Window" },
        { "slang": "iawtc", "original": "I agree with this comment" },
        { "slang": "iawtp", "original": "I agree with this post" },
        { "slang": "iawy", "original": "I agree with you" },
        { "slang": "ib", "original": "I'm back" },
        { "slang": "ibbl", "original": "I'll be back later" },
        { "slang": "ibcd", "original": "Idiot between chair & desk" },
        { "slang": "ibs", "original": "Internet Bitch Slap " },
        { "slang": "ibt", "original": "I'll be there" },
        { "slang": "ibtl", "original": "In Before The Lock" },
        { "slang": "ibw", "original": "I'll be waiting" },
        { "slang": "ic", "original": "I see" },
        { "slang": "icb", "original": "I can't believe" },
        { "slang": "icbi", "original": "i can't believe it" },
        { "slang": "icbiwoop", "original": "I chuckled, but it was out of pity." },
        { "slang": "icbt", "original": "i can't believe that" },
        { "slang": "icbu", "original": "I can't believe you" },
        { "slang": "icbyst", "original": "i cant believe you said that" },
        { "slang": "iccl", "original": "I could care less" },
        { "slang": "icgup", "original": "I can give you pleasure" },
        { "slang": "icic", "original": "I See. I See" },
        { "slang": "icp", "original": "insane clown posse" },
        { "slang": "icr", "original": "I can't rememer" },
        { "slang": "icsrg", "original": "I can still reach Google" },
        { "slang": "ictrn", "original": "I can't talk right now" },
        { "slang": "icty", "original": "i can't tell you " },
        { "slang": "icu", "original": "i see you" },
        { "slang": "icudk", "original": "in case you didn't know" },
        { "slang": "icup", "original": "i see you pee" },
        { "slang": "icw", "original": "I care why?" },
        { "slang": "icwudt", "original": "I see what you did there" },
        { "slang": "icwum", "original": "I see what you mean" },
        { "slang": "icydk", "original": "in csae you didn't know" },
        { "slang": "icydn", "original": "in case you didn't know" },
        { "slang": "icymi", "original": "in case you missed it" },
        { "slang": "id10t", "original": "idiot" },
        { "slang": "idbtwdsat", "original": "I don't believe they would do such a thing" },
        { "slang": "idby", "original": "I Don't Believe You" },
        { "slang": "idc", "original": "I don't care" },
        { "slang": "iddi", "original": "I didn't do it" },
        { "slang": "idec", "original": "I don't even care" },
        { "slang": "idek", "original": " I don't even know" },
        { "slang": "idfc", "original": "i don't fucking care" },
        { "slang": "idfk", "original": "i don't fucking know" },
        { "slang": "idfts", "original": "I don't fucking think so" },
        { "slang": "idgac", "original": "i don't give a crap" },
        { "slang": "idgad", "original": "I don't give a damn" },
        { "slang": "idgaf", "original": "i don't give a fuck" },
        { "slang": "idgaff", "original": "I don't give a flying fuck" },
        { "slang": "idgafs", "original": "I don't give a fucking shit" },
        { "slang": "idgara", "original": "I don't give a rat's ass" },
        { "slang": "idgas", "original": "i don't give a shit" },
        { "slang": "idgi", "original": "I don't get it" },
        { "slang": "idjit", "original": "idiot" },
        { "slang": "idk", "original": "I don't know" },
        { "slang": "idkbibt", "original": "I don't know but I've Been Told" },
        { "slang": "idke", "original": "I don't know ethier" },
        { "slang": "idkh", "original": "I don't know how" },
        { "slang": "idkh2s", "original": "i don't know how to spell" },
        { "slang": "idkt", "original": "I don't know that" },
        { "slang": "idkw", "original": "I don't know why" },
        { "slang": "idkwiwdwu", "original": "I don't know what I would do without you" },
        { "slang": "idkwts", "original": "I don't know what to say" },
        { "slang": "idkwurta", "original": "I don't know what you are talking about." },
        { "slang": "idkwym", "original": "I don't know what you mean" },
        { "slang": "idky", "original": "I don't know you" },
        { "slang": "idkyb", "original": "i don't know why but" },
        { "slang": "idkymb2", "original": "I didn't know yoru mom blogs too" },
        { "slang": "idl", "original": "I don't like" },
        { "slang": "idli", "original": "I don't like it" },
        { "slang": "idlu", "original": "i don't like you" },
        { "slang": "idly", "original": "I don't like you" },
        { "slang": "idlyitw", "original": "i don't like you in that way" },
        { "slang": "idm", "original": "I don't mind" },
        { "slang": "idmhw", "original": "im doing my homework" },
        { "slang": "idn", "original": "i don't know" },
        { "slang": "idnk", "original": "i don't know" },
        { "slang": "idno", "original": "i do not know" },
        { "slang": "idntk", "original": "i dont need to know" },
        { "slang": "idnwths", "original": "i do not want to have sex" },
        { "slang": "idonno", "original": "i do not know" },
        { "slang": "idop", "original": "it depends on price" },
        { "slang": "idot", "original": "idiot" },
        { "slang": "idr", "original": "I don't remember" },
        { "slang": "idrc", "original": "i don't really care" },
        { "slang": "idrfk", "original": "I don't really fucking know" },
        { "slang": "idrgaf", "original": "I don't really give a fuck" },
        { "slang": "idrgaff", "original": "i don't really give a flying fuck" },
        { "slang": "idrk", "original": "i don't really know" },
        { "slang": "idrts", "original": "I don't really think so" },
        { "slang": "idsw", "original": "i don't see why" },
        { "slang": "idtis", "original": "I don't think I should" },
        { "slang": "idtkso", "original": "i don't think so" },
        { "slang": "idts", "original": "i don't think so" },
        { "slang": "idunno", "original": "i do not know" },
        { "slang": "iduwym", "original": "I don't understand what you mean." },
        { "slang": "idw2", "original": "I don't want to" },
        { "slang": "idw2n", "original": "i don't want to know" },
        { "slang": "idwk", "original": "I don't wanna know" },
        { "slang": "idwt", "original": "i don't want to" },
        { "slang": "idwtg", "original": "I don't want to go" },
        { "slang": "idyat", "original": "idiot" },
        { "slang": "iebkac", "original": "issue exists between keyboard and chair" },
        { "slang": "ietf", "original": "internet engineering task force" },
        { "slang": "iff", "original": "if and only if" },
        { "slang": "ifhu", "original": "I fucking hate you" },
        { "slang": "ifhy", "original": "i fucking hate you" },
        { "slang": "ifk", "original": "I fucking know" },
        { "slang": "iflu", "original": "i fucking love you" },
        { "slang": "ifthtb", "original": "i find that hard to belive" },
        { "slang": "ifttt", "original": "if this then that " },
        { "slang": "ifwis", "original": "I forgot what I said" },
        { "slang": "ig", "original": "I guess" },
        { "slang": "ig2g", "original": "I got to go" },
        { "slang": "ig5oi", "original": "I got 5 on it " },
        { "slang": "igahp", "original": "I've got a huge penis" },
        { "slang": "igalboc", "original": "I've got a lovely bunch of cocnuts" },
        { "slang": "igg", "original": "i gotta go" },
        { "slang": "ight", "original": "alright" },
        { "slang": "igkymfa", "original": "I'm gonna kick your mother fucking ass" },
        { "slang": "igs", "original": "I guess so" },
        { "slang": "igt", "original": "I Got This" },
        { "slang": "igtg", "original": "i've got to go" },
        { "slang": "igtgt", "original": "I got to go tinkle" },
        { "slang": "igtkya", "original": "im going to kick your ass" },
        { "slang": "igu", "original": "i give up" },
        { "slang": "igyb", "original": "I Got Your Back" },
        { "slang": "ih", "original": "it happens" },
        { "slang": "ih2gp", "original": "I have to go pee" },
        { "slang": "ih2p", "original": "i'll have to pass" },
        { "slang": "ih8", "original": "i hate" },
        { "slang": "ih8mls", "original": "I hate my little sister " },
        { "slang": "ih8p", "original": "I hate parents" },
        { "slang": "ih8tu", "original": "i hate you" },
        { "slang": "ih8u", "original": "I hate you" },
        { "slang": "ih8usm", "original": "i hate you so much" },
        { "slang": "ih8y", "original": "I hate you" },
        { "slang": "ihac", "original": "I have a customer" },
        { "slang": "ihat3u", "original": "I hate you" },
        { "slang": "ihistr", "original": "i hope i spelled that right" },
        { "slang": "ihiwydt", "original": "I hate it when you do that" },
        { "slang": "ihml", "original": "I hate my life" },
        { "slang": "ihmp", "original": "i hate my parents" },
        { "slang": "ihnc", "original": "i have no clue" },
        { "slang": "ihnfc", "original": "I have no fucking clue" },
        { "slang": "ihni", "original": "i have no idea" },
        { "slang": "iht", "original": "I heard that" },
        { "slang": "ihtfp", "original": "I hate this fucking place" },
        { "slang": "ihtgttbwijd", "original": "I have to go to the bathroom, wait I just did." },
        { "slang": "ihtp", "original": "I Have To Poop" },
        { "slang": "ihtsm", "original": "i hate this so much" },
        { "slang": "ihtutbr", "original": "I have to use the bathroom" },
        { "slang": "ihu", "original": "I hate you" },
        { "slang": "ihurg", "original": "i hate your guts" },
        { "slang": "ihusb", "original": "i hate you so bad " },
        { "slang": "ihusfm", "original": "i hate you so fucking much" },
        { "slang": "ihusm", "original": "i hate you so much" },
        { "slang": "ihy", "original": "i hate you" },
        { "slang": "ihya", "original": "i hate you all" },
        { "slang": "ihysm", "original": "I hate you so much" },
        { "slang": "ihysmrn", "original": "i hate you so much right now" },
        { "slang": "iigh", "original": "alright" },
        { "slang": "iight", "original": "alright" },
        { "slang": "iiok", "original": "is it okay" },
        { "slang": "iirc", "original": "if I recall correctly" },
        { "slang": "iistgtbtipi", "original": "If It Sounds Too Good To Be True It Probably Is" },
        { "slang": "iit", "original": "is it tight" },
        { "slang": "iitywimwybmad", "original": "if I tell you what it means will you buy me a drink" },
        { "slang": "iitywybmad", "original": "if I tell you, will you buy me a drink?" },
        { "slang": "iiuc", "original": "if I understand correctly" },
        { "slang": "iiw2", "original": "is it web 2.0?" },
        { "slang": "iiwii", "original": "it is what it is" },
        { "slang": "ij", "original": "indide joke" },
        { "slang": "ijaf", "original": "it's just a fact" },
        { "slang": "ijcomk", "original": "i just came on my keyboard" },
        { "slang": "ijdk", "original": "I just don't know" },
        { "slang": "ijdl", "original": "I just died laughing" },
        { "slang": "ijeomk", "original": "I just ejaculated on my keybord" },
        { "slang": "ijf", "original": "i just farted" },
        { "slang": "ijgl", "original": "I just got laid" },
        { "slang": "ijit", "original": "idiot" },
        { "slang": "ijk", "original": "I'm Just kidding" },
        { "slang": "ijp", "original": "Internet job posting" },
        { "slang": "ijpmp", "original": "I just peed my pants" },
        { "slang": "ijpms", "original": "I just pissed myself" },
        { "slang": "ijr", "original": "i just remembered" },
        { "slang": "ijs", "original": "I'm just saying" },
        { "slang": "ijsabomomcibstg", "original": "I just saved a bunch of money on my car insurance by switching to geico" },
        { "slang": "ik", "original": "i know" },
        { "slang": "iki", "original": "i know it" },
        { "slang": "ikic", "original": "I know I can" },
        { "slang": "ikm", "original": "I know man" },
        { "slang": "ikr", "original": "I know really" },
        { "slang": "ikt", "original": "i knew that" },
        { "slang": "ikwud", "original": "I know what you did" },
        { "slang": "ikwum", "original": "I know what you meant" },
        { "slang": "ikwyl", "original": "I know where you live" },
        { "slang": "ikwym", "original": "i know what you mean" },
        { "slang": "ilbbaicnl", "original": "I like big butts and I can not lie" },
        { "slang": "ilbcnu", "original": "i'll be seeing you" },
        { "slang": "ilcul8r", "original": "I'll see you later" },
        { "slang": "ilhsm", "original": "i love him/her so much" },
        { "slang": "ili", "original": "i love it" },
        { "slang": "ilk2fku", "original": "I would like to fuck you" },
        { "slang": "ilml", "original": "I Love My Life" },
        { "slang": "ilms", "original": "I love my self" },
        { "slang": "ilotibinlirl", "original": "I'm laughing on the internet, but I'm not laughing in real life" },
        { "slang": "ilshipmp", "original": "I laughed so hard I peed my pants" },
        { "slang": "iltf", "original": "i love to fuck" },
        { "slang": "iltwymmf", "original": "I love the way you make me feel" },
        { "slang": "ilu", "original": "I love you" },
        { "slang": "ilu2", "original": "I love you too" },
        { "slang": "iluaaf", "original": "i love you as a friend" },
        { "slang": "ilulafklc", "original": "I love you like a fat kid loves cake." },
        { "slang": "ilum", "original": "i love you more" },
        { "slang": "ilusfm", "original": "I love you so fucking much" },
        { "slang": "ilusm", "original": "I love you So much" },
        { "slang": "iluvm", "original": "I Love You Very Much" },
        { "slang": "iluvu", "original": "i love you" },
        { "slang": "iluvya", "original": "i love you" },
        { "slang": "iluwamh", "original": "i love  you with all my heart" },
        { "slang": "ilvu", "original": "i love you" },
        { "slang": "ily", "original": "i love you" },
        { "slang": "ily2", "original": "i love you too" },
        { "slang": "ily4e", "original": "i love you forever" },
        { "slang": "ily4ev", "original": "i love you forever" },
        { "slang": "ilyaas", "original": "I Love You As A Sister" },
        { "slang": "ilyal", "original": "I like you a lot" },
        { "slang": "ilyb", "original": "i love you bitch" },
        { "slang": "ilybby", "original": "i love you baby" },
        { "slang": "ilybtid", "original": "I Love You But Then I Don't" },
        { "slang": "ilyf", "original": "I'll Love You Forever" },
        { "slang": "ilygsm", "original": "i love you guys so much" },
        { "slang": "ilykthnxbai", "original": "i love you k thanks bye" },
        { "slang": "ilyl", "original": "i love you loads" },
        { "slang": "ilylab", "original": "I love you like a brother" },
        { "slang": "ilylabf", "original": "I love you like a best friend" },
        { "slang": "ilylafklc", "original": "i love you like a fat kid loves cake" },
        { "slang": "ilylas", "original": "i love you like a sister" },
        { "slang": "ilylc", "original": "i love you like crazy" },
        { "slang": "ilym", "original": " i love you more" },
        { "slang": "ilymtyk", "original": "i love you more than you know" },
        { "slang": "ilymtylm", "original": "i love you more than you love me" },
        { "slang": "ilysfm", "original": "i love you so fucking much" },
        { "slang": "ilysfmb", "original": "i love you so fucking much baby" },
        { "slang": "ilysm", "original": "i love you so much" },
        { "slang": "ilysmih", "original": "i love you so much it hurts" },
        { "slang": "ilysmm", "original": "i love you so much more" },
        { "slang": "ilysmydek", "original": "I Love You So Much You Don't Even Know" },
        { "slang": "ilysvm", "original": "i love you so very much" },
        { "slang": "ilyvm", "original": "i love you very much" },
        { "slang": "ilywamh", "original": "I love you with all my heart" },
        { "slang": "im", "original": "Instant Message" },
        { "slang": "im'd", "original": "instant messaged" },
        { "slang": "im26c4u", "original": "I am too sexy for you" },
        { "slang": "ima", "original": "I am a" },
        { "slang": "imao", "original": "in my arrogant opinion" },
        { "slang": "imb", "original": "I am back" },
        { "slang": "imcdo", "original": "in my conceited dogmatic opinion" },
        { "slang": "imed", "original": "instant messaged" },
        { "slang": "imfao", "original": "In My Fucking Arrogant Opinion" },
        { "slang": "imfo", "original": "in my fucking opinion" },
        { "slang": "imh", "original": "I am here" },
        { "slang": "imhbco", "original": "In my humble but correct opinion" },
        { "slang": "imhe", "original": "in my humble experience" },
        { "slang": "imho", "original": "in my humble opinion" },
        { "slang": "imm", "original": "instant message me" },
        { "slang": "imma", "original": "I'm going to" },
        { "slang": "imnerho", "original": "In my not even remotely humble opinion" },
        { "slang": "imnl", "original": "I'm not laughing" },
        { "slang": "imnshmfo", "original": "In My Not So Humble Mother Fucking Opinion" },
        { "slang": "imnsho", "original": "in my not so humble opinion" },
        { "slang": "imo", "original": "in my opinion" },
        { "slang": "imoo", "original": "in my own opinion" },
        { "slang": "impo", "original": "In My Personal Opinion" },
        { "slang": "impov", "original": "in my point of view" },
        { "slang": "imr", "original": "in my room" },
        { "slang": "imsb", "original": "i am so bored" },
        { "slang": "imsry", "original": "I am sorry" },
        { "slang": "imtaw", "original": "it may take a while" },
        { "slang": "imts", "original": "I meant to say" },
        { "slang": "imu", "original": "i miss you " },
        { "slang": "imusm", "original": "I miss you so much" },
        { "slang": "imvho", "original": "in my very humble opinion" },
        { "slang": "imwtk", "original": "Inquiring minds want to know" },
        { "slang": "imy", "original": "I miss you" },
        { "slang": "imy2", "original": "i miss you to" },
        { "slang": "imya", "original": "i miss you already" },
        { "slang": "imysfm", "original": "i miss you so fucking much" },
        { "slang": "in2", "original": "into" },
        { "slang": "inb4", "original": "in before" },
        { "slang": "inbd", "original": "it's no big deal" },
        { "slang": "incld", "original": "include" },
        { "slang": "incrse", "original": "increase" },
        { "slang": "ind2p", "original": "I need to pee" },
        { "slang": "indie", "original": "independent" },
        { "slang": "inef", "original": "it's not even funny" },
        { "slang": "inet", "original": "internet" },
        { "slang": "inh", "original": "I need help" },
        { "slang": "inho", "original": "in my honest opinion" },
        { "slang": "inhwh", "original": "I need homework help" },
        { "slang": "init", "original": "isn't it" },
        { "slang": "inmp", "original": "it's not my problem" },
        { "slang": "innit", "original": "isn't it" },
        { "slang": "ino", "original": "I know" },
        { "slang": "instagib", "original": "instant kill" },
        { "slang": "instakill", "original": "instant kill" },
        { "slang": "intarwebs", "original": "internet" },
        { "slang": "intel", "original": "intelligence" },
        { "slang": "interweb", "original": "internet" },
        { "slang": "intpftpotm", "original": "I nominate this post for the post of the month" },
        { "slang": "inttwmf", "original": "I am Not Typing This With My Fingers" },
        { "slang": "invu", "original": "I envy you" },
        { "slang": "ioh", "original": "I'm out of here" },
        { "slang": "iois", "original": "Indicators of Interest" },
        { "slang": "iokiya", "original": "it's ok if you are" },
        { "slang": "iomw", "original": "I'm on my way" },
        { "slang": "ionno", "original": "I don't know" },
        { "slang": "iono", "original": "I don't know" },
        { "slang": "iotd", "original": "image of the day" },
        { "slang": "iou", "original": "i owe you" },
        { "slang": "iow", "original": "in other words" },
        { "slang": "ioya", "original": "I'd Own Your Ass" },
        { "slang": "ioyk", "original": "if only you knew" },
        { "slang": "ip", "original": "internet protocol" },
        { "slang": "irc", "original": "internet relay chat" },
        { "slang": "ircd", "original": "Internet Relay Chat daemon" },
        { "slang": "irdc", "original": "I really don't care" },
        { "slang": "irdgaf", "original": "i really don't give a fuck" },
        { "slang": "irdk", "original": "I really don't know" },
        { "slang": "irgtgbtw", "original": "I've really got to get back to work" },
        { "slang": "irhtgttbr", "original": "I really have to go to the bathroom" },
        { "slang": "irhy", "original": "i really hate you" },
        { "slang": "irl", "original": "in real life" },
        { "slang": "irly", "original": "I really love you" },
        { "slang": "irt", "original": "in reply to" },
        { "slang": "irtf", "original": "I'll return the favor" },
        { "slang": "is2g", "original": "i swear to god" },
        { "slang": "isb", "original": "I'm so bored." },
        { "slang": "isbya", "original": "im sorry but you asked" },
        { "slang": "isd", "original": "internet slang dictionary" },
        { "slang": "ise", "original": "internal server error" },
        { "slang": "isfly", "original": "i so fucking love you" },
        { "slang": "isg", "original": "I speak geek" },
        { "slang": "ishii", "original": "i see how it is" },
        { "slang": "isianmtu", "original": "I swear I am not making this up" },
        { "slang": "isj", "original": "inside joke" },
        { "slang": "iso", "original": "In Search Of" },
        { "slang": "isp", "original": "internet service provider" },
        { "slang": "iss", "original": "im so sorry" },
        { "slang": "istg", "original": "i swear to god" },
        { "slang": "istr", "original": "I seem to remember" },
        { "slang": "istwfn", "original": "I stole this word from noslang.com" },
        { "slang": "iswydt", "original": "i see what you did there" },
        { "slang": "ita", "original": "I Totally Agree" },
        { "slang": "itb", "original": "in the butt" },
        { "slang": "itc", "original": "in that case" },
        { "slang": "itd", "original": "in the dark" },
        { "slang": "ite", "original": "alright" },
        { "slang": "itk", "original": "in the know" },
        { "slang": "itn", "original": "I think not" },
        { "slang": "itt", "original": "in this thread" },
        { "slang": "ityltk", "original": "I thought you'd like to know" },
        { "slang": "itys", "original": " i told you so" },
        { "slang": "itz", "original": "it's" },
        { "slang": "itzk", "original": "it's ok" },
        { "slang": "iucmd", "original": "if you catch my drift" },
        { "slang": "iukwim", "original": "if you know what i mean" },
        { "slang": "iunno", "original": "I don't know" },
        { "slang": "iuno", "original": "i dunno" },
        { "slang": "ive", "original": "i have" },
        { "slang": "iw2f", "original": "i want to fuck" },
        { "slang": "iw2fu", "original": "i want to fuck you" },
        { "slang": "iw2mu", "original": "I want to meet you" },
        { "slang": "iwaa", "original": "It was an accident" },
        { "slang": "iwbrbl@r", "original": "I will be right back later" },
        { "slang": "iwc", "original": "In Which Case" },
        { "slang": "iwfusb", "original": "i wanna fuck you so bad" },
        { "slang": "iwfy", "original": "I want to fuck you" },
        { "slang": "iwfybo", "original": "i will fuck your brains out" },
        { "slang": "iwg", "original": "it was good" },
        { "slang": "iwhi", "original": "I would hit it" },
        { "slang": "iwhswu", "original": "I want to have sex with you" },
        { "slang": "iwjk", "original": "i was just kidding" },
        { "slang": "iwk", "original": "I wouldn't know" },
        { "slang": "iwlu4e", "original": "I will love you for ever" },
        { "slang": "iwmu", "original": "i will miss you" },
        { "slang": "iwmy", "original": "i will miss you" },
        { "slang": "iws", "original": "i want sex" },
        { "slang": "iwsn", "original": "i want sex now" },
        { "slang": "iwsul8r", "original": "I will see you later" },
        { "slang": "iwtfu", "original": "i want to fuck you" },
        { "slang": "iwtfy", "original": "i want to fuck you" },
        { "slang": "iwthswy", "original": "i want to have sex with you" },
        { "slang": "iwtk", "original": "I Want to Know" },
        { "slang": "iwtly", "original": "i want to love you" },
        { "slang": "iwu", "original": "i want you" },
        { "slang": "iwuwh", "original": "i wish you were here " },
        { "slang": "iwy", "original": "i want you" },
        { "slang": "iwyb", "original": "I want your body" },
        { "slang": "iwyn", "original": "I want you now" },
        { "slang": "iwythmb", "original": "i want you to have my baby" },
        { "slang": "iyam", "original": "if you ask me" },
        { "slang": "iyc", "original": "if you can" },
        { "slang": "iyd", "original": "In Your Dreams" },
        { "slang": "iydhantsdsaaa", "original": "If you don't have anything nice to say don't say anything at all" },
        { "slang": "iydmma", "original": "if you don't mind me asking" },
        { "slang": "iyf", "original": "In your face" },
        { "slang": "iyflg", "original": "If You're Feeling Less Generous" },
        { "slang": "iygm", "original": "if you get me" },
        { "slang": "iykwim", "original": "if you know what I mean" },
        { "slang": "iym", "original": "I am your man" },
        { "slang": "iyo", "original": "in your opinion" },
        { "slang": "iyq", "original": "I like you" },
        { "slang": "iyss", "original": "if you say so" },
        { "slang": "iyswim", "original": "if you see what I mean" },
        { "slang": "iywt", "original": "if you want to" },
        { "slang": "iz", "original": "is" },
        { "slang": "j-c", "original": "just chilling" },
        { "slang": "j/a", "original": "Just Asking" },
        { "slang": "j/c", "original": "just curious" },
        { "slang": "j/j", "original": "just joking" },
        { "slang": "j/k", "original": "just kidding" },
        { "slang": "j/o", "original": "jackoff" },
        { "slang": "j/p", "original": "just playing" },
        { "slang": "j/s", "original": "just saying" },
        { "slang": "j/t", "original": "just talking" },
        { "slang": "j/w", "original": "just wondering" },
        { "slang": "j00", "original": "you" },
        { "slang": "j00r", "original": "your" },
        { "slang": "j2bs", "original": "just to be sure" },
        { "slang": "j2c", "original": "just too cute" },
        { "slang": "j2f", "original": "just too funny" },
        { "slang": "j2luk", "original": "just to let you know" },
        { "slang": "j2lyk", "original": "just to let you know" },
        { "slang": "j4f", "original": "just for fun" },
        { "slang": "j4g", "original": "just for grins" },
        { "slang": "j4l", "original": "just for laughs" },
        { "slang": "j4u", "original": "just for you" },
        { "slang": "jalaudlm", "original": "just as long as you don't leave me" },
        { "slang": "jas", "original": "just a second" },
        { "slang": "jb", "original": "jailbait" },
        { "slang": "jbu", "original": "just between us" },
        { "slang": "jc", "original": "just curious" },
        { "slang": "jcam", "original": "just checking away message" },
        { "slang": "jcath", "original": "Just chilling at the house" },
        { "slang": "jdfi", "original": "Just fucking do it" },
        { "slang": "jebus", "original": "Jesus" },
        { "slang": "jeomk", "original": "Just ejaculated on my keyboard" },
        { "slang": "jf", "original": "just fooling" },
        { "slang": "jfc", "original": "Jesus fucking Christ" },
        { "slang": "jfdi", "original": "Just Fucking Do It!" },
        { "slang": "jff", "original": "just for fun" },
        { "slang": "jfg", "original": "just for giggles" },
        { "slang": "jfgi", "original": "just fucking google it" },
        { "slang": "jfi", "original": "just forget it" },
        { "slang": "jfj", "original": "jump for joy" },
        { "slang": "jfk", "original": "Just fucking kidding" },
        { "slang": "jfl", "original": "just for laughs" },
        { "slang": "jflts", "original": "just felt like typing something" },
        { "slang": "jfn", "original": "just for now" },
        { "slang": "jfo", "original": "just fuck off" },
        { "slang": "jfr", "original": "Just for reference" },
        { "slang": "jftr", "original": "just for the record" },
        { "slang": "jfu", "original": "just for you" },
        { "slang": "jfwy", "original": "just fucking with you" },
        { "slang": "jg2h", "original": "just go to hell" },
        { "slang": "jgiyn", "original": "Just google it you noob" },
        { "slang": "jgtfooh", "original": "just get the fuck out of here" },
        { "slang": "jh", "original": "Just hanging" },
        { "slang": "jhm", "original": "just hold me" },
        { "slang": "jho", "original": "just hanging out" },
        { "slang": "jic", "original": "just in case" },
        { "slang": "jit", "original": "just in time" },
        { "slang": "jizz", "original": "semen" },
        { "slang": "jj", "original": "just joking" },
        { "slang": "jj/k", "original": "just joking" },
        { "slang": "jja", "original": "just joking around" },
        { "slang": "jk", "original": "just kidding" },
        { "slang": "jka", "original": "just kidding around" },
        { "slang": "jking", "original": "joking" },
        { "slang": "jkl", "original": "just kidding loser" },
        { "slang": "jklol", "original": "Just Kidding Laughing Out Loud" },
        { "slang": "jkn", "original": "joking" },
        { "slang": "jks", "original": "jokes" },
        { "slang": "jkz", "original": "jokes" },
        { "slang": "jlma", "original": "just leave me alone" },
        { "slang": "jlt", "original": "just like that" },
        { "slang": "jm", "original": "Just Messing" },
        { "slang": "jma", "original": "just messing around" },
        { "slang": "jml", "original": "just my luck" },
        { "slang": "jmo", "original": "just my opinion" },
        { "slang": "jms", "original": "just making sure" },
        { "slang": "jom", "original": "just one minuite" },
        { "slang": "joo", "original": "you" },
        { "slang": "jooc", "original": "just out of curiosity" },
        { "slang": "jooce", "original": "Juice" },
        { "slang": "joor", "original": "your" },
        { "slang": "jp", "original": "just playing" },
        { "slang": "js", "original": "just saying" },
        { "slang": "jsa", "original": "just stop already" },
        { "slang": "jsing", "original": "just saying" },
        { "slang": "jst", "original": "just" },
        { "slang": "jsuk", "original": "just so you know" },
        { "slang": "jsun", "original": "Just so you know" },
        { "slang": "jsut", "original": "just" },
        { "slang": "jsyk", "original": "Just so you know" },
        { "slang": "jsyn", "original": "just so you know" },
        { "slang": "jtay", "original": "just thinking about you" },
        { "slang": "jtbs", "original": "Just To Be Sure" },
        { "slang": "jtc", "original": "Join the club" },
        { "slang": "jtfo", "original": "joke the fuck out" },
        { "slang": "jtluk", "original": "just to let you know" },
        { "slang": "jtlyk", "original": "just to let you know" },
        { "slang": "jtoi", "original": "just thought of it" },
        { "slang": "jtol", "original": "just thinking out loud" },
        { "slang": "jttsiowctw", "original": "just testing to see if other websites copy this word" },
        { "slang": "jtty", "original": "just to tell you" },
        { "slang": "jtumltk", "original": "just thought you might like to know" },
        { "slang": "jtwii", "original": "just the way it is." },
        { "slang": "jtwiw", "original": "just the way it was." },
        { "slang": "jtyltk", "original": "just thought you'd like to know" },
        { "slang": "jtysk", "original": "just thought you should know" },
        { "slang": "jumping the couch", "original": "acting strange" },
        { "slang": "jus", "original": "just" },
        { "slang": "juss", "original": "just" },
        { "slang": "juz", "original": "just" },
        { "slang": "juzt", "original": "just" },
        { "slang": "jw", "original": "just wondering" },
        { "slang": "jw2k", "original": "just wanted to know" },
        { "slang": "jwas", "original": "just wait a second" },
        { "slang": "jwing", "original": "just wondering" },
        { "slang": "jwtlyk", "original": "Just wanted to let you know" },
        { "slang": "jyfihp", "original": "jam your finger in her pussy" }
    ]
}
