module.exports = {
  range: ['k', 'l', 'm', 'n', 'o'],
  words: [
    { "slang": "k", "original": "ok" },
    { "slang": "k3wl", "original": "cool" },
    { "slang": "ka", "original": "Kick Ass" },
    { "slang": "kafn", "original": "kill all fucking noobs" },
    { "slang": "kah", "original": "kisses and hugs" },
    { "slang": "kaw", "original": "kick ass work" },
    { "slang": "kay", "original": "okay" },
    { "slang": "kb", "original": "KiloBite" },
    { "slang": "kcco", "original": "keep calm chive on" },
    { "slang": "kek", "original": "laughing out loud" },
    { "slang": "kewel", "original": "cool" },
    { "slang": "kewl", "original": "cool" },
    { "slang": "kfc", "original": "kentucky fried chicken" },
    { "slang": "khitbash", "original": "kick her in the box and shove her" },
    { "slang": "khuf", "original": "know how you feel" },
    { "slang": "kia", "original": "Killed In Action" },
    { "slang": "kib", "original": "okay, im back" },
    { "slang": "kic", "original": "keep it clean" },
    { "slang": "kicks", "original": "sneakers" },
    { "slang": "kig", "original": "keep it going" },
    { "slang": "kiled", "original": "killed" },
    { "slang": "kinda", "original": "kind of" },
    { "slang": "kir", "original": "kid in room" },
    { "slang": "kis", "original": "keep it simple" },
    { "slang": "kisa", "original": "knight in shining armor" },
    { "slang": "kit", "original": "keep in touch" },
    { "slang": "kitfo", "original": "knock it the fuck off" },
    { "slang": "kitteh", "original": "kitten" },
    { "slang": "kiu", "original": "Keep it up" },
    { "slang": "kiwf", "original": "Kill It With Fire" },
    { "slang": "kk", "original": "ok" },
    { "slang": "kkk", "original": "ku klux klan" },
    { "slang": "kkthnxbye", "original": "okay thanks bye" },
    { "slang": "kky", "original": "kinky" },
    { "slang": "kl", "original": "cool" },
    { "slang": "km", "original": "kiss me" },
    { "slang": "kma", "original": "kiss my ass" },
    { "slang": "kmag", "original": "kiss my ass goodbye" },
    { "slang": "kmao", "original": "kick my ass off" },
    { "slang": "kmb", "original": "kiss my butt" },
    { "slang": "kmfa", "original": "kiss my fucking ass" },
    { "slang": "kmhba", "original": "kiss my hairy big ass" },
    { "slang": "kml", "original": "Killing Myself Laughing" },
    { "slang": "kmn", "original": "kill me now" },
    { "slang": "kmp", "original": "kill me please" },
    { "slang": "kmsl", "original": "killing myself laughing" },
    { "slang": "kmswl", "original": "killing myself with laughter" },
    { "slang": "knackered", "original": "drunk" },
    { "slang": "knewb", "original": "new player" },
    { "slang": "knn", "original": "fuck your mother" },
    { "slang": "kno", "original": "know" },
    { "slang": "knw", "original": "know" },
    { "slang": "ko", "original": "knock out" },
    { "slang": "kol", "original": "kiss on lips" },
    { "slang": "koo", "original": "cool" },
    { "slang": "kool", "original": "cool" },
    { "slang": "kos", "original": "kid over shoulder" },
    { "slang": "kotc", "original": "kiss on the cheek" },
    { "slang": "kotl", "original": "kiss on the lips" },
    { "slang": "kotor", "original": "Knights of the old republic" },
    { "slang": "kots", "original": "keep on talking shit" },
    { "slang": "kpc", "original": "keeping parents clueless" },
    { "slang": "ks", "original": "kill steal" },
    { "slang": "kss", "original": "kiss" },
    { "slang": "kssd", "original": "kissed" },
    { "slang": "kt", "original": "keep talking" },
    { "slang": "ktc", "original": "kill the cat" },
    { "slang": "ktfo", "original": "knocked the fuck out" },
    { "slang": "kthanxbi", "original": "Okay, thanks. Bye." },
    { "slang": "kthnxbai", "original": "Okay, thanks, bye" },
    { "slang": "kthnxbye", "original": "Okay, thanks, bye" },
    { "slang": "kthx", "original": "ok, thank you" },
    { "slang": "kthxbai", "original": "ok thanks bye!" },
    { "slang": "kthxbi", "original": "ok, thank you, goodbye" },
    { "slang": "kthxbye", "original": "ok, thank you, goodbye" },
    { "slang": "kthxbye", "original": "ok, thank you, goodbye" },
    { "slang": "kthxgb", "original": "ok thanks goodbye" },
    { "slang": "kthxmn", "original": "Ok Thanks Man" },
    { "slang": "kthz", "original": "ok thanks" },
    { "slang": "ktnx", "original": "Okay and Thanks" },
    { "slang": "kuhl", "original": "cool" },
    { "slang": "kul", "original": "cool" },
    { "slang": "kute", "original": "cute" },
    { "slang": "kutgw", "original": "Keep Up The good Work" },
    { "slang": "kuwl", "original": "cool" },
    { "slang": "kwik", "original": "quick" },
    { "slang": "kwim", "original": "Know What I Mean" },
    { "slang": "kwis", "original": "Know what I'm saying?" },
    { "slang": "kwit", "original": "quit" },
    { "slang": "kwiz", "original": "quiz" },
    { "slang": "kwl", "original": "cool" },
    { "slang": "kwtsds", "original": "Kiss where the sun don't shine" },
    { "slang": "kyag", "original": "Kiss Your Ass Goodbye" },
    { "slang": "kyfag", "original": "kiss your fucking ass goodbye" },
    { "slang": "kyfc", "original": "keep your fingers crossed" },
    { "slang": "kyko", "original": "keep your knickers on" },
    { "slang": "kyms", "original": "keep your mouth shut" },
    { "slang": "kys", "original": "kill yourself" },
    { "slang": "l0lz", "original": "laugh out loud" },
    { "slang": "l2", "original": "learn to" },
    { "slang": "l2m", "original": "listening to music" },
    { "slang": "l2ms", "original": "laughing to myself" },
    { "slang": "l2p", "original": "learn to play" },
    { "slang": "l2r", "original": "Learn to read" },
    { "slang": "l337", "original": "elite" },
    { "slang": "l33t", "original": "elite" },
    { "slang": "l4m3rz", "original": "lamers" },
    { "slang": "l8", "original": "late" },
    { "slang": "l84skool", "original": "late for school" },
    { "slang": "l8a", "original": "later" },
    { "slang": "l8er", "original": "later" },
    { "slang": "l8ers", "original": "Later" },
    { "slang": "l8r", "original": "see you later" },
    { "slang": "l8rs", "original": "laters" },
    { "slang": "l8rz", "original": "later" },
    { "slang": "l8s", "original": "later" },
    { "slang": "l8t", "original": "later" },
    { "slang": "l8ta", "original": "later" },
    { "slang": "l8ter", "original": "later" },
    { "slang": "l8tr", "original": "later" },
    { "slang": "l@u", "original": "laughing at you" },
    { "slang": "laff", "original": "laugh" },
    { "slang": "lafs", "original": "love at first sight" },
    { "slang": "lak", "original": "love and kisses" },
    { "slang": "lal", "original": "laughing a little" },
    { "slang": "lalol", "original": "lots and lots of laughs" },
    { "slang": "lam", "original": "leave a message" },
    { "slang": "lamf", "original": "like a motherfucker" },
    { "slang": "lan", "original": "local area network" },
    { "slang": "lappy", "original": "Laptop" },
    { "slang": "larp", "original": "live action role-play" },
    { "slang": "lasb", "original": "Lame Ass Stupid Bitch" },
    { "slang": "lat", "original": "laugh at that" },
    { "slang": "lata", "original": "later" },
    { "slang": "lates", "original": "later" },
    { "slang": "latn", "original": "laugh at the newbs" },
    { "slang": "latr", "original": "Later" },
    { "slang": "latwttb", "original": "laughing all the way to the bank" },
    { "slang": "lau", "original": "laugh at you" },
    { "slang": "lawd", "original": "lord" },
    { "slang": "lawl", "original": "lauging out loud with a southern drawl" },
    { "slang": "lawl'd", "original": "laughed out loud" },
    { "slang": "lawled", "original": "laughed out loud" },
    { "slang": "lawls", "original": "laughing out loud with a southern drawl" },
    { "slang": "lawlz", "original": "laughing out loud with a southern drawl" },
    { "slang": "lazer", "original": "laser" },
    { "slang": "lazor", "original": "laser" },
    { "slang": "lbh", "original": "let's be honest" },
    { "slang": "lbnr", "original": "laughing but not really" },
    { "slang": "lbo", "original": "laughing butt off " },
    { "slang": "lbr", "original": "little boy's room" },
    { "slang": "lbvs", "original": "laughing but very serious" },
    { "slang": "lcsnpc", "original": "low cost small notebook personal computer" },
    { "slang": "ldr", "original": "Long-distance relationship" },
    { "slang": "lee7", "original": "elite" },
    { "slang": "leet", "original": "elite" },
    { "slang": "legit", "original": "legitimate" },
    { "slang": "leik", "original": "like" },
    { "slang": "leme", "original": "let me" },
    { "slang": "lemme", "original": "let me" },
    { "slang": "lesbo", "original": "lesbian" },
    { "slang": "less than 3", "original": "love" },
    { "slang": "less than three", "original": "love" },
    { "slang": "lez", "original": "Lesbian" },
    { "slang": "lezbean", "original": "lesbian" },
    { "slang": "lezbo", "original": "lesbian" },
    { "slang": "lezzzie", "original": "lesbian" },
    { "slang": "lf", "original": "looking for" },
    { "slang": "lf1m", "original": "Looking for one more" },
    { "slang": "lf2m", "original": "looking for 2 more" },
    { "slang": "lfg", "original": "Looking for group" },
    { "slang": "lfl", "original": "let's fuck later" },
    { "slang": "lfm", "original": "looking for mate" },
    { "slang": "lfnar", "original": "laughing for no aparent reason" },
    { "slang": "lfp", "original": "looking for pussy" },
    { "slang": "lfr", "original": "Laughing for real" },
    { "slang": "lgb", "original": "lesbian/gay/bisexual" },
    { "slang": "lgbnaf", "original": "lets get butt naked and fuck" },
    { "slang": "lgbtq", "original": "Lesbien, Gay, Bisexual, Transgender and Queer." },
    { "slang": "lgds", "original": "let's go do something" },
    { "slang": "lgf", "original": "little green footballs" },
    { "slang": "lggd", "original": "let's go get drunk" },
    { "slang": "lgn", "original": "link goes nowhere" },
    { "slang": "lgo", "original": "life goes on" },
    { "slang": "lgot", "original": "let's go out tonight" },
    { "slang": "lgr", "original": "little girls room" },
    { "slang": "lgs", "original": "let's go shopping!" },
    { "slang": "lhao", "original": "laughing her ass off" },
    { "slang": "lhs", "original": "lets have sex" },
    { "slang": "lhsrn", "original": "let's have sex right now" },
    { "slang": "lic", "original": "like i care" },
    { "slang": "liec", "original": "like i even care" },
    { "slang": "liek", "original": "like" },
    { "slang": "liekz", "original": "likes" },
    { "slang": "lifo", "original": "last in first out" },
    { "slang": "ligaff", "original": "like I give a flying fuck" },
    { "slang": "ligafs", "original": "like I give a flying shit" },
    { "slang": "ligas", "original": "like I give a shit" },
    { "slang": "lih", "original": "Laugh in head" },
    { "slang": "liita", "original": "love is in the air" },
    { "slang": "lik", "original": "like" },
    { "slang": "lil", "original": "little" },
    { "slang": "lim", "original": "Like it Matters" },
    { "slang": "limh", "original": "laugh in my head" },
    { "slang": "liol", "original": "laugh insanely out loud" },
    { "slang": "lirl", "original": "laughing in real life" },
    { "slang": "liu", "original": "Look It Up" },
    { "slang": "liv", "original": "live" },
    { "slang": "liyf", "original": "laughing in your face" },
    { "slang": "lj", "original": "live journal" },
    { "slang": "lk", "original": "like" },
    { "slang": "lke", "original": "like" },
    { "slang": "llab", "original": "Laughing like a bitch." },
    { "slang": "llap", "original": "live long and prosper" },
    { "slang": "llc", "original": "laughing like crazy" },
    { "slang": "llf", "original": "laugh like fuck" },
    { "slang": "llh", "original": "laughing like hell" },
    { "slang": "llol", "original": "literally laughing out loud" },
    { "slang": "lltnt", "original": "live like theres no tomorrow " },
    { "slang": "lm4aq", "original": "Let's meet for a quickie." },
    { "slang": "lma", "original": "leave me alone" },
    { "slang": "lmamf", "original": "leave me alone mother fucker" },
    { "slang": "lmao", "original": "laughing my ass off" },
    { "slang": "lmaol", "original": "laughing my ass out loud" },
    { "slang": "lmaomtoaoa", "original": "Laugh my ass off many times over and over again" },
    { "slang": "lmaonade", "original": "laughing my ass off" },
    { "slang": "lmaool", "original": "laughing my ass off out loud " },
    { "slang": "lmaootf", "original": "Laughing my ass off on the floor " },
    { "slang": "lmaorof", "original": "Laughing my Ass off Rolling on the floor" },
    { "slang": "lmaorotf", "original": "laughing my ass off rolling on the floor" },
    { "slang": "lmaowrotf", "original": "Laughing my ass of while rolling on the floor" },
    { "slang": "lmaowtntpm", "original": "laughing my ass off whilst trying not to piss myself" },
    { "slang": "lmaoxh", "original": "laughing my ass off extremely hard" },
    { "slang": "lmap", "original": "leave me alone please" },
    { "slang": "lmb", "original": "lick my balls" },
    { "slang": "lmbao", "original": "laughing my black ass off" },
    { "slang": "lmbfwao", "original": "laughing my big fat white ass off" },
    { "slang": "lmbo", "original": "laughing my butt off" },
    { "slang": "lmcao", "original": "laughing my crazy ass off" },
    { "slang": "lmclao", "original": "laughing my cute little ass off" },
    { "slang": "lmd", "original": "Lick My Dick" },
    { "slang": "lmfao", "original": "laughing my fucking ass off" },
    { "slang": "lmfbo", "original": "laugh my fucking butt off" },
    { "slang": "lmffao", "original": "laughing my fucking fat ass off" },
    { "slang": "lmffo", "original": "Laughing my fucking face off" },
    { "slang": "lmfho", "original": "laughing my fucking head off" },
    { "slang": "lmfo", "original": "laughing my face off" },
    { "slang": "lmfpo", "original": "laughing my fucking pussy off" },
    { "slang": "lmfr", "original": "Lets Meet For Real" },
    { "slang": "lmfto", "original": "laughing my fuckin tits off" },
    { "slang": "lmg", "original": "let me guess" },
    { "slang": "lmgdao", "original": "Laughing My God Damn Ass Off" },
    { "slang": "lmgtfy", "original": "Let me Google that for you" },
    { "slang": "lmhao", "original": "laughing my hairy ass off" },
    { "slang": "lmho", "original": "laughing my heiny off" },
    { "slang": "lmip", "original": "LETS MEET IN PERSON" },
    { "slang": "lmirl", "original": "Let's meet in real life" },
    { "slang": "lmk", "original": "let me know" },
    { "slang": "lmks", "original": "Let Me Know Soon" },
    { "slang": "lmkwut", "original": "let me know what you think" },
    { "slang": "lml", "original": "love my life" },
    { "slang": "lmmfao", "original": "laughing my mother fucking ass off" },
    { "slang": "lmmfaos", "original": "laughing my mother fucking ass off silly" },
    { "slang": "lmmfas", "original": "laugh my mother fuckin ass off" },
    { "slang": "lmmffao", "original": "laughing my mother fucking fat ass off" },
    { "slang": "lmo", "original": "Leave Me One" },
    { "slang": "lmoao", "original": "Laughing my Other Ass Off" },
    { "slang": "lmp", "original": "lick my pussy" },
    { "slang": "lmpo", "original": "laughing my panties off" },
    { "slang": "lms", "original": "leave me some" },
    { "slang": "lmsao", "original": "laughing my sexy ass off" },
    { "slang": "lmso", "original": "laughing my socks off" },
    { "slang": "lmtd", "original": "limited" },
    { "slang": "lmtfa", "original": "leave me the fuck alone" },
    { "slang": "lmto", "original": "laughing my tits off" },
    { "slang": "lmtus", "original": "let me tell you something" },
    { "slang": "lmty", "original": "laughing more than you" },
    { "slang": "lmvo", "original": "laugh my vagina off" },
    { "slang": "ln", "original": "last name" },
    { "slang": "lnk", "original": "Link" },
    { "slang": "lobfl", "original": "Laugh Out Bloody Fucking Loud" },
    { "slang": "lobl", "original": "laugh out bloody loud" },
    { "slang": "lof", "original": "Laughing on floor" },
    { "slang": "lofi", "original": "uncool" },
    { "slang": "lofl", "original": "laugh out fucking loud" },
    { "slang": "loflmao", "original": "laying on floor laughing my ass off" },
    { "slang": "loi", "original": "laughing on the inside" },
    { "slang": "lol", "original": "laughing out loud" },
    { "slang": "lol'd", "original": "laughed out loud" },
    { "slang": "lol2u", "original": "Laugh out loud to you" },
    { "slang": "lol@u", "original": "Laugh out loud at you" },
    { "slang": "lolarotf", "original": "laughing out loud and rolling on the floor" },
    { "slang": "lolaw", "original": "laugh out loud at work" },
    { "slang": "lolbs", "original": "laugh out loud but seriously" },
    { "slang": "lolcano", "original": "laugh out loud" },
    { "slang": "lolci", "original": "laughing out loud, crying inside" },
    { "slang": "lolcity", "original": "the whole city laughs out loud" },
    { "slang": "lold", "original": "laughed out loud" },
    { "slang": "lolees", "original": "laugh out loud" },
    { "slang": "lolerz", "original": "laugh out loud" },
    { "slang": "lolf", "original": "lots of love forever" },
    { "slang": "lolin", "original": "laughing out loud" },
    { "slang": "lolio", "original": "laugh out loud I own" },
    { "slang": "lollam", "original": "Laughing Out Loud Like A Maniac" },
    { "slang": "lollercaust", "original": "an extreme event of hilarity" },
    { "slang": "lollercoaster", "original": "laugh out loud (a lot)" },
    { "slang": "lollerskates", "original": "laughing out loud" },
    { "slang": "lolm", "original": "laugh out loud man" },
    { "slang": "loln", "original": "laught out loud... not" },
    { "slang": "lolngs", "original": "laghing out loud never gonna stop" },
    { "slang": "lolocost", "original": "laugh out loud" },
    { "slang": "lolol", "original": "saying " },
    { "slang": "lololz", "original": "laugh out loud" },
    { "slang": "lolpimp", "original": "Laughing out loud peeing in my pants" },
    { "slang": "lolq", "original": "laugh out loud quietly" },
    { "slang": "lolrof", "original": "Laughing out loud while rolling on the floor." },
    { "slang": "lolrotf", "original": "laughing out loud rolling on the floor" },
    { "slang": "lols", "original": "laugh out loud " },
    { "slang": "lolvq", "original": "laugh out loud very quietly" },
    { "slang": "lolwtime", "original": "laughing out loud with tears in my eyes" },
    { "slang": "lolz", "original": "laugh out loud" },
    { "slang": "lomg", "original": "like oh my god" },
    { "slang": "loml", "original": "love of my life" },
    { "slang": "lomy", "original": "love of my life" },
    { "slang": "loomm", "original": "laughing out of my mind" },
    { "slang": "lorl", "original": "laugh out real loud" },
    { "slang": "lorrl", "original": "laugh out really really loud" },
    { "slang": "lotf", "original": "laughing on the floor" },
    { "slang": "loti", "original": "laughing on the inside" },
    { "slang": "loto", "original": "laughing on the outside" },
    { "slang": "lotr", "original": "lord of the rings" },
    { "slang": "lov", "original": "love" },
    { "slang": "lovu", "original": "love you" },
    { "slang": "loxen", "original": "laughing out loud" },
    { "slang": "loxxen", "original": "laughing out loud" },
    { "slang": "lozer", "original": "loser" },
    { "slang": "lpb", "original": "low ping bastard" },
    { "slang": "lpiaw", "original": "Large Penis is always welcome" },
    { "slang": "lpms", "original": "life pretty much sucks" },
    { "slang": "lq", "original": "Laughing Quietly" },
    { "slang": "lq2m", "original": "laughing quietly to myself" },
    { "slang": "lqtm", "original": "Laugh quietly to myself" },
    { "slang": "lqtms", "original": "Laughing quietly to myself" },
    { "slang": "lqts", "original": "laughing quietly to self" },
    { "slang": "lrfl", "original": "Laughing really fucking loud" },
    { "slang": "lrh", "original": "laughing really hard" },
    { "slang": "lrqtms", "original": "laughing really quietly to myself" },
    { "slang": "lrt", "original": "last retweet" },
    { "slang": "lsfw", "original": "Less Safe For Work" },
    { "slang": "lshic", "original": "laughing so hard i'm crying" },
    { "slang": "lshid", "original": "laugh so hard i die" },
    { "slang": "lshifabmh", "original": "Laughing so hard I fell and broke my hip" },
    { "slang": "lshipmp", "original": "Laughing so Hard I Piss My Pants" },
    { "slang": "lshismp", "original": "laughed so hard I shit my pants" },
    { "slang": "lshiwms", "original": "laughing so hard I wet myself" },
    { "slang": "lshmson", "original": "laughing so hard milk shot out nose" },
    { "slang": "lshrn", "original": "laughing so hard right now" },
    { "slang": "lsmih", "original": "laughing so much it hurts" },
    { "slang": "lsr", "original": "loser" },
    { "slang": "lsudi", "original": "Lets see you do it" },
    { "slang": "lt", "original": "long time" },
    { "slang": "ltb", "original": "looking to buy" },
    { "slang": "lthtt", "original": "laughing too hard to type" },
    { "slang": "ltip", "original": "laughting until I puke" },
    { "slang": "ltm", "original": "listen to me" },
    { "slang": "ltmq", "original": "Laugh To Myself Quietly" },
    { "slang": "ltms", "original": "Laughing to my self" },
    { "slang": "ltnc", "original": "Long time no see" },
    { "slang": "ltns", "original": "long time no see" },
    { "slang": "ltnsoh", "original": "Long time, no see or hear" },
    { "slang": "ltnt", "original": "long time no talk" },
    { "slang": "ltp", "original": "Lay the pipe" },
    { "slang": "ltr", "original": "later" },
    { "slang": "lttpot", "original": "laughing to the point of tears" },
    { "slang": "ltw", "original": "Lead The Way" },
    { "slang": "ltywl", "original": "love the way you lie" },
    { "slang": "lu2", "original": "love you too" },
    { "slang": "lu2d", "original": "love you to death" },
    { "slang": "lu4l", "original": "love you for life" },
    { "slang": "lub", "original": "laugh under breath" },
    { "slang": "luf", "original": "love" },
    { "slang": "luff", "original": "Love" },
    { "slang": "lug", "original": "lesbian until graduation" },
    { "slang": "luk", "original": "look" },
    { "slang": "lukin", "original": "looking" },
    { "slang": "lul", "original": "love you lots" },
    { "slang": "lulab", "original": "Love you like a brother" },
    { "slang": "lulas", "original": "Love You Like a Sister" },
    { "slang": "lulz", "original": "Laughing out loud." },
    { "slang": "lumumi", "original": "Love you miss you mean it" },
    { "slang": "lurker", "original": "one who reads but doesn't reply" },
    { "slang": "lurve", "original": "love" },
    { "slang": "luser", "original": "user who is a loser" },
    { "slang": "lusm", "original": "love you so much" },
    { "slang": "luv", "original": "love" },
    { "slang": "luver", "original": "lover" },
    { "slang": "luvuvm", "original": "love you very much" },
    { "slang": "luvv", "original": "love" },
    { "slang": "luzar", "original": "Loser" },
    { "slang": "lv", "original": "love" },
    { "slang": "lve", "original": "Love" },
    { "slang": "lvl", "original": "level" },
    { "slang": "lvn", "original": "loving" },
    { "slang": "lvr", "original": "lover" },
    { "slang": "lvya", "original": "love you" },
    { "slang": "lwih", "original": "look what I have" },
    { "slang": "lwn", "original": "last week's news" },
    { "slang": "ly", "original": "love you" },
    { "slang": "ly2", "original": "love you to" },
    { "slang": "lya", "original": "love you always" },
    { "slang": "lyaab", "original": "Love you as a brother" },
    { "slang": "lyaaf", "original": "Love you as a friend" },
    { "slang": "lyao", "original": "laugh your ass off" },
    { "slang": "lybo", "original": "laugh your butt off" },
    { "slang": "lyf", "original": "life" },
    { "slang": "lyfao", "original": "laughing your fucking ass off" },
    { "slang": "lyfe", "original": "life" },
    { "slang": "lyk", "original": "like" },
    { "slang": "lyk3", "original": "like" },
    { "slang": "lyke", "original": "like" },
    { "slang": "lyl", "original": "love you lots" },
    { "slang": "lylab", "original": "love you like a brother" },
    { "slang": "lylaba", "original": "love you like a brother always" },
    { "slang": "lylad", "original": "love you like a dad" },
    { "slang": "lylafklc", "original": "love you like a fat kid loves cake" },
    { "slang": "lylam", "original": "love you like a mom" },
    { "slang": "lylas", "original": "I love you like a sister" },
    { "slang": "lylasa", "original": "love you like a sister always" },
    { "slang": "lylno", "original": "Love you like no other" },
    { "slang": "lyls", "original": "love you lots" },
    { "slang": "lymi", "original": "love you mean it" },
    { "slang": "lysfm", "original": "love you so fucking much" },
    { "slang": "lysm", "original": "love you so much" },
    { "slang": "lyt", "original": "love you too" },
    { "slang": "lyvm", "original": "love you very much" },
    { "slang": "lzer", "original": "laser" },
    { "slang": "lzr", "original": "loser" },
    { "slang": "m", "original": "am" },
    { "slang": "m$", "original": "Microsoft" },
    { "slang": "m$wxp", "original": "Microsoft Windows XP" },
    { "slang": "m&d", "original": "mom and dad" },
    { "slang": "m'kay", "original": "okay" },
    { "slang": "m.i.a", "original": "Missing In Action" },
    { "slang": "m.o", "original": "makeout" },
    { "slang": "m/b", "original": "maybe" },
    { "slang": "m/f", "original": "male or female" },
    { "slang": "m2", "original": "me too" },
    { "slang": "m3", "original": "me" },
    { "slang": "m473s", "original": "friends" },
    { "slang": "m473z", "original": "friends" },
    { "slang": "m4f", "original": "male for female" },
    { "slang": "m4m", "original": "male for male" },
    { "slang": "m8", "original": "friend" },
    { "slang": "m84l", "original": "mate for life" },
    { "slang": "m8s", "original": "mates" },
    { "slang": "m8t", "original": "mate" },
    { "slang": "m8t's", "original": "friends" },
    { "slang": "m9", "original": "mine" },
    { "slang": "mabby", "original": "maybe" },
    { "slang": "mabe", "original": "Maybe" },
    { "slang": "maga", "original": "make America great again" },
    { "slang": "mah", "original": "my" },
    { "slang": "mai", "original": "my" },
    { "slang": "mao", "original": "my ass off" },
    { "slang": "marvy", "original": "marvelous" },
    { "slang": "masterb8", "original": "masterbate" },
    { "slang": "mastrb8", "original": "masturbate." },
    { "slang": "mayb", "original": "maybe" },
    { "slang": "mayte", "original": "mate" },
    { "slang": "mb", "original": "my bad" },
    { "slang": "mbf", "original": "my best friend" },
    { "slang": "mbfal", "original": "my best friend and lover" },
    { "slang": "mbhsm", "original": "My Boobs Hurt So Much" },
    { "slang": "mbl8r", "original": "Maybe Later" },
    { "slang": "mcds", "original": "mcdonalds" },
    { "slang": "mcs", "original": "My computer sucks" },
    { "slang": "mcse", "original": "Microsoft Certified Systems Engineer" },
    { "slang": "mdf", "original": "my dear friend" },
    { "slang": "mdk", "original": "murder death kill" },
    { "slang": "me2", "original": "me too" },
    { "slang": "meatcurtain", "original": "woman's private parts" },
    { "slang": "meatspace", "original": "the real world" },
    { "slang": "meeh", "original": "me" },
    { "slang": "mego", "original": "my eyes glaze over" },
    { "slang": "meh", "original": "whatever" },
    { "slang": "messg", "original": "message" },
    { "slang": "mf", "original": "motherfucker" },
    { "slang": "mf2f4sx", "original": "meet face to face for sex" },
    { "slang": "mfa", "original": "mother fucking asshole" },
    { "slang": "mfah", "original": "motherfucking asshole" },
    { "slang": "mfao", "original": "my fucking ass off" },
    { "slang": "mfb", "original": "mother fucking bitch" },
    { "slang": "mfer", "original": "motherfucker" },
    { "slang": "mfg", "original": "merge from current" },
    { "slang": "mfkr", "original": "motherfucker" },
    { "slang": "mflfs", "original": "married female looking for sex" },
    { "slang": "mfr", "original": "motherfucker" },
    { "slang": "mfw", "original": "my face when" },
    { "slang": "mgiwjsdchmw", "original": "my girlfriend is watching jeff so don't call her my wife" },
    { "slang": "mgmt", "original": "management " },
    { "slang": "mhh", "original": "my head hurts" },
    { "slang": "mhm", "original": "Yes" },
    { "slang": "mho", "original": "My Humble Opinion" },
    { "slang": "mia", "original": "Missing In Action" },
    { "slang": "mic", "original": "microphone" },
    { "slang": "miid", "original": "my internet is down" },
    { "slang": "milf", "original": "Mom i'd like to fuck" },
    { "slang": "miltf", "original": "Mom I'd like to fuck" },
    { "slang": "min", "original": "minute" },
    { "slang": "mins", "original": "minutes" },
    { "slang": "miq", "original": "make it quick" },
    { "slang": "mir", "original": "mom in room" },
    { "slang": "mirl", "original": "meet in real life" },
    { "slang": "misc.", "original": "miscellaneous" },
    { "slang": "miself", "original": "myself" },
    { "slang": "mite", "original": "might" },
    { "slang": "miw", "original": "mom is watching" },
    { "slang": "miwnlf", "original": "mom I would not like to fuck." },
    { "slang": "mk", "original": "mmm....ok" },
    { "slang": "mkay", "original": "ok" },
    { "slang": "mlc", "original": "mid life crisis" },
    { "slang": "mle", "original": "emily" },
    { "slang": "mlia", "original": "my life is amazing" },
    { "slang": "mlod", "original": "mega laugh out loud of doom" },
    { "slang": "mlp", "original": "my little pony" },
    { "slang": "mmamp", "original": "Meet me at my place" },
    { "slang": "mmas", "original": "meet me after school" },
    { "slang": "mmatc", "original": "meet me around the corner" },
    { "slang": "mmatp", "original": "meet me at the park" },
    { "slang": "mmbocmb", "original": "message me back or comment me back" },
    { "slang": "mmd", "original": "make my day" },
    { "slang": "mmiw", "original": "my mom is watching" },
    { "slang": "mmk", "original": "umm, ok" },
    { "slang": "mml", "original": "making me laugh" },
    { "slang": "mml8r", "original": "meet me later" },
    { "slang": "mmlfs", "original": "married man looking for sex" },
    { "slang": "mmmkay", "original": "okay" },
    { "slang": "mmo", "original": "Massive Multiplayer Online" },
    { "slang": "mmorpg", "original": "massively multiplayer online role playing game" },
    { "slang": "mmt", "original": "meet me there" },
    { "slang": "mmtyh", "original": "My mom thinks you're hot" },
    { "slang": "mmw", "original": "making me wet" },
    { "slang": "mngmt", "original": "management" },
    { "slang": "mngr", "original": "manager" },
    { "slang": "mnm", "original": "eminem" },
    { "slang": "mnt", "original": "More next time" },
    { "slang": "mobo", "original": "motherboard" },
    { "slang": "mof", "original": "matter of fact" },
    { "slang": "mofo", "original": "mother fucker" },
    { "slang": "moh", "original": "Medal Of Honor" },
    { "slang": "mohaa", "original": "Medal of Honor Allied Assult" },
    { "slang": "mol", "original": "more or less" },
    { "slang": "mompl", "original": "moment please" },
    { "slang": "moobs", "original": "man boobs" },
    { "slang": "mor", "original": "more" },
    { "slang": "morf", "original": "male or female" },
    { "slang": "moro", "original": "tomorrow" },
    { "slang": "mos", "original": "mom over shoulder" },
    { "slang": "moss", "original": "member of same sex" },
    { "slang": "motarded", "original": "more retarded" },
    { "slang": "motd", "original": "message of the day" },
    { "slang": "motos", "original": "member of the opposite sex" },
    { "slang": "mpaw", "original": "my parents are watching" },
    { "slang": "mpbis", "original": "most popular boy in school" },
    { "slang": "mpd", "original": "Multiple Personality Disorder" },
    { "slang": "mpgis", "original": "most popular girl in school" },
    { "slang": "mph", "original": "miles per hour" },
    { "slang": "mpih", "original": "my penis is hard" },
    { "slang": "mpty", "original": "more power to you" },
    { "slang": "mrau", "original": "message received and understood" },
    { "slang": "msf", "original": "male seeking female" },
    { "slang": "msg", "original": "message" },
    { "slang": "msgs", "original": "messages" },
    { "slang": "msh", "original": "Me so horny" },
    { "slang": "msibo", "original": "my side is busting open" },
    { "slang": "msie", "original": "microsoft's internet explorer" },
    { "slang": "msm", "original": "main stream media" },
    { "slang": "msmd", "original": "monkey see - monkey do" },
    { "slang": "msngr", "original": "messenger" },
    { "slang": "mssg", "original": "message" },
    { "slang": "mstrb8r", "original": "masturbator" },
    { "slang": "msv", "original": "Microsoft Vista" },
    { "slang": "mtc", "original": "more to come" },
    { "slang": "mtf", "original": "More to Follow" },
    { "slang": "mtfbwu", "original": "may the force be with you" },
    { "slang": "mtfbwy", "original": "May the Force be with you" },
    { "slang": "mtg", "original": "Meeting" },
    { "slang": "mtherfker", "original": "mother fucker" },
    { "slang": "mthrfkr", "original": "mother fucker" },
    { "slang": "mtl", "original": "more than likely" },
    { "slang": "mtr", "original": "matter" },
    { "slang": "mtrfkr", "original": "motherfucker" },
    { "slang": "mty", "original": "empty" },
    { "slang": "mu", "original": "miss you" },
    { "slang": "mudda", "original": "mother" },
    { "slang": "mul", "original": "miss you lots" },
    { "slang": "musiq", "original": "music" },
    { "slang": "musm", "original": "Miss You So Much" },
    { "slang": "mutha", "original": "mother" },
    { "slang": "muve", "original": "multi-user virtual environment" },
    { "slang": "muvva", "original": "mother" },
    { "slang": "muzik", "original": "music" },
    { "slang": "mw2", "original": "modern warfare 2" },
    { "slang": "mw3", "original": "Modern Warfare 3" },
    { "slang": "mwah", "original": "kiss" },
    { "slang": "mwf", "original": "Married White Female" },
    { "slang": "mwsmirl", "original": "maybe we should meet in real life" },
    { "slang": "myaly", "original": "miss you and love you" },
    { "slang": "myfb", "original": "mind your fucking business" },
    { "slang": "myke", "original": "man-dyke" },
    { "slang": "myn", "original": "mine" },
    { "slang": "myob", "original": "mind your own business" },
    { "slang": "myodb", "original": "mind your own damn business" },
    { "slang": "myofb", "original": "mind your own fucking business" },
    { "slang": "mypl", "original": "my young padawan learner" },
    { "slang": "mysm", "original": "Miss you so much" },
    { "slang": "myspce", "original": "myspace" },
    { "slang": "n", "original": "and" },
    { "slang": "n e", "original": "any" },
    { "slang": "n/a", "original": "not applicable" },
    { "slang": "n/a/s/l", "original": "name, age, sex location" },
    { "slang": "n/c", "original": "no comment" },
    { "slang": "n/m", "original": "nevermind" },
    { "slang": "n/n", "original": "nickname" },
    { "slang": "n/o", "original": "no offense" },
    { "slang": "n/t", "original": "no text" },
    { "slang": "n00b", "original": "newbie" },
    { "slang": "n00bs", "original": "newbies" },
    { "slang": "n00dz", "original": "nudes" },
    { "slang": "n00s", "original": "news" },
    { "slang": "n1", "original": "nice one" },
    { "slang": "n199312", "original": "african american" },
    { "slang": "n1994", "original": "african american" },
    { "slang": "n2", "original": "into" },
    { "slang": "n2b", "original": "not too bad" },
    { "slang": "n2bb", "original": "nice to be back" },
    { "slang": "n2br", "original": "not to be rude" },
    { "slang": "n2g", "original": "Not too good" },
    { "slang": "n2m", "original": "not too much" },
    { "slang": "n2mh", "original": "not too much here" },
    { "slang": "n2mhbu", "original": "not too much how about you?" },
    { "slang": "n2mhjc", "original": "not too much here just chillin" },
    { "slang": "n2mu", "original": "not too much, you?" },
    { "slang": "n2n", "original": "need to know" },
    { "slang": "n2p", "original": "need to pee" },
    { "slang": "n64", "original": "Nintendo 64" },
    { "slang": "n8v", "original": "native" },
    { "slang": "na", "original": "not applicable" },
    { "slang": "na4w", "original": "not appropriate for work" },
    { "slang": "naa", "original": "not at all" },
    { "slang": "nade", "original": "grenade" },
    { "slang": "nafc", "original": "Not Appropriate for Children" },
    { "slang": "nafkam", "original": "Not Away From Keyboard Any More" },
    { "slang": "naft", "original": "Not A Fucking Thing" },
    { "slang": "nafta", "original": "North American Free Trade Agreement" },
    { "slang": "nah", "original": "no" },
    { "slang": "namh", "original": "not at my house" },
    { "slang": "nao", "original": "Not As Often" },
    { "slang": "natch", "original": "naturally" },
    { "slang": "natm", "original": "not at the minute" },
    { "slang": "naw", "original": "no" },
    { "slang": "naw-t", "original": "Naughty" },
    { "slang": "nawidt", "original": "never again will i do that" },
    { "slang": "nawt", "original": "not" },
    { "slang": "naww", "original": "no" },
    { "slang": "nayl", "original": "in a while" },
    { "slang": "nb", "original": "not bad" },
    { "slang": "nb,p", "original": "nothing bad, parents" },
    { "slang": "nba", "original": "national basketball association " },
    { "slang": "nbd", "original": "no big deal" },
    { "slang": "nbdy", "original": "nobody" },
    { "slang": "nbf", "original": "never been fucked" },
    { "slang": "nc", "original": "not cool" },
    { "slang": "ncaa", "original": "National Collegiate Athletic Association" },
    { "slang": "ncs", "original": "no crap sherlock" },
    { "slang": "nd", "original": "and" },
    { "slang": "ndit", "original": "No details in thread" },
    { "slang": "ndn", "original": "indian" },
    { "slang": "nds", "original": "Nintendo DS" },
    { "slang": "ne", "original": "any" },
    { "slang": "ne1", "original": "anyone" },
    { "slang": "neday", "original": "any day" },
    { "slang": "nedn", "original": "any day now" },
    { "slang": "nefing", "original": "anything" },
    { "slang": "negl", "original": "not even going to lie" },
    { "slang": "nei", "original": "Not enough information" },
    { "slang": "neida", "original": "any idea" },
    { "slang": "nekkid", "original": "naked" },
    { "slang": "nemore", "original": "Anymore" },
    { "slang": "nes", "original": "Nintendo Entertainment System" },
    { "slang": "nethin", "original": "anything" },
    { "slang": "nething", "original": "anything" },
    { "slang": "neva", "original": "never" },
    { "slang": "nevah", "original": "never" },
    { "slang": "nevar", "original": "Never" },
    { "slang": "nevarz", "original": "never" },
    { "slang": "nevm", "original": "never mind" },
    { "slang": "nevr", "original": "never" },
    { "slang": "newais", "original": "Anyways" },
    { "slang": "neway", "original": "anyway" },
    { "slang": "neways", "original": "anyways" },
    { "slang": "newayz", "original": "anyways" },
    { "slang": "newb", "original": "someone who is new" },
    { "slang": "newbie", "original": "new player" },
    { "slang": "newez", "original": "anyways" },
    { "slang": "nf", "original": "not funny" },
    { "slang": "nfbsk", "original": "not for british school kids" },
    { "slang": "nfc", "original": "no fucking clue" },
    { "slang": "nfd", "original": "no fucking deal" },
    { "slang": "nff", "original": "not fucking fair" },
    { "slang": "nfi", "original": "no fucking idea" },
    { "slang": "nfr", "original": "not for real" },
    { "slang": "nfs", "original": "not for sale" },
    { "slang": "nft", "original": "no further text" },
    { "slang": "nfw", "original": "no fucking way" },
    { "slang": "ng", "original": "nice game" },
    { "slang": "ngaf", "original": "nobody gives a fuck" },
    { "slang": "ngl", "original": "Not Gonna Lie" },
    { "slang": "nh", "original": "nice hand" },
    { "slang": "nhatm", "original": "not here at the moment" },
    { "slang": "ni", "original": "no idea" },
    { "slang": "ni994", "original": "nigga" },
    { "slang": "nib", "original": "new in box" },
    { "slang": "nic", "original": "Network Interface Card" },
    { "slang": "nif", "original": "non internet friend" },
    { "slang": "nifoc", "original": "naked in front of computer" },
    { "slang": "nifok", "original": "naked in front of keyboard" },
    { "slang": "nigysob", "original": "now I've got you son of a bitch" },
    { "slang": "nimby", "original": "not in my backyard" },
    { "slang": "nin", "original": "no its not" },
    { "slang": "nip", "original": "nothing in particular" },
    { "slang": "nips", "original": "nipples" },
    { "slang": "nite", "original": "night" },
    { "slang": "niwdi", "original": "no I won\\'t do it" },
    { "slang": "nizzle", "original": "nigger" },
    { "slang": "nj", "original": "Nice job" },
    { "slang": "njoy", "original": "enjoy" },
    { "slang": "njp", "original": "nice job partner" },
    { "slang": "nk", "original": "no kidding" },
    { "slang": "nkt", "original": "never knew that" },
    { "slang": "nld", "original": "nice lay down" },
    { "slang": "nm", "original": "not much" },
    { "slang": "nm u", "original": "not much, you" },
    { "slang": "nmbr", "original": "number" },
    { "slang": "nme", "original": "enemy" },
    { "slang": "nmf", "original": "not my fault" },
    { "slang": "nmfp", "original": "not my fucking problem" },
    { "slang": "nmh", "original": "not much here" },
    { "slang": "nmhau", "original": "nothing much how about you" },
    { "slang": "nmhm", "original": "nothing much here, man" },
    { "slang": "nmhu", "original": "nothing much here, you?" },
    { "slang": "nmhwby", "original": "nothing much here what about you" },
    { "slang": "nmjb", "original": "nothing much just bored" },
    { "slang": "nmjc", "original": "not much, just chillin'" },
    { "slang": "nmjch", "original": "Nothing Much Just Chilling" },
    { "slang": "nmjcu", "original": "nothing much, just chilling, you?" },
    { "slang": "nmjdhw", "original": "nothing much just doing homework" },
    { "slang": "nmjfa", "original": "nothing much, just fucking around" },
    { "slang": "nmnhnlm", "original": "no money, no honey, nobody loves me" },
    { "slang": "nmp", "original": "Not My Problem" },
    { "slang": "nmu", "original": "nothing much, you" },
    { "slang": "nmw", "original": "no matter what" },
    { "slang": "nmwh", "original": "no matter what happens" },
    { "slang": "nn", "original": "good night" },
    { "slang": "nn2r", "original": "no need to respond" },
    { "slang": "nnaa", "original": "no not at all" },
    { "slang": "nnfaa", "original": "no need for an apology" },
    { "slang": "nnr", "original": "no not really" },
    { "slang": "nntr", "original": "no need to reply" },
    { "slang": "nntst", "original": "no need to say thanks" },
    { "slang": "no pro", "original": "no problem" },
    { "slang": "no1", "original": "no one" },
    { "slang": "noaa", "original": "National Oceanic and Atmospheric Administration" },
    { "slang": "noc", "original": "naked on camera" },
    { "slang": "noe", "original": "know" },
    { "slang": "noes", "original": "no" },
    { "slang": "nofi", "original": "No Flame Intended" },
    { "slang": "nolm", "original": "No one loves me" },
    { "slang": "nomw", "original": "not on my watch" },
    { "slang": "noob", "original": "someone who is new" },
    { "slang": "noobie", "original": "new person" },
    { "slang": "nooblet", "original": "new player" },
    { "slang": "noobz0r", "original": "newbie" },
    { "slang": "noodz", "original": "nude pictures" },
    { "slang": "nookie", "original": "sex" },
    { "slang": "nop", "original": "normal operating procedure" },
    { "slang": "NORWICH", "original": "knickers off ready when I come home" },
    { "slang": "notin", "original": "nothing" },
    { "slang": "noty", "original": "no thank you" },
    { "slang": "noub", "original": "none of your business" },
    { "slang": "nowai", "original": "No way" },
    { "slang": "nowin", "original": "knowing" },
    { "slang": "noyb", "original": "none of your business" },
    { "slang": "noygdb", "original": "none of your god damn business" },
    { "slang": "np", "original": "no problem" },
    { "slang": "np4np", "original": "naked pic for naked pic" },
    { "slang": "npa", "original": "not paying attention" },
    { "slang": "npc", "original": "Non-playable character" },
    { "slang": "npe", "original": "nope" },
    { "slang": "npgf", "original": "no problem girl friend" },
    { "slang": "nph", "original": "no problem here" },
    { "slang": "npi", "original": "no pun intended" },
    { "slang": "npnt", "original": "no picture, no talk" },
    { "slang": "nps", "original": "No Problems" },
    { "slang": "nq", "original": "Thank you" },
    { "slang": "nr", "original": " no reserve" },
    { "slang": "nr4u", "original": "not right for you" },
    { "slang": "nrg", "original": "energy" },
    { "slang": "nrn", "original": "No Response Necessary" },
    { "slang": "ns", "original": "nice" },
    { "slang": "nsa", "original": "No Strings Attached" },
    { "slang": "nsas", "original": "No Strings Attached Sex" },
    { "slang": "nsfmf", "original": "not so fast my friend" },
    { "slang": "nsfu", "original": "no sex for you" },
    { "slang": "nsfw", "original": "not safe for work" },
    { "slang": "nss", "original": "no shit sherlock" },
    { "slang": "nst", "original": "no school today" },
    { "slang": "nstaafl", "original": "No Such Thing As a Free Lunch" },
    { "slang": "nt", "original": "nice try" },
    { "slang": "ntb", "original": "not to bad" },
    { "slang": "ntbn", "original": "no text-back needed" },
    { "slang": "nthg", "original": "nothing" },
    { "slang": "nthin", "original": "nothing" },
    { "slang": "nthn", "original": "nothing" },
    { "slang": "ntigaf", "original": "not that i give a fuck" },
    { "slang": "ntk", "original": "Need to know" },
    { "slang": "ntkb", "original": "need to know basis" },
    { "slang": "ntm", "original": "not to much" },
    { "slang": "ntmk", "original": "Not to my knowledge" },
    { "slang": "ntmu", "original": "nice to meet you" },
    { "slang": "ntmy", "original": "nice to meet you" },
    { "slang": "ntn", "original": "nothing" },
    { "slang": "ntrly", "original": "Not Really" },
    { "slang": "nts", "original": "note to self" },
    { "slang": "ntstt", "original": "not safe to talk " },
    { "slang": "ntt", "original": "need to talk" },
    { "slang": "ntta", "original": "nothing to talk about " },
    { "slang": "nttawwt", "original": "Not that there is anything wrong with that" },
    { "slang": "nttiawwt", "original": "Not that there is anything wrong with that." },
    { "slang": "ntty", "original": "nice talking to you" },
    { "slang": "ntw", "original": "not to worry" },
    { "slang": "ntxt", "original": "no text" },
    { "slang": "nty", "original": "no thank you" },
    { "slang": "nu", "original": "new" },
    { "slang": "nub", "original": "inexperienced person" },
    { "slang": "nuff", "original": "enough" },
    { "slang": "nuffin", "original": "nothing" },
    { "slang": "nufin", "original": "nothing" },
    { "slang": "nutin", "original": "nothing" },
    { "slang": "nuttin", "original": "nothing" },
    { "slang": "nv", "original": "envy" },
    { "slang": "nvm", "original": "never mind" },
    { "slang": "nvmd", "original": "nevermind" },
    { "slang": "nvmdt", "original": "never mind then" },
    { "slang": "nvmt", "original": "nevermind that" },
    { "slang": "nvr", "original": "never" },
    { "slang": "nvrm", "original": "Nevermind" },
    { "slang": "nvrmnd", "original": "never mind " },
    { "slang": "nw", "original": "no way" },
    { "slang": "nwb", "original": "a new person" },
    { "slang": "nwih", "original": "no way in hell" },
    { "slang": "nwj", "original": "No Way Jose" },
    { "slang": "nwrus", "original": "no way are your serious " },
    { "slang": "nws", "original": "not work safe" },
    { "slang": "nwtf", "original": "now what the fuck" },
    { "slang": "nwy", "original": "no way" },
    { "slang": "nxt", "original": "next" },
    { "slang": "ny1", "original": "Anyone" },
    { "slang": "nyc", "original": "New York City" },
    { "slang": "nyf", "original": "not your fault" },
    { "slang": "nyp", "original": "not your problem" },
    { "slang": "nywy", "original": "anyway" },
    { "slang": "o", "original": "Oh" },
    { "slang": "o rly", "original": "oh really" },
    { "slang": "o&o", "original": "over and out" },
    { "slang": "o.p.", "original": "Original Poster" },
    { "slang": "o/y", "original": "oh yeah" },
    { "slang": "oaoa", "original": "over and over again" },
    { "slang": "oar", "original": "on a roll" },
    { "slang": "oaw", "original": "on a website" },
    { "slang": "obgjfioyo", "original": "old but good job finding it on your own" },
    { "slang": "obj", "original": "Object" },
    { "slang": "obl", "original": "osama bin laden" },
    { "slang": "obo", "original": "or best offer" },
    { "slang": "obtw", "original": "oh, by the way" },
    { "slang": "obv", "original": "obviously" },
    { "slang": "obvi", "original": "obviously" },
    { "slang": "occ", "original": "Occupation" },
    { "slang": "ocd", "original": "obsessive compulsive disorder" },
    { "slang": "ocgg", "original": "Oh Crap, gotta go" },
    { "slang": "od", "original": "over dose" },
    { "slang": "oday", "original": "software illegally obtained before it was released" },
    { "slang": "odg", "original": "oh dear God" },
    { "slang": "odtaa", "original": "one damn thing after another" },
    { "slang": "oe", "original": "or else" },
    { "slang": "oed", "original": "oxford english dictionary" },
    { "slang": "of10", "original": "often" },
    { "slang": "ofc", "original": "of course" },
    { "slang": "ofcol", "original": "oh for crying out loud" },
    { "slang": "ofn", "original": "Old Fucking News" },
    { "slang": "oftc", "original": "out for the count" },
    { "slang": "oftn", "original": "often" },
    { "slang": "oftpc", "original": "off topic" },
    { "slang": "ofwg", "original": "old fat white guys" },
    { "slang": "og", "original": "original gangster" },
    { "slang": "ogw", "original": "oh guess what" },
    { "slang": "oh noes", "original": "oh shit!" },
    { "slang": "oh noez", "original": "Oh no!" },
    { "slang": "ohic", "original": "oh I see" },
    { "slang": "ohn", "original": "oh hell no" },
    { "slang": "ohnoez", "original": "Oh no" },
    { "slang": "ohy", "original": "oh hell yeah" },
    { "slang": "oibmpc", "original": "oops I broke my computer" },
    { "slang": "oic", "original": "oh, I see" },
    { "slang": "oicic", "original": "oh i see i see" },
    { "slang": "oicu", "original": "oh, i see you!" },
    { "slang": "oicwydt", "original": "oh, i see what you did there" },
    { "slang": "oidia", "original": "oops i did it again" },
    { "slang": "oink", "original": "Oh I Never Knew" },
    { "slang": "oiyd", "original": "Only In Your Dreams" },
    { "slang": "oj", "original": "orange juice" },
    { "slang": "ojsu", "original": "Oh, just shut up!" },
    { "slang": "ok", "original": "okay" },
    { "slang": "oll", "original": "online love" },
    { "slang": "olpc", "original": "One Laptop Per Child" },
    { "slang": "omdg", "original": "oh my dear god" },
    { "slang": "omdz", "original": "Oh My Days " },
    { "slang": "omfd", "original": "oh my fucking days" },
    { "slang": "omfg", "original": "oh my fucking god" },
    { "slang": "omfgn", "original": "Oh my fucking god noob" },
    { "slang": "omfgsh", "original": "Oh My Fucking Gosh" },
    { "slang": "omfj", "original": "oh my fucking jesus" },
    { "slang": "omfl", "original": "oh my fucking internet connection is slow" },
    { "slang": "omfsm", "original": "Oh My Flying Spaghetti Monster" },
    { "slang": "omfwtg", "original": "Oh My Fuck What The God?" },
    { "slang": "omg", "original": "oh my God" },
    { "slang": "omg's", "original": "oh my god's" },
    { "slang": "omgd", "original": "Oh my gosh dude" },
    { "slang": "omgf", "original": "oh my god...Fuck!" },
    { "slang": "omgg", "original": "Oh my gosh girl" },
    { "slang": "omgicfbi", "original": "Oh my god I can't fucking believe it" },
    { "slang": "omgih", "original": "Oh My God In Heaven" },
    { "slang": "omgihv2p", "original": "oh my god i have to pee" },
    { "slang": "omginbd", "original": "Oh my God, It's no big deal" },
    { "slang": "omgn", "original": "oh my goodness" },
    { "slang": "omgny", "original": "oh my god no way" },
    { "slang": "omgosh", "original": "Oh my gosh" },
    { "slang": "omgroflmao", "original": "oh my god roll on the floor laughing my ass off" },
    { "slang": "omgsh", "original": "oh my gosh" },
    { "slang": "omgty", "original": "Oh my god thank you" },
    { "slang": "omgukk", "original": "oh my god you killed kenny" },
    { "slang": "omgwtf", "original": "on my God, what the fuck" },
    { "slang": "OMGWTFBBQ", "original": "oh my God, what the fuck" },
    { "slang": "omgwtfhax", "original": "Oh My God What The Fuck, Hacks!" },
    { "slang": "omgwtfit", "original": "Oh my God, what the fuck is that" },
    { "slang": "OMGWTFNIPPLES", "original": "on my God, what the fuck" },
    { "slang": "omgyg2bk", "original": "oh my god you got to be kidding" },
    { "slang": "omgykkyb", "original": "oh my god you killed kenny you bastards" },
    { "slang": "omgz", "original": "oh my God" },
    { "slang": "omgzors", "original": "oh my god" },
    { "slang": "omhg", "original": "oh my hell god" },
    { "slang": "omj", "original": "oh my jesus" },
    { "slang": "ommfg", "original": "oh my mother fucking god" },
    { "slang": "omt", "original": "one more time" },
    { "slang": "omw", "original": "on my way" },
    { "slang": "omwh", "original": "on my way home" },
    { "slang": "omwts", "original": "on my way to school" },
    { "slang": "omy", "original": "oh my!" },
    { "slang": "onoez", "original": "oh no" },
    { "slang": "onoz", "original": "oh no" },
    { "slang": "onud", "original": "oh no you didn't" },
    { "slang": "onyd", "original": "oh no you didn't" },
    { "slang": "oob", "original": "out of buisness" },
    { "slang": "oobl", "original": "out of breath laughing" },
    { "slang": "ooc", "original": "out of character" },
    { "slang": "oohm", "original": "out of his/her mind" },
    { "slang": "oom", "original": "Out of mana" },
    { "slang": "oomf", "original": "One of my followers" },
    { "slang": "oomm", "original": "out of my mind" },
    { "slang": "ooo", "original": "out of the office" },
    { "slang": "ootb", "original": "out of the blue" },
    { "slang": "ootd", "original": "outfit of the day" },
    { "slang": "oow", "original": "On our way" },
    { "slang": "ooym", "original": "out of your mind" },
    { "slang": "op", "original": "operator" },
    { "slang": "orgy", "original": "orgasm" },
    { "slang": "orlsx", "original": "oral sex" },
    { "slang": "orly", "original": "Oh Really" },
    { "slang": "orly", "original": "oh really?" },
    { "slang": "orpg", "original": "online role playing game" },
    { "slang": "os", "original": "operating system" },
    { "slang": "osbutctt", "original": "only sad bastards use this crappy text talk" },
    { "slang": "osd", "original": "On Screen Display" },
    { "slang": "osifgt", "original": "oh shit i forgot" },
    { "slang": "oslt", "original": "or something like that" },
    { "slang": "osy", "original": "oh screw you" },
    { "slang": "ot", "original": "off topic" },
    { "slang": "otc", "original": "off the chain" },
    { "slang": "otfcu", "original": "on the floor cracking up" },
    { "slang": "otfl", "original": "on the floor laughing" },
    { "slang": "otflmao", "original": "On the floor laughing my ass off" },
    { "slang": "otflmfao", "original": "On the floor laughing my fucking ass off" },
    { "slang": "otflol", "original": "on the floor laughing out loud" },
    { "slang": "otfp", "original": "on the fucking phone" },
    { "slang": "otft", "original": "over the fucking top" },
    { "slang": "oti", "original": "on the internet" },
    { "slang": "otl", "original": "out to lunch" },
    { "slang": "otoh", "original": "on the other hand" },
    { "slang": "otp", "original": "on the phone" },
    { "slang": "ots", "original": "over the shoulder" },
    { "slang": "ott", "original": "over the top" },
    { "slang": "otw", "original": "on the way" },
    { "slang": "outa", "original": "out of" },
    { "slang": "ova", "original": "over" },
    { "slang": "oways", "original": "oh wow are you serious" },
    { "slang": "owned", "original": "made to look bad" },
    { "slang": "ownt", "original": "made to look bad" },
    { "slang": "ownz", "original": "owns" },
    { "slang": "ownzer", "original": "one who makes others look bad" },
    { "slang": "ownzorz", "original": "Owned." },
    { "slang": "owt", "original": "Out" },
    { "slang": "oww", "original": "Oops, wrong window" },
    { "slang": "oyfe", "original": "Open Your Fucking Eyes" },
    { "slang": "oyid", "original": "oh yes i did" },
    { "slang": "oyo", "original": "on your own" },
    { "slang": "oyr", "original": "Oh Yeah Right" }
  ]
}
