module.exports = {
  range: ['p', 'q', 'r', 's', 't'],
  words: [
    { "slang": "p-nis", "original": "penis" },
    { "slang": "p.o.b.", "original": "Parent Over Back" },
    { "slang": "p.o.s", "original": "parent over shoulder" },
    { "slang": "p.o.s.", "original": "parent over shoulder" },
    { "slang": "p/oed", "original": "pissed off" },
    { "slang": "p/w", "original": "password" },
    { "slang": "p00p", "original": "poop" },
    { "slang": "p0wn", "original": "make to look bad" },
    { "slang": "p2p", "original": "peer to peer" },
    { "slang": "p2w", "original": "pay to win" },
    { "slang": "p33n", "original": "penis" },
    { "slang": "p3n0r", "original": "penis" },
    { "slang": "p3n15", "original": "penis" },
    { "slang": "p3n1s", "original": "penis" },
    { "slang": "p4p", "original": "pic for pic" },
    { "slang": "p911", "original": "parent emergency (parent near)" },
    { "slang": "p@w", "original": "parents are watching" },
    { "slang": "pach", "original": "parents are coming home" },
    { "slang": "pachs", "original": "parents are coming home soon" },
    { "slang": "pae", "original": "Pimpin aint easy" },
    { "slang": "pag", "original": "Parents Are Gone" },
    { "slang": "pah", "original": "parents at home" },
    { "slang": "parnts", "original": "parents" },
    { "slang": "pas", "original": "parent at side" },
    { "slang": "pasii", "original": "put a sock in it" },
    { "slang": "patd", "original": "Panic At The Disco" },
    { "slang": "paw", "original": "parents are watching" },
    { "slang": "pb", "original": "peanut butter" },
    { "slang": "pb&j", "original": "peanut butter and jelly" },
    { "slang": "pbb", "original": "parent behind back" },
    { "slang": "pbcakb", "original": "problem between chair and keyboard" },
    { "slang": "pbj", "original": "peanut butter and jelly" },
    { "slang": "pbjt", "original": "peanut butter jelly time" },
    { "slang": "pbkc", "original": "Problem between keyboard & chair" },
    { "slang": "pbly", "original": "probably" },
    { "slang": "pbm", "original": "parent behind me" },
    { "slang": "pbp", "original": "Please Be Patient" },
    { "slang": "pcbd", "original": "page cannot be displayed" },
    { "slang": "pce", "original": "peace" },
    { "slang": "pcent", "original": "percent" },
    { "slang": "pcm", "original": "please call me" },
    { "slang": "pco", "original": "please come over" },
    { "slang": "pcrs", "original": "Parents can read slang" },
    { "slang": "pda", "original": "public display of affection" },
    { "slang": "pdg", "original": "pretty damn good" },
    { "slang": "pdq", "original": "pretty damn quick" },
    { "slang": "peanus", "original": "penis" },
    { "slang": "pearoast", "original": "repost" },
    { "slang": "pebcak", "original": "Problem Exists Between Chair and Keyboard" },
    { "slang": "pebkac", "original": "problem exists between keyboard and chair" },
    { "slang": "pebmac", "original": "Problem Exist Between monitor and chair" },
    { "slang": "peep dis", "original": "check out what I'm telling you" },
    { "slang": "peeps", "original": "people" },
    { "slang": "pen0r", "original": "Penis" },
    { "slang": "pen15", "original": "penis" },
    { "slang": "penor", "original": "penis" },
    { "slang": "peoples", "original": "people" },
    { "slang": "perv", "original": "pervert" },
    { "slang": "pewp", "original": "poop" },
    { "slang": "pex", "original": "Please explain?" },
    { "slang": "pezzas", "original": "parents" },
    { "slang": "pf", "original": "profile " },
    { "slang": "pfa", "original": "Please Find Attached" },
    { "slang": "pfm", "original": "Please forgive me" },
    { "slang": "pfo", "original": "please fuck off" },
    { "slang": "pfos", "original": "parental figure over sholder" },
    { "slang": "pfy", "original": "pimply faced youth" },
    { "slang": "pg", "original": "page" },
    { "slang": "ph#", "original": "phone number" },
    { "slang": "ph33r", "original": "fear" },
    { "slang": "ph34r", "original": "fear" },
    { "slang": "phag", "original": "fag" },
    { "slang": "phail", "original": "fail" },
    { "slang": "phat", "original": "pretty hot and tasty" },
    { "slang": "phayl", "original": "fail" },
    { "slang": "phear", "original": "fear" },
    { "slang": "phlr", "original": "peace hugs love respect" },
    { "slang": "phm", "original": "please help me" },
    { "slang": "phq", "original": "fuck you" },
    { "slang": "phreak", "original": "freak" },
    { "slang": "phreaker", "original": "phone hacker" },
    { "slang": "phuck", "original": "fuck" },
    { "slang": "phucker", "original": "fucker" },
    { "slang": "phuk", "original": "fuck" },
    { "slang": "phun", "original": "fun" },
    { "slang": "phux", "original": "Fuck" },
    { "slang": "phuxor", "original": "fuck" },
    { "slang": "piab", "original": "panties in a bunch" },
    { "slang": "pic", "original": "picture" },
    { "slang": "piccies", "original": "Pictures" },
    { "slang": "pics", "original": "pictures" },
    { "slang": "pihb", "original": "pee in his/her butt" },
    { "slang": "piihb", "original": "put it in her butt" },
    { "slang": "piitb", "original": "put it in the butt" },
    { "slang": "pima", "original": "Pain in my ass" },
    { "slang": "pimfa", "original": "pain in my fucking ass" },
    { "slang": "pimha", "original": "Pain in my hairy ass" },
    { "slang": "pimpl", "original": "pissing in my pants laughing" },
    { "slang": "pino", "original": "Filipino" },
    { "slang": "pir", "original": "parents in room" },
    { "slang": "pirlos", "original": "parent in room looking over shoulder" },
    { "slang": "pita", "original": "pain in the ass" },
    { "slang": "pitfa", "original": "Pain In The Fucking Ass" },
    { "slang": "pitr", "original": "parent in the room" },
    { "slang": "pitrtul", "original": "parents in the room text you later" },
    { "slang": "piw", "original": "Parent is watching" },
    { "slang": "pix", "original": "pictures" },
    { "slang": "pk", "original": "player kill" },
    { "slang": "pkemon", "original": "pokemon" },
    { "slang": "pker", "original": "player killer" },
    { "slang": "pking", "original": "player killing" },
    { "slang": "pl", "original": "parent looking" },
    { "slang": "pl0x", "original": "please" },
    { "slang": "pl8", "original": "plate" },
    { "slang": "plac", "original": "parent looking at computer" },
    { "slang": "plams", "original": "parents looking at my screen" },
    { "slang": "plars", "original": "party like a rock star" },
    { "slang": "platcs", "original": "parent looking at the computer screen" },
    { "slang": "ple's", "original": "please" },
    { "slang": "pleaz", "original": "please" },
    { "slang": "pleez", "original": "please" },
    { "slang": "pleeze", "original": "please" },
    { "slang": "pleze", "original": "please" },
    { "slang": "pliz", "original": "please" },
    { "slang": "plma", "original": "please leave me alone " },
    { "slang": "plmk", "original": "please let me know" },
    { "slang": "plocks", "original": "please" },
    { "slang": "plom", "original": "parents looking over me" },
    { "slang": "plomb", "original": "parents looking over my back" },
    { "slang": "ploms", "original": "parent looking over my shoulder" },
    { "slang": "plos", "original": "Parents Looking Over Shoulder" },
    { "slang": "plox", "original": "please" },
    { "slang": "ploxxorz", "original": "please" },
    { "slang": "pls", "original": "please" },
    { "slang": "plse", "original": "please" },
    { "slang": "plx", "original": "please/thanks" },
    { "slang": "plywm", "original": "play with me" },
    { "slang": "plz", "original": "please" },
    { "slang": "plzkthx", "original": "Please? OK, Thank you" },
    { "slang": "plzthx", "original": "please? Thanks" },
    { "slang": "pmfji", "original": "Pardon me for jumping in" },
    { "slang": "pmfsl", "original": "piss my fucking self laughing" },
    { "slang": "pmg", "original": "oh my God" },
    { "slang": "pmita", "original": "pound me in the ass" },
    { "slang": "pmitap", "original": "pound me in the ass prison" },
    { "slang": "pml", "original": "pissing myself laughing" },
    { "slang": "pmo", "original": "pissing me off" },
    { "slang": "pmp", "original": "pissing my pants" },
    { "slang": "pmpl", "original": "piss my pants laughing" },
    { "slang": "pmsfl", "original": "Pissed Myself Fucking Laughing" },
    { "slang": "pmsl", "original": "piss my self laughing" },
    { "slang": "pmt", "original": "pretty much this" },
    { "slang": "pnbf", "original": "Potential new boy friend" },
    { "slang": "pnhlgd", "original": "parents not home, let's get dirty" },
    { "slang": "pns", "original": "penis" },
    { "slang": "pnus", "original": "penis" },
    { "slang": "po", "original": "piss off" },
    { "slang": "po po", "original": "police" },
    { "slang": "po'd", "original": "pissed off" },
    { "slang": "pob", "original": "parent over back" },
    { "slang": "poc", "original": "Piece of crap" },
    { "slang": "poed", "original": "pissed off" },
    { "slang": "poets", "original": "piss off early, tomorrow's Saturday" },
    { "slang": "poi", "original": "point of interest" },
    { "slang": "poidnh", "original": "Pics or it did not happen " },
    { "slang": "pol", "original": "parent over looking" },
    { "slang": "poms", "original": "parent over my shoulder" },
    { "slang": "poo", "original": "poop" },
    { "slang": "poontang", "original": "female genitalia" },
    { "slang": "pooter", "original": "Computer" },
    { "slang": "popo", "original": "police" },
    { "slang": "poq", "original": "Piss Off Quick" },
    { "slang": "pos", "original": "Parent Over Shoulder" },
    { "slang": "poscs", "original": "parents over sholder change subject" },
    { "slang": "posmbri", "original": "parent over shoulder might be reading it" },
    { "slang": "potc", "original": "pirates of the caribbean" },
    { "slang": "pots", "original": "Plain Old Telephone Service" },
    { "slang": "pov", "original": "point of view" },
    { "slang": "pow", "original": "prisoner of war" },
    { "slang": "pp", "original": "pee pee" },
    { "slang": "ppl", "original": "people" },
    { "slang": "ppls", "original": "people" },
    { "slang": "pplz", "original": "people" },
    { "slang": "ppor", "original": "post proof or recant" },
    { "slang": "ppppppp", "original": "Prior Proper Planning Prevents Piss Poor Performance" },
    { "slang": "pr0", "original": "professional" },
    { "slang": "pr0n", "original": "porn" },
    { "slang": "pr0nz", "original": "porn" },
    { "slang": "prblm", "original": "Problem" },
    { "slang": "prd", "original": "period" },
    { "slang": "preggers", "original": "pregnant" },
    { "slang": "prego", "original": "Pregnant" },
    { "slang": "prfct", "original": "perfect" },
    { "slang": "prn", "original": "porn" },
    { "slang": "prncpl", "original": "principal" },
    { "slang": "prncss", "original": "princess" },
    { "slang": "prnoscrn", "original": "porn on screen" },
    { "slang": "pro", "original": "professional" },
    { "slang": "prob", "original": "problem" },
    { "slang": "probly", "original": "probably" },
    { "slang": "probz", "original": "probably" },
    { "slang": "prod", "original": "product" },
    { "slang": "prolly", "original": "Probably" },
    { "slang": "prollz", "original": "probably" },
    { "slang": "promos", "original": "promotions" },
    { "slang": "pron", "original": "porn" },
    { "slang": "proxie", "original": "proxy" },
    { "slang": "prp", "original": "please reply" },
    { "slang": "prsn", "original": "person" },
    { "slang": "prty", "original": "party" },
    { "slang": "prv", "original": "private" },
    { "slang": "prvrt", "original": "pervert" },
    { "slang": "prw", "original": "parents are watching" },
    { "slang": "ps1", "original": "Play Station 1" },
    { "slang": "ps2", "original": "Play Station 2" },
    { "slang": "ps3", "original": "Play Station 3" },
    { "slang": "psa", "original": "Public Service Announcement" },
    { "slang": "psbms", "original": "parent standing by my side" },
    { "slang": "psn", "original": "playstation netwok" },
    { "slang": "psos", "original": "parent standing over sholder" },
    { "slang": "psp", "original": "playstation portable" },
    { "slang": "pssy", "original": "pussy" },
    { "slang": "pst", "original": "please send tell" },
    { "slang": "pt33n", "original": "preteen" },
    { "slang": "ptbb", "original": "pass the barf bag" },
    { "slang": "ptfo", "original": "passed the fuck out" },
    { "slang": "pthc", "original": "preteen hardcore" },
    { "slang": "ptl", "original": "Praise the Lord" },
    { "slang": "pto", "original": "Personal Time Off " },
    { "slang": "ptw", "original": "play to win " },
    { "slang": "puh-leaze", "original": "Please" },
    { "slang": "purty", "original": "pretty" },
    { "slang": "puter", "original": "Computer" },
    { "slang": "pvp", "original": "player versus player" },
    { "slang": "pvt", "original": "pervert" },
    { "slang": "pw", "original": "parent watching" },
    { "slang": "pwb", "original": "pussy whipped bitch" },
    { "slang": "pwcb", "original": "parents watching close by" },
    { "slang": "pwd", "original": "password" },
    { "slang": "pwn", "original": "made to look bad" },
    { "slang": "pwn3d", "original": "owned" },
    { "slang": "pwn3r", "original": "owner" },
    { "slang": "pwnage", "original": "Ownage" },
    { "slang": "pwnd", "original": "owned" },
    { "slang": "pwned", "original": "made to look bad" },
    { "slang": "pwner", "original": "owner" },
    { "slang": "pwnt", "original": "owned" },
    { "slang": "pwnz", "original": "owns" },
    { "slang": "pwnzor", "original": "owner" },
    { "slang": "pwob", "original": "Parent watching over back" },
    { "slang": "pwoms", "original": "parent watching over my shoulder" },
    { "slang": "pwor", "original": "power" },
    { "slang": "pwos", "original": "parent was over sholder" },
    { "slang": "pww", "original": "parents were watching" },
    { "slang": "pxr", "original": "punk rocker" },
    { "slang": "pydim", "original": "put your dick in me" },
    { "slang": "pyfco", "original": "put your freaking clothes on" },
    { "slang": "pyt", "original": "pretty young thing" },
    { "slang": "pz", "original": "peace" },
    { "slang": "pzled", "original": "puzzled" },
    { "slang": "p^s", "original": "parent over shoulder" },
    { "slang": "q2c", "original": "quick to cum" },
    { "slang": "q33r", "original": "Queer" },
    { "slang": "q4u", "original": "question for you" },
    { "slang": "qed", "original": "I've made my Point" },
    { "slang": "qfe", "original": "quoted for emphasis" },
    { "slang": "qfmft", "original": "quoted for motherfucking truth" },
    { "slang": "qft", "original": "quoted for truth" },
    { "slang": "qft&gj", "original": "quoted for truth and great justice" },
    { "slang": "ql", "original": "cool" },
    { "slang": "qltm", "original": "quietly laughing to myself" },
    { "slang": "qna", "original": "question and answer" },
    { "slang": "qool", "original": "cool" },
    { "slang": "qoolz", "original": "cool" },
    { "slang": "qotd", "original": "quote of the day" },
    { "slang": "qotsa", "original": "queens of the stone age" },
    { "slang": "qoty", "original": "quote of the year" },
    { "slang": "qpr", "original": "quite pathetic really" },
    { "slang": "qpwd", "original": "quit posting while drunk" },
    { "slang": "qq", "original": "crying eyes" },
    { "slang": "qt", "original": "cutie" },
    { "slang": "qt3.14", "original": "cutie pie" },
    { "slang": "qte", "original": "cutie" },
    { "slang": "qtpi", "original": "cutie pie" },
    { "slang": "r", "original": "are" },
    { "slang": "r-tard", "original": "retard" },
    { "slang": "r.i.p", "original": "Rest in peace" },
    { "slang": "r.i.p.", "original": "rest in peace" },
    { "slang": "r0x0rz", "original": "rocks" },
    { "slang": "r2f", "original": "Ready To Fuck" },
    { "slang": "r8", "original": "rate" },
    { "slang": "r8p", "original": "rape" },
    { "slang": "r8pist", "original": "rapist" },
    { "slang": "r8t", "original": "rate" },
    { "slang": "ra2", "original": "red alert 2 (game)" },
    { "slang": "ra3", "original": "Red Alert 3 (game)" },
    { "slang": "raoflmao", "original": "rolling around on floor laughing my ass off" },
    { "slang": "rawk", "original": "Rock" },
    { "slang": "rawks", "original": "rocks" },
    { "slang": "rawr", "original": "roar" },
    { "slang": "rb@u", "original": "right back at you" },
    { "slang": "rbau", "original": "right back at you" },
    { "slang": "rbay", "original": "right back at you" },
    { "slang": "rbm", "original": "right behind me" },
    { "slang": "rbtl", "original": "Read between the lines" },
    { "slang": "rbty", "original": "right back to you" },
    { "slang": "rcks", "original": "Rocks" },
    { "slang": "rcsa", "original": "right click save as" },
    { "slang": "rcvd", "original": "received" },
    { "slang": "rdy", "original": "ready" },
    { "slang": "re", "original": "reply" },
    { "slang": "re/rehi", "original": "hello again" },
    { "slang": "reefer", "original": "marijuana" },
    { "slang": "refl", "original": "rolling on the floor laughing" },
    { "slang": "rehi", "original": "hello again" },
    { "slang": "rele", "original": "really" },
    { "slang": "rents", "original": "parents" },
    { "slang": "rentz", "original": "parents" },
    { "slang": "rep", "original": "to represent" },
    { "slang": "reppin", "original": "representing" },
    { "slang": "retrotextual", "original": "One who is using out of date words and abbreviations while texting." },
    { "slang": "rff", "original": "really fucking funny" },
    { "slang": "rflmao", "original": "rolling on the floor laughing my ass off" },
    { "slang": "rfn", "original": "right fucking now" },
    { "slang": "rgr", "original": "roger" },
    { "slang": "rhcp", "original": "red hot chilli peppers" },
    { "slang": "rhgir", "original": "really hot guy in room" },
    { "slang": "rhs", "original": "right hand side" },
    { "slang": "ricl", "original": "rolling in chair laughing" },
    { "slang": "rifk", "original": "rolling on the floor laughing" },
    { "slang": "rihad", "original": "Rot In Hell And Die" },
    { "slang": "rino", "original": "republican in name only" },
    { "slang": "rite", "original": "right" },
    { "slang": "ritjive", "original": "non virgin" },
    { "slang": "rjct", "original": "reject" },
    { "slang": "rl", "original": "real life" },
    { "slang": "rlbf", "original": "Real Life Boy Friend" },
    { "slang": "rlf", "original": "Real Life Friend" },
    { "slang": "rlg", "original": "really loud giggle" },
    { "slang": "rlgf", "original": "Real Life Girl Friend" },
    { "slang": "rlly", "original": "really" },
    { "slang": "rln", "original": "real life name" },
    { "slang": "rly", "original": "really" },
    { "slang": "rlz", "original": "rules" },
    { "slang": "rlze", "original": "realize" },
    { "slang": "rm", "original": "room" },
    { "slang": "rme", "original": "rolling my eyes" },
    { "slang": "rmr", "original": "remember" },
    { "slang": "rmso", "original": "Rock My socks off" },
    { "slang": "rn", "original": "Right now" },
    { "slang": "rnt", "original": "aren't" },
    { "slang": "ro", "original": "rock out" },
    { "slang": "rockr", "original": "rocker" },
    { "slang": "rodger", "original": "affirmative" },
    { "slang": "rofalol", "original": "roll on the floor and laugh out loud" },
    { "slang": "rofc", "original": "Rolling On Floor Crying" },
    { "slang": "roffle", "original": "rolling on the floor laughing" },
    { "slang": "roffle out loud", "original": "rolling on the floor laughing out loud" },
    { "slang": "rofflecake", "original": "rolling on the floor laughing" },
    { "slang": "rofflecopters", "original": "rolling on the floor with laughter" },
    { "slang": "roffleol", "original": "rolling on the floor laughing out loud" },
    { "slang": "roffles", "original": "rolling on floor laughing" },
    { "slang": "rofflmfao", "original": "rolling on the floor laughing my fucking ass" },
    { "slang": "rofl", "original": "rolling on the floor laughing" },
    { "slang": "rofl&pmp", "original": "rolling on floor laughing and peeing my pants" },
    { "slang": "roflao", "original": "rolling on the floor laughing my ass off" },
    { "slang": "roflastc", "original": "Rolling On Floor Laughing And Scaring The Cat" },
    { "slang": "roflcopter", "original": "Rolling on the floor laughing" },
    { "slang": "roflcopters", "original": "rolling on the floor laughing, VERY funny." },
    { "slang": "roflkmd", "original": "rolling on the floor laughing kicking my dog" },
    { "slang": "rofllh", "original": "rolling on the floor laughing like hell" },
    { "slang": "roflmao", "original": "rolling on the floor laughing my ass off" },
    { "slang": "roflmaoapimp", "original": "rolling on the floor laughing my ass off and peeing in my pants" },
    { "slang": "roflmaool", "original": "Rolling on the floor laughing my ass off out loud" },
    { "slang": "roflmaopmp", "original": "rolling on the floor, laughing my ass off, pissing my pants" },
    { "slang": "roflmaouts", "original": "Rolling on floor laughing my fucking ass off unable to speak" },
    { "slang": "roflmaowpimp", "original": "rolling on floor laughing my ass off while peeing in my pants" },
    { "slang": "roflmbfao", "original": "Rolling On Floor Laughing My Big Fat Ass Off " },
    { "slang": "roflmbo", "original": "rolling on floor laughing my butt off" },
    { "slang": "roflmfao", "original": "rolling on the floor laughing my fucking ass off" },
    { "slang": "roflmfaopimp", "original": "rolling on the floor laughing my fucking ass off pissing in my pants" },
    { "slang": "roflmfaopmp", "original": "rolling on flor laughing my fucking ass of peeing my pants" },
    { "slang": "roflmgao", "original": "rolling on the floor laughing my gay ass off" },
    { "slang": "roflmgdao", "original": "rolling on the floor laughing my god damn ass off" },
    { "slang": "roflmgdmfao", "original": "roling on floor laughing my god damn mother fucking ass off" },
    { "slang": "roflmgo", "original": "Rolling On Floor Laughing My Guts Out" },
    { "slang": "roflmho", "original": "Rolling on the floor laughing my head off" },
    { "slang": "roflmiaha", "original": "Rolling on the floor laughing myself into a heart attack" },
    { "slang": "roflmmfao", "original": "rolling on the floor laughing my mother fucking ass off" },
    { "slang": "roflol", "original": "rolling on floor laughing out loud" },
    { "slang": "roflolbag", "original": "Rolling On The Floor Laughing Out Loud Busting A Gut" },
    { "slang": "roflpimp", "original": "rolling on the floor laughing pissing in my pants" },
    { "slang": "roflpmp", "original": "rolling on the floor laughing peeing my pants" },
    { "slang": "roflwtime", "original": "Rolling on the Floor laughing with tears in my eyes" },
    { "slang": "rofpml", "original": "rolling on the floor pissing myself laughing" },
    { "slang": "rofwl", "original": "Rolling on the floor while laughing" },
    { "slang": "roger", "original": "affirmative" },
    { "slang": "rogl", "original": "rolling on ground laughing" },
    { "slang": "roglmfao", "original": "rolling on ground laughing my fucking ass off" },
    { "slang": "roi", "original": "Return On Investment" },
    { "slang": "roids", "original": "steroids" },
    { "slang": "roj", "original": "affirmative" },
    { "slang": "rol", "original": "rolling over laugihng" },
    { "slang": "rolmao", "original": "Rolling Over Laughing My Ass Off" },
    { "slang": "rolmfao", "original": "rolling over laughing my fucking ass off" },
    { "slang": "rombl", "original": "rolled off my bed laughing" },
    { "slang": "rong", "original": "wrong" },
    { "slang": "roofles", "original": "rolling on the floor laughing" },
    { "slang": "ror", "original": "raughing out roud" },
    { "slang": "rotf", "original": "rolling on the floor" },
    { "slang": "rotfalol", "original": "roll on the floor and laugh out loud" },
    { "slang": "rotffl", "original": "roll on the fucking floor laughing" },
    { "slang": "rotfflmao", "original": "rolling on the fucking floor laughing my ass off" },
    { "slang": "rotfflmfao", "original": "rolling on the fucking floor laughing my fucking ass off" },
    { "slang": "rotfl", "original": "rolling on the floor laughing" },
    { "slang": "rotflaviab", "original": "rolling on the floor laughing and vomiting in a bucket" },
    { "slang": "rotflmao", "original": "rolling on the floor laughing my ass off" },
    { "slang": "rotflmaofaktd", "original": "Rolling on the floor laughing my ass off farted and killed the dog" },
    { "slang": "rotflmaool", "original": "rolling on the floor laughing my ass off out loud" },
    { "slang": "rotflmaostc", "original": "rolling on the floor laughing my ass off scaring the cat" },
    { "slang": "rotflmbo", "original": "rolling on the floor laughing my butt off" },
    { "slang": "rotflmfao", "original": "rolling on the floor laughing my fucking ass off" },
    { "slang": "rotflmfaopimp", "original": "rolling on the floor laughing my fucking ass off peeing in my pants" },
    { "slang": "rotflmfaopmp", "original": "rolling on the floor laughing my ass off pissin my pants" },
    { "slang": "rotflmfho", "original": "rolling on the floor laughing my fucking head off" },
    { "slang": "rotflmho", "original": "rolling on the floor laughing my head off" },
    { "slang": "rotflmmfao", "original": "rolling on the floor laughing my mother fucking ass off" },
    { "slang": "rotflol", "original": "rolling on the floor laughing out loud" },
    { "slang": "rotfpm", "original": "rolling on the floor pissing myself" },
    { "slang": "rotfwlmao", "original": "rolling on the floor while laughing my ass off" },
    { "slang": "rotg", "original": "rolling on the ground" },
    { "slang": "rotgl", "original": "roll on the ground laughing" },
    { "slang": "rotglmao", "original": "rolling on the ground laughing my ass off" },
    { "slang": "rotw", "original": "rest of the world" },
    { "slang": "rowyco", "original": "rock out with your cock out" },
    { "slang": "rox", "original": "rocks" },
    { "slang": "roxor", "original": "rock" },
    { "slang": "roxorz", "original": "rocks" },
    { "slang": "roxxor", "original": "rock" },
    { "slang": "rp", "original": "roleplay" },
    { "slang": "rpg", "original": "role playing game" },
    { "slang": "rpita", "original": "royal pain in the ass" },
    { "slang": "rplbk", "original": "reply back" },
    { "slang": "rpo", "original": "royally pissed off" },
    { "slang": "rq", "original": "real quick" },
    { "slang": "rr", "original": "rest room" },
    { "slang": "rrb", "original": "restroom break" },
    { "slang": "rsn", "original": "real soon now" },
    { "slang": "rsp", "original": "respawn" },
    { "slang": "rspct", "original": "respect" },
    { "slang": "rsps", "original": "Runescape Private Server" },
    { "slang": "rta", "original": "read the article" },
    { "slang": "rtard", "original": "retard" },
    { "slang": "rtbq", "original": "Read The Blinking Question" },
    { "slang": "rtf", "original": "return the favor" },
    { "slang": "rtfa", "original": "read the fucking article" },
    { "slang": "rtffp", "original": "Read the fucking front page" },
    { "slang": "rtfm", "original": "read the fucking manual" },
    { "slang": "rtfmfm", "original": "read the fucking manual fucking moron" },
    { "slang": "rtfmm", "original": "read the fucking manual moron" },
    { "slang": "rtfms", "original": "Read The Fucking Manual Stupid" },
    { "slang": "rtfp", "original": "read the fucking post" },
    { "slang": "rtfq", "original": "Read The Fucking Question" },
    { "slang": "rtfs", "original": "read the fucking summary" },
    { "slang": "rtfu", "original": "Ready the fuck up" },
    { "slang": "rtg", "original": "ready to go" },
    { "slang": "rtl", "original": "report the loss" },
    { "slang": "rtm", "original": "read the manual" },
    { "slang": "rtr", "original": "Read the Rules" },
    { "slang": "rtry", "original": "retry" },
    { "slang": "rts", "original": "Real-time strategy" },
    { "slang": "ru", "original": "are you" },
    { "slang": "ru18", "original": "are you 18" },
    { "slang": "rua", "original": "are you alone" },
    { "slang": "ruabog", "original": "are you a boy or girl" },
    { "slang": "ruagoab", "original": "are you a girl or a boy" },
    { "slang": "rubz2nt", "original": "are you busy tonight" },
    { "slang": "rufkm", "original": "are you fucking kidding me" },
    { "slang": "rugay", "original": "are you gay" },
    { "slang": "rugta", "original": "are you going to answer" },
    { "slang": "ruh", "original": "are you horny" },
    { "slang": "ruk", "original": "are you ok?" },
    { "slang": "rukm", "original": "are you kidding me" },
    { "slang": "rul8", "original": "Are you late" },
    { "slang": "rumf", "original": "Are you male or female" },
    { "slang": "ruok", "original": "are you ok?" },
    { "slang": "rur", "original": "are you ready" },
    { "slang": "rut", "original": "are you there" },
    { "slang": "ruwm", "original": "are you watching me" },
    { "slang": "rwb", "original": "Rich White Bitch" },
    { "slang": "rys", "original": "are you single" },
    { "slang": "ryt", "original": "right" },
    { "slang": "ryte", "original": "right" },
    { "slang": "*s*", "original": "smile" },
    { "slang": "psl", "original": "Pumpkin Spice Latte" },
    { "slang": "s'ok", "original": "it's okay" },
    { "slang": "s'pose", "original": "suppose" },
    { "slang": "s'up", "original": "what is up" },
    { "slang": "s.i.n.g.l.e", "original": "Stay intoxicated nightly, get laid everyday." },
    { "slang": "s.i.t.", "original": "stay in touch" },
    { "slang": "s.o.a.b.", "original": "son of a bitch" },
    { "slang": "s.o.b.", "original": "son of a bitch" },
    { "slang": "s.w.a.k.", "original": "sealed with a kiss" },
    { "slang": "s/b", "original": "should be" },
    { "slang": "s2a", "original": "sent to all" },
    { "slang": "s2bu", "original": "Sucks to be you" },
    { "slang": "s2g", "original": "swear to god" },
    { "slang": "s2r", "original": "send to receive" },
    { "slang": "s2u", "original": "same to you" },
    { "slang": "s2us", "original": "Speak to you soon" },
    { "slang": "s3x", "original": "Sex." },
    { "slang": "s4se", "original": "Sight For Sore Eyes" },
    { "slang": "s8ter", "original": "skater" },
    { "slang": "sab", "original": "slap a bitch" },
    { "slang": "safm", "original": "stay away from me" },
    { "slang": "sagn", "original": "Spelling and Grammar Nazi" },
    { "slang": "sah", "original": "sexy as hell" },
    { "slang": "sahm", "original": "stay at home mom" },
    { "slang": "sase", "original": "self addressed stamped envelope" },
    { "slang": "sbc", "original": "sorry bout caps" },
    { "slang": "sbcg4ap", "original": "strongbads cool game for attractive people" },
    { "slang": "sbd", "original": "silent but deadly" },
    { "slang": "sblai", "original": "stop babbaling like an idiot" },
    { "slang": "sbrd", "original": "so bored" },
    { "slang": "sbs", "original": "such bull shit" },
    { "slang": "sbt", "original": "sorry bout that" },
    { "slang": "scnr", "original": "sorry, I couldn't resist" },
    { "slang": "scool", "original": "school" },
    { "slang": "scrilla", "original": "money" },
    { "slang": "scrt", "original": "secret" },
    { "slang": "scurred", "original": "scared" },
    { "slang": "sd", "original": "suck dick" },
    { "slang": "sdf^", "original": "shut da fuck up" },
    { "slang": "sdk", "original": "Software Development Kit" },
    { "slang": "sdlc", "original": "Software Development Life Cycle" },
    { "slang": "sec", "original": "second" },
    { "slang": "secks", "original": "sex" },
    { "slang": "secksea", "original": "Sexy" },
    { "slang": "secksy", "original": "sexy" },
    { "slang": "sed", "original": "said" },
    { "slang": "see through your eyes", "original": "stye" },
    { "slang": "seg", "original": "Shit Eatin Grin" },
    { "slang": "seks", "original": "sex" },
    { "slang": "sellin", "original": "selling" },
    { "slang": "seo", "original": "Search Engine Optimization" },
    { "slang": "serp", "original": "search engine results page" },
    { "slang": "sexc", "original": "sexy" },
    { "slang": "sexe", "original": "sexy" },
    { "slang": "sexi", "original": "Sexy" },
    { "slang": "sexii", "original": "sexy" },
    { "slang": "sexilicious", "original": "Very Sexy" },
    { "slang": "sexx0rz", "original": "sex" },
    { "slang": "sez", "original": "says" },
    { "slang": "sfam", "original": "Sister from another mother" },
    { "slang": "sfe", "original": "safe" },
    { "slang": "sfh", "original": "So Fucking Hot" },
    { "slang": "sfipmp", "original": "so funny I peed my pants" },
    { "slang": "sfm", "original": "so fucking much" },
    { "slang": "sfr", "original": "so fucking random" },
    { "slang": "sfs", "original": "so fucking stupid" },
    { "slang": "sfsg", "original": "So far so good" },
    { "slang": "sfu", "original": "shut the fuck up" },
    { "slang": "sfw", "original": "safe for work" },
    { "slang": "sfwuz", "original": "safe for work until zoomed" },
    { "slang": "sfy", "original": "speak for yourself" },
    { "slang": "sg", "original": "so good" },
    { "slang": "sgb", "original": "straight/gay/bisexual" },
    { "slang": "sgbadq", "original": "Search google before asking dumb questions" },
    { "slang": "sgi", "original": "Still got it" },
    { "slang": "sgtm", "original": "slightly gigling to myself" },
    { "slang": "sh", "original": "shit happens" },
    { "slang": "shag", "original": "fuck" },
    { "slang": "shawty", "original": "girl" },
    { "slang": "shd", "original": "should" },
    { "slang": "shexi", "original": "sexy" },
    { "slang": "shexy", "original": "sexy" },
    { "slang": "shiat", "original": "Shit" },
    { "slang": "shiet", "original": "shit" },
    { "slang": "shite", "original": "shit" },
    { "slang": "shiz", "original": "shit" },
    { "slang": "shizit", "original": "shit" },
    { "slang": "shiznat", "original": "shit" },
    { "slang": "shiznit", "original": "shit" },
    { "slang": "shizz", "original": "shit" },
    { "slang": "shizzle", "original": "shit" },
    { "slang": "shld", "original": "should" },
    { "slang": "shmexy", "original": "sexy" },
    { "slang": "shmily", "original": "see how much i love you" },
    { "slang": "sho", "original": "sure" },
    { "slang": "sho'nuff", "original": "sure enough" },
    { "slang": "showin", "original": "showing" },
    { "slang": "shrn", "original": "so hot right now" },
    { "slang": "sht", "original": "shit" },
    { "slang": "shtf", "original": "shit hits the fan" },
    { "slang": "shud", "original": "should" },
    { "slang": "shuddup", "original": "Shut Up" },
    { "slang": "shup", "original": "shut up" },
    { "slang": "shure", "original": "sure" },
    { "slang": "shut^", "original": "shut Up" },
    { "slang": "shwr", "original": "shower" },
    { "slang": "shyat", "original": "shit" },
    { "slang": "shyt", "original": "shit" },
    { "slang": "siao", "original": "school is almost over" },
    { "slang": "sibir", "original": "sibling in room" },
    { "slang": "sic", "original": "said in context" },
    { "slang": "sicl", "original": "sitting in chair laughing" },
    { "slang": "sif", "original": "as if" },
    { "slang": "sifn't", "original": "as if not" },
    { "slang": "sig", "original": "Signature" },
    { "slang": "siggy", "original": "Signature" },
    { "slang": "silf", "original": "Sister I'd Like To Fuck" },
    { "slang": "simcl", "original": "sitting in my chair laughing" },
    { "slang": "simclmao", "original": "sitting in my chair laughing my ass off" },
    { "slang": "siol", "original": "Shout It Out Loud" },
    { "slang": "sis", "original": "sister" },
    { "slang": "sista", "original": "Sister" },
    { "slang": "sitb", "original": "sex in the but" },
    { "slang": "sitmf", "original": "say it to my face" },
    { "slang": "siu", "original": "suck it up" },
    { "slang": "siuya", "original": " shove it up your ass" },
    { "slang": "sk", "original": "spawn kill" },
    { "slang": "sk8", "original": "skate" },
    { "slang": "sk8er", "original": "skater" },
    { "slang": "sk8ing", "original": "Skating" },
    { "slang": "sk8r", "original": "skater" },
    { "slang": "sk8ter", "original": "skater" },
    { "slang": "sk8tr", "original": "skater" },
    { "slang": "skb", "original": "should know better" },
    { "slang": "sked", "original": "schedule" },
    { "slang": "skeet", "original": "ejaculate" },
    { "slang": "skewl", "original": "school" },
    { "slang": "skhool", "original": "school" },
    { "slang": "skillz", "original": "skills" },
    { "slang": "skl", "original": "School" },
    { "slang": "skool", "original": "school" },
    { "slang": "skoul", "original": "school" },
    { "slang": "sktr", "original": "skater" },
    { "slang": "skwl", "original": "school" },
    { "slang": "sl4n", "original": "so long for now" },
    { "slang": "sleepin", "original": "sleeping" },
    { "slang": "sleepn", "original": "sleeping" },
    { "slang": "slf", "original": "sexy little fuck" },
    { "slang": "slgb", "original": "Straight/Lesbian/Gay/Bisexual" },
    { "slang": "slng", "original": "slang" },
    { "slang": "slo", "original": "slow" },
    { "slang": "slore", "original": "slutty whore" },
    { "slang": "slos", "original": "someone looking over shoulder" },
    { "slang": "slp", "original": "sleep" },
    { "slang": "slt", "original": "something like that" },
    { "slang": "sl^t", "original": "Slut " },
    { "slang": "sm", "original": "social media" },
    { "slang": "sm1", "original": "someone" },
    { "slang": "smb", "original": "see my blog" },
    { "slang": "smbd", "original": "suck my big dick " },
    { "slang": "smbt", "original": "Suck my big toe" },
    { "slang": "smc", "original": "suck my cock" },
    { "slang": "smd", "original": "suck my dick" },
    { "slang": "smdb", "original": "suck my dick bitch" },
    { "slang": "smdvq", "original": "suck my dick quickly" },
    { "slang": "smeg", "original": "fuck" },
    { "slang": "smexy", "original": "sexy" },
    { "slang": "smf", "original": "stupid motherfucker" },
    { "slang": "smfd", "original": "suck my fucking dick" },
    { "slang": "smfpos", "original": "stupid mother fucking piece of shit" },
    { "slang": "smh", "original": "shaking my head" },
    { "slang": "smhb", "original": "suck my hairy balls" },
    { "slang": "smho", "original": "Screaming My Head Off" },
    { "slang": "smithwaws", "original": "Smack me in the head with a wooden spoon" },
    { "slang": "smofo", "original": "stupid mother fucker" },
    { "slang": "smst", "original": "somebody missed snack time" },
    { "slang": "smt", "original": "suck my tits" },
    { "slang": "smthin", "original": "something" },
    { "slang": "smthng", "original": "something" },
    { "slang": "smtm", "original": "sometime" },
    { "slang": "smto", "original": "Sticking My Tongue Out" },
    { "slang": "smtoay", "original": "Sticking my tongue out at you" },
    { "slang": "sn", "original": "screen name" },
    { "slang": "snafu", "original": "situation normal all fucked up" },
    { "slang": "snafubar", "original": "Situation Normal All Fucked Up Beyond Any Recognition" },
    { "slang": "snes", "original": "Super Nintendo Entertainment System" },
    { "slang": "snew", "original": "what's new" },
    { "slang": "snf", "original": "so not fair" },
    { "slang": "snl", "original": "Saturday Night Live" },
    { "slang": "snm", "original": "say no more" },
    { "slang": "snog", "original": "kiss" },
    { "slang": "snogged", "original": "kissed" },
    { "slang": "soa", "original": "service oriented architecture " },
    { "slang": "soab", "original": "son of a btch" },
    { "slang": "soad", "original": "system of a down" },
    { "slang": "soafb", "original": "son of a fucking bitch" },
    { "slang": "sob", "original": "son of a bitch" },
    { "slang": "sobs", "original": "same, old, boring shit" },
    { "slang": "soc", "original": "Same old crap" },
    { "slang": "soe", "original": "service oriented enterprise" },
    { "slang": "sof", "original": "smile on face" },
    { "slang": "sofas", "original": "stepping out for a smoke" },
    { "slang": "sofs", "original": "same old fucking shit" },
    { "slang": "soi", "original": "service oriented infrastructure" },
    { "slang": "sok", "original": "It's ok" },
    { "slang": "sokay", "original": "it's okay" },
    { "slang": "sol", "original": "Shit outta luck" },
    { "slang": "som'm", "original": "something" },
    { "slang": "som1", "original": "someone" },
    { "slang": "somadn", "original": "sitting on my ass doing nothing" },
    { "slang": "some1", "original": "someone" },
    { "slang": "soml", "original": "story of my life" },
    { "slang": "soo", "original": "So" },
    { "slang": "soobs", "original": "saggy boobs" },
    { "slang": "sool", "original": "shit out of luck" },
    { "slang": "sop", "original": "same old place" },
    { "slang": "sorg", "original": "Straight or Gay" },
    { "slang": "sorreh", "original": "sorry" },
    { "slang": "sorta", "original": "sort of" },
    { "slang": "sos", "original": "same old shit" },
    { "slang": "sosdd", "original": "same old shit, different day" },
    { "slang": "sosg", "original": "spouse over shoulder gone" },
    { "slang": "sot", "original": "suck on this" },
    { "slang": "sotc", "original": "stupid off topic crap" },
    { "slang": "sotr", "original": "sex on the road" },
    { "slang": "sowi", "original": "sorry" },
    { "slang": "sowwy", "original": "sorry" },
    { "slang": "soz", "original": "sorry" },
    { "slang": "spk", "original": "speak" },
    { "slang": "spk2ul8r", "original": "Speak to you later" },
    { "slang": "sploits", "original": "exploits" },
    { "slang": "sploitz", "original": "exploits" },
    { "slang": "spos", "original": "stupid peace of shit" },
    { "slang": "sprm", "original": "sperm" },
    { "slang": "sqtm", "original": "snickering quietly to myself" },
    { "slang": "srch", "original": "search" },
    { "slang": "srly", "original": "seriously" },
    { "slang": "sroucks", "original": "that's cool, but it still sucks" },
    { "slang": "srry", "original": "sorry" },
    { "slang": "srs", "original": "serious" },
    { "slang": "srsly", "original": "seriously" },
    { "slang": "srvis", "original": "Service" },
    { "slang": "sry", "original": "sorry" },
    { "slang": "srynd2g", "original": "sorry need to go" },
    { "slang": "srzly", "original": "seriously" },
    { "slang": "ss", "original": "screenshot" },
    { "slang": "ss4l", "original": "smoking sista for life" },
    { "slang": "ssdd", "original": "same shit, different day" },
    { "slang": "ssdp", "original": "same shit different pile" },
    { "slang": "ssia", "original": "subject says it all" },
    { "slang": "ssl", "original": "secure sockets layer" },
    { "slang": "ssob", "original": "stupid sons of bitches" },
    { "slang": "ssry", "original": "so sorry" },
    { "slang": "sssd", "original": "Same Shit Same Day" },
    { "slang": "st", "original": "Stop That" },
    { "slang": "st1", "original": "stoned" },
    { "slang": "st8", "original": "state" },
    { "slang": "stb", "original": "soon to be" },
    { "slang": "stbx", "original": "soon to be ex" },
    { "slang": "stby", "original": "sucks to be you" },
    { "slang": "std", "original": "sexually transmitted disease" },
    { "slang": "steamloller", "original": "Laughing. Alot." },
    { "slang": "stfd", "original": "sit the fuck down" },
    { "slang": "stff", "original": "stuff" },
    { "slang": "stfm", "original": "search the fucking manual" },
    { "slang": "stfng", "original": "search the fucking news group" },
    { "slang": "stfu", "original": "shut the fuck up" },
    { "slang": "stfua", "original": "shut the fuck up already" },
    { "slang": "stfuah", "original": "shut the fuck up asshole" },
    { "slang": "stfub", "original": "shut the fuck up bitch" },
    { "slang": "stfuda", "original": "Shut the fuck up dumb ass" },
    { "slang": "stfugbtw", "original": "shut the fuck up and get back to work" },
    { "slang": "stfun", "original": "Shut the fuck up nigger" },
    { "slang": "stfuogtfo", "original": "Shut the fuck up or get the fuck out." },
    { "slang": "stfuppercut", "original": "shut the fuck up" },
    { "slang": "stfuyb", "original": "shut the fuck up you bitch" },
    { "slang": "stfuysoab", "original": "shut the fuck up you son of a bitch" },
    { "slang": "stfw", "original": "search the fucking web" },
    { "slang": "stg", "original": "swear to god" },
    { "slang": "sth", "original": "something" },
    { "slang": "sthing", "original": "something" },
    { "slang": "sthu", "original": "shut the hell up" },
    { "slang": "stm", "original": "smiling to myself" },
    { "slang": "stoopid", "original": "stupid" },
    { "slang": "stpd", "original": "stupid" },
    { "slang": "str8", "original": "straight" },
    { "slang": "str8up", "original": "straight up" },
    { "slang": "sts", "original": "so to speak" },
    { "slang": "stsp", "original": "Same Time Same Place" },
    { "slang": "stt", "original": "Same time tomorrow" },
    { "slang": "stufu", "original": "stupid fucker" },
    { "slang": "stupd", "original": "stupid" },
    { "slang": "stw", "original": "share the wealth " },
    { "slang": "stys", "original": "speak to you soon" },
    { "slang": "su", "original": "shut up" },
    { "slang": "suabq", "original": "shut up and be quiet" },
    { "slang": "suagooml", "original": "shut up and get out of my life" },
    { "slang": "suib", "original": "shut up im busy" },
    { "slang": "suk", "original": "suck" },
    { "slang": "suka", "original": "Sucker" },
    { "slang": "sukz", "original": "sucks" },
    { "slang": "sul", "original": "see you later" },
    { "slang": "sum1", "original": "someone" },
    { "slang": "sumfin", "original": "Something" },
    { "slang": "summin", "original": "something" },
    { "slang": "sumone", "original": "someone" },
    { "slang": "sumthin'", "original": "Something" },
    { "slang": "sumtin", "original": "something" },
    { "slang": "sup", "original": "what's up" },
    { "slang": "supa", "original": "super" },
    { "slang": "supposably", "original": "Supposedly" },
    { "slang": "sus", "original": "see you soon" },
    { "slang": "susfu", "original": "situation unchanged, still fucked up" },
    { "slang": "sut", "original": "see you tomorrow" },
    { "slang": "sutuct", "original": "so you think you can type" },
    { "slang": "sux", "original": "sucks" },
    { "slang": "sux0rz", "original": "sucks" },
    { "slang": "sux2bu", "original": "sucks to be you" },
    { "slang": "suxor", "original": "Sucks" },
    { "slang": "suxors", "original": "sucks" },
    { "slang": "suxorz", "original": "sucks" },
    { "slang": "suxx", "original": "sucks" },
    { "slang": "suxxor", "original": "sucks" },
    { "slang": "suyah", "original": "shut up you ass hole!" },
    { "slang": "svn", "original": "seven" },
    { "slang": "svu", "original": "special victims unit" },
    { "slang": "sw", "original": "so what" },
    { "slang": "swafk", "original": "sealed with a friendly kiss" },
    { "slang": "swak", "original": "sealed with a kiss" },
    { "slang": "swakaah", "original": "Sealed With A Kiss And A Hug" },
    { "slang": "swalk", "original": "sealed with a loving kiss" },
    { "slang": "swf", "original": "single white female" },
    { "slang": "swm", "original": "single white male" },
    { "slang": "swmbo", "original": "she who must be obeyed" },
    { "slang": "swmt", "original": "Stop Wasting My Time " },
    { "slang": "swp", "original": "sorry wrong person" },
    { "slang": "swsw2b", "original": "single when she wants to be" },
    { "slang": "swt", "original": "sweet" },
    { "slang": "swtf", "original": "seriously, what the fuck" },
    { "slang": "sx", "original": "sex" },
    { "slang": "sxc", "original": "sexy" },
    { "slang": "sxcy", "original": "sexy" },
    { "slang": "sxe", "original": "straight edge" },
    { "slang": "sxi", "original": "sexy" },
    { "slang": "sxs", "original": "sex" },
    { "slang": "sxy", "original": "sexy" },
    { "slang": "syatp", "original": "see you at the party" },
    { "slang": "sydim", "original": "stick your dick in me" },
    { "slang": "sydlm", "original": "Shut your dirty little mouth" },
    { "slang": "syfm", "original": "shut your fucking mouth" },
    { "slang": "syiab", "original": "see you in a bit" },
    { "slang": "syiaf", "original": "see you in a few" },
    { "slang": "syl", "original": "see you later" },
    { "slang": "syl8r", "original": "see you later" },
    { "slang": "sym", "original": "shut your mouth" },
    { "slang": "syoa", "original": "Save Your Own Ass" },
    { "slang": "syotbf", "original": "see you on the battlefield" },
    { "slang": "syrs", "original": "see ya real soon" },
    { "slang": "sys", "original": "see you soon" },
    { "slang": "sysop", "original": "system operator" },
    { "slang": "syt", "original": "see you there" },
    { "slang": "sytycd", "original": "so you think you can dance " },
    { "slang": "syu", "original": "sex you up" },
    { "slang": "sz", "original": "sorry" },
    { "slang": "Tsm ", "original": "Thanks so much" },
    { "slang": "t#3", "original": "the" },
    { "slang": "t,ftfy", "original": "there, fixed that for you" },
    { "slang": "t.t.y.l", "original": "Talk To You Later" },
    { "slang": "t/a", "original": "Try again" },
    { "slang": "t2b", "original": "time to blunt" },
    { "slang": "t2m", "original": "talk to me" },
    { "slang": "t2u", "original": "talking to you" },
    { "slang": "t2ul", "original": "talk to you later" },
    { "slang": "t2ul8r", "original": "talk to you later" },
    { "slang": "t3h", "original": "the" },
    { "slang": "t4a", "original": "thanks for asking" },
    { "slang": "t4m", "original": "Transgender for Male" },
    { "slang": "t8st", "original": "taste" },
    { "slang": "ta", "original": "thanks again" },
    { "slang": "taci", "original": "that's a crappy idea" },
    { "slang": "tafn", "original": "That's all for now" },
    { "slang": "taht", "original": "that" },
    { "slang": "tai", "original": "think about it" },
    { "slang": "taig", "original": "That's all I got. " },
    { "slang": "tal", "original": "thanks a lot" },
    { "slang": "talkin", "original": "talking" },
    { "slang": "tanq", "original": "thank you" },
    { "slang": "tanstaafl", "original": "there ain't no such thing as a free lunch" },
    { "slang": "tard", "original": "retard" },
    { "slang": "tarfu", "original": "things are really fucked up" },
    { "slang": "tat", "original": "that" },
    { "slang": "tat2", "original": "tattoo" },
    { "slang": "tau", "original": "thinking about you" },
    { "slang": "taunch", "original": "te amo un chingo" },
    { "slang": "taw", "original": "Teachers are Watching" },
    { "slang": "tay", "original": "thinking about you" },
    { "slang": "tb", "original": "text back" },
    { "slang": "tb4u", "original": "too bad for you" },
    { "slang": "tba", "original": "to be anounced" },
    { "slang": "tbc", "original": "To be continued" },
    { "slang": "tbd", "original": "to be decided" },
    { "slang": "tbf", "original": "to be fair" },
    { "slang": "tbfh", "original": "to be fucking honest" },
    { "slang": "tbfu", "original": "too bad for you" },
    { "slang": "tbh", "original": "to be honest" },
    { "slang": "tbhimo", "original": "to be honest in my opinion" },
    { "slang": "tbnt", "original": "thanks but no thanks" },
    { "slang": "tbp", "original": "The Pirate Bay" },
    { "slang": "tbpfh", "original": "To be perfectly fucking honest" },
    { "slang": "tbph", "original": "To be perfectly honest" },
    { "slang": "tbqf", "original": "to be quite frank" },
    { "slang": "tbqh", "original": "to be quite honest" },
    { "slang": "tbss", "original": "too bad so sad" },
    { "slang": "tbt", "original": "throwback thursday" },
    { "slang": "tbtfh", "original": "to be totally freaking honest" },
    { "slang": "tbvh", "original": "to be very honest" },
    { "slang": "tc", "original": "take care" },
    { "slang": "tcfc", "original": "Too Close For Comfort" },
    { "slang": "tcfm", "original": "too cool for me" },
    { "slang": "tcg", "original": "Trading Card Game" },
    { "slang": "tchbo", "original": "Topic creater has been owned" },
    { "slang": "tcial", "original": "The cake is a lie" },
    { "slang": "tcoy", "original": "take care of yourself" },
    { "slang": "tcp", "original": "transmission control protocol" },
    { "slang": "tcp/ip", "original": "transmission control protocol/internet protocol" },
    { "slang": "td2m", "original": "talk dirty to me" },
    { "slang": "tddup", "original": "till death do us part" },
    { "slang": "tdf", "original": "To Die For" },
    { "slang": "tdl", "original": "Too Damn Lazy" },
    { "slang": "tdtm", "original": "Talk Dirty To Me" },
    { "slang": "tdwdtg", "original": "The Devil Went Down To Georgia" },
    { "slang": "te", "original": "Team effort" },
    { "slang": "teh", "original": "the" },
    { "slang": "teotwawki", "original": "the end of the world as we know it" },
    { "slang": "terd", "original": "shit" },
    { "slang": "tf2", "original": "Team Fortress 2" },
    { "slang": "tfa", "original": "the fucking article" },
    { "slang": "tfb", "original": "time for bed" },
    { "slang": "tfbundy", "original": "totaly fucked but unfortunatly not dead yet" },
    { "slang": "tfc", "original": "Team Fortress Classic" },
    { "slang": "tfd", "original": "total fucking disaster" },
    { "slang": "tff", "original": "That's Fucking Funny" },
    { "slang": "tfft", "original": "thank fuck for that" },
    { "slang": "tffw", "original": "Too funny for words" },
    { "slang": "tfh", "original": "Thread from hell" },
    { "slang": "tfic", "original": "Tongue Firmly In Cheek" },
    { "slang": "tfiik", "original": "the fuck if i know" },
    { "slang": "tfl", "original": "Thanks For Looking" },
    { "slang": "tfln", "original": "thanx for last night" },
    { "slang": "tfm", "original": "too fucking much" },
    { "slang": "tfs", "original": "thanks for sharing" },
    { "slang": "tfta", "original": "thanks for the add" },
    { "slang": "tfti", "original": "thanks for the information" },
    { "slang": "tfu", "original": "that's fucked up" },
    { "slang": "tfu2baw", "original": "time for you to buy a watch" },
    { "slang": "tg", "original": "thank god" },
    { "slang": "tgfe", "original": "together forever" },
    { "slang": "tgfitw", "original": "The Greatest Fans In The World" },
    { "slang": "tgft", "original": "thank god for that" },
    { "slang": "tgfu", "original": "too good for you" },
    { "slang": "tgfuap", "original": "thank god for unanswered prayers" },
    { "slang": "tghig", "original": "thank god husband is gone" },
    { "slang": "tgif", "original": "thank god it's friday" },
    { "slang": "tgiff", "original": "thank god its fucking Friday" },
    { "slang": "tgis", "original": "thank god it's saturday" },
    { "slang": "tgiwjo", "original": "Thank God It Was Just Once" },
    { "slang": "tgsttttptct", "original": "thank God someone took the time to put this crap together" },
    { "slang": "tgtbt", "original": "Too Good To Be True" },
    { "slang": "tgwig", "original": "thank god wife is gone" },
    { "slang": "tgws", "original": "that goes without saying" },
    { "slang": "th@", "original": "that" },
    { "slang": "tha", "original": "the" },
    { "slang": "thankies", "original": "Thank You" },
    { "slang": "thankx", "original": "thank you" },
    { "slang": "thanq", "original": "thank you" },
    { "slang": "thanx", "original": "thank you" },
    { "slang": "thar", "original": "there" },
    { "slang": "thatz", "original": "that's" },
    { "slang": "thku", "original": "thank you" },
    { "slang": "thn", "original": "then" },
    { "slang": "thnk", "original": "think" },
    { "slang": "thnx", "original": "thanks" },
    { "slang": "tho", "original": "though" },
    { "slang": "thot", "original": "the hoe of today" },
    { "slang": "thr", "original": "there" },
    { "slang": "thr4", "original": "therefore" },
    { "slang": "thru", "original": "through" },
    { "slang": "tht", "original": "that" },
    { "slang": "thwdi", "original": "thats how we do it" },
    { "slang": "thwy", "original": "the hell with you!" },
    { "slang": "thx", "original": "thank you" },
    { "slang": "thxx", "original": "thanks" },
    { "slang": "thz", "original": "thank you" },
    { "slang": "ti2o", "original": "that is too obious" },
    { "slang": "tia", "original": "thanks in advance" },
    { "slang": "tiafayh", "original": "Thanks in advance for all your help" },
    { "slang": "tiai", "original": "take it all in" },
    { "slang": "tias", "original": "Try It And See" },
    { "slang": "tiatwtcc", "original": "this is a trap word to catch copiers" },
    { "slang": "tif", "original": "this is fun" },
    { "slang": "tif2m", "original": "this is fucking 2 much" },
    { "slang": "tifs", "original": "this is funny shit" },
    { "slang": "tifu", "original": "that is fucked up" },
    { "slang": "tigger", "original": "tiger" },
    { "slang": "tiic", "original": "the idiots in control" },
    { "slang": "til", "original": "until" },
    { "slang": "tilf", "original": "Teenager I'd Like To Fuck" },
    { "slang": "tinf", "original": "this is not fair" },
    { "slang": "tinla", "original": "this is not legal advice" },
    { "slang": "tinstaafl", "original": "There Is No Such Thing As A Free Lunch" },
    { "slang": "tioli", "original": "take it or leave it" },
    { "slang": "tis", "original": "is" },
    { "slang": "tisc", "original": "that is so cool" },
    { "slang": "tisfu", "original": "that is so fucked up" },
    { "slang": "tisg", "original": "this is so gay" },
    { "slang": "tisly", "original": "that is so last year" },
    { "slang": "tisnf", "original": "that is so not fair" },
    { "slang": "tiss", "original": "This is some shit" },
    { "slang": "tisw", "original": "that is so wrong" },
    { "slang": "tiw", "original": "teacher is watching" },
    { "slang": "tix", "original": "tickets" },
    { "slang": "tjb", "original": "thats just boring" },
    { "slang": "tk", "original": "team kill" },
    { "slang": "tk2ul", "original": "talk to you later" },
    { "slang": "tkd", "original": "Tae Kwon Do" },
    { "slang": "tker", "original": "team killer" },
    { "slang": "tks", "original": "thanks" },
    { "slang": "tku", "original": "thank you" },
    { "slang": "tl", "original": "Tough Luck" },
    { "slang": "tl,dr", "original": "Too long; didn't read" },
    { "slang": "tl8r", "original": "talk later" },
    { "slang": "tl:dr", "original": "Too Long; Didn't Read" },
    { "slang": "tl; dr", "original": "To Long; Didn't read" },
    { "slang": "tl;dr", "original": "too long; didn't read" },
    { "slang": "tla", "original": "Three Letter Acronym" },
    { "slang": "tlc", "original": "tender loving care" },
    { "slang": "tld", "original": "told" },
    { "slang": "tldnr", "original": "too long, did not read" },
    { "slang": "tldr", "original": "Too long, didn't read." },
    { "slang": "tlgo", "original": "The list goes on" },
    { "slang": "tliwwv", "original": "this link is worthless without video" },
    { "slang": "tlk", "original": "talk" },
    { "slang": "tlk2me", "original": "talk to me" },
    { "slang": "tlk2ul8r", "original": "talk to you later" },
    { "slang": "tlkin", "original": "talking" },
    { "slang": "tlkn", "original": "talking" },
    { "slang": "tltpr", "original": "Too long to proof read." },
    { "slang": "tlyk", "original": "to let you know" },
    { "slang": "tma", "original": "take my advice" },
    { "slang": "tmaai", "original": "tell me all about it" },
    { "slang": "tmai", "original": "tell me about it" },
    { "slang": "tmbi", "original": "tell me about it" },
    { "slang": "tmi", "original": "too much information" },
    { "slang": "tmk", "original": "to my knowledge" },
    { "slang": "tml", "original": "tell me later" },
    { "slang": "tmmrw", "original": "tomorrow" },
    { "slang": "tmnt", "original": "teenage mutant ninja turtles" },
    { "slang": "tmo", "original": "take me out" },
    { "slang": "tmoro", "original": "tomorrow" },
    { "slang": "tmoz", "original": "tomorrow" },
    { "slang": "tmp", "original": "Text my phone" },
    { "slang": "tmr", "original": "tomorrow" },
    { "slang": "tmr@ia", "original": "the monkeys are at it again" },
    { "slang": "tmrrw", "original": "tomorrow" },
    { "slang": "tmrw", "original": "Tomorrow" },
    { "slang": "tmrz", "original": "tomorrow" },
    { "slang": "tms", "original": "that makes sense" },
    { "slang": "tmsaisti", "original": "That's my story and I'm sticking to it." },
    { "slang": "tmsg", "original": "tell me something good" },
    { "slang": "tmsidk", "original": "tell me somthing I don't know" },
    { "slang": "tmth", "original": "too much to handle" },
    { "slang": "tmtmo", "original": "text me tomorrow" },
    { "slang": "tmtoyh", "original": "Too Much Time On Your Hands" },
    { "slang": "tmtt", "original": "tell me the truth" },
    { "slang": "tmw", "original": "Too much work" },
    { "slang": "tmwfi", "original": "Take my word for it" },
    { "slang": "tmz", "original": "tomorrow" },
    { "slang": "tn1", "original": "trust no-one" },
    { "slang": "tna", "original": "tits and ass" },
    { "slang": "tnc", "original": "totally not cool" },
    { "slang": "tnf", "original": "That's Not Funny" },
    { "slang": "tnlnsl", "original": "Took nothing left nothing signed log" },
    { "slang": "tnx", "original": "thanks" },
    { "slang": "tnxz", "original": "thanks" },
    { "slang": "tob", "original": "teacher over back" },
    { "slang": "tofy", "original": "Thinking of You" },
    { "slang": "toh", "original": "typing one handed" },
    { "slang": "tok", "original": "That's ok" },
    { "slang": "tok2ul8r", "original": "i'll talk to you later" },
    { "slang": "tolol", "original": "thinking of laughing out loud" },
    { "slang": "tomm", "original": "tommorow" },
    { "slang": "tomoro", "original": "tommorrow" },
    { "slang": "tomoz", "original": "tomorrow" },
    { "slang": "tonite", "original": "tonight" },
    { "slang": "tos", "original": "terms of service" },
    { "slang": "totes", "original": "totally" },
    { "slang": "totl", "original": "total" },
    { "slang": "totm", "original": "top of the morning" },
    { "slang": "totp", "original": "talking on the phone" },
    { "slang": "totpd", "original": "top of the page dance" },
    { "slang": "tou", "original": "thinking of you" },
    { "slang": "toya", "original": "thinking of you always" },
    { "slang": "tp", "original": "toilet paper" },
    { "slang": "tpb", "original": "the pirate bay" },
    { "slang": "tpiwwp", "original": "this post is worthless without pictures" },
    { "slang": "tps", "original": "test procedure specification" },
    { "slang": "tptb", "original": "the powers that be" },
    { "slang": "tq", "original": "Thank You" },
    { "slang": "trani", "original": "transexual" },
    { "slang": "tranny", "original": "Transexual" },
    { "slang": "trble", "original": "trouble" },
    { "slang": "trd", "original": "tired" },
    { "slang": "trnsl8", "original": "translate" },
    { "slang": "trnsltr", "original": "translator" },
    { "slang": "troll", "original": "person who diliberately stirs up trouble" },
    { "slang": "tru", "original": "true" },
    { "slang": "ts", "original": "talking shit" },
    { "slang": "tsc", "original": "that's so cool" },
    { "slang": "tsff", "original": "thats so fuckin funny" },
    { "slang": "tsig", "original": "that site is gay" },
    { "slang": "tsnf", "original": "that's so not fair" },
    { "slang": "tss", "original": "That's so sweet" },
    { "slang": "tstoac", "original": "too stupid to own a computer" },
    { "slang": "tswc", "original": "tell someone who cares" },
    { "slang": "tt4n", "original": "ta ta for now" },
    { "slang": "ttbc", "original": "Try to be cool" },
    { "slang": "ttbomk", "original": "to the best o fmy knowledge" },
    { "slang": "ttc", "original": "text the cell" },
    { "slang": "ttfaf", "original": "Through the Fire and Flames" },
    { "slang": "ttfn", "original": "ta ta for now" },
    { "slang": "tthb", "original": "try to hurry back" },
    { "slang": "ttihlic", "original": "try to imagine how little i care" },
    { "slang": "ttiuwiop", "original": "this thread is useless without pics" },
    { "slang": "ttiuwop", "original": "this thread is useless without pics" },
    { "slang": "ttiuwp", "original": "This Thread Is Useless Without Pictures" },
    { "slang": "ttiwwop", "original": "This thread is worthless without pics" },
    { "slang": "ttiwwp", "original": "this thread is worthless without pics" },
    { "slang": "ttl", "original": "total" },
    { "slang": "ttlly", "original": "totally" },
    { "slang": "ttly", "original": "totally" },
    { "slang": "ttm", "original": "talk to me" },
    { "slang": "ttml", "original": "talk to me later" },
    { "slang": "ttmn", "original": "Talk to me now" },
    { "slang": "ttms", "original": "talking to myself" },
    { "slang": "ttr", "original": "time to run" },
    { "slang": "ttrf", "original": "That's the rules, fucker" },
    { "slang": "tts", "original": "text to speech" },
    { "slang": "ttt", "original": "to the top" },
    { "slang": "ttth", "original": "Talk To The Hand" },
    { "slang": "tttt", "original": "to tell the truth" },
    { "slang": "ttul", "original": "Talk To You Later" },
    { "slang": "ttul8r", "original": "Talk to you later" },
    { "slang": "ttus", "original": "talk to you soon" },
    { "slang": "ttut", "original": "Talk to you Tomorrow" },
    { "slang": "ttutt", "original": "to tell you the truth" },
    { "slang": "tty", "original": "Talk to You" },
    { "slang": "ttyab", "original": "Talk to you after breakfast" },
    { "slang": "ttyad", "original": "Talk to you after Dinner" },
    { "slang": "ttyal", "original": "Talk to you after lunch" },
    { "slang": "ttyas", "original": "talk to you at school" },
    { "slang": "ttyiam", "original": "talk to you in a minute" },
    { "slang": "ttyitm", "original": "talk to you in the morning" },
    { "slang": "ttyl", "original": "talk to you later" },
    { "slang": "ttyl8r", "original": "talk to you later" },
    { "slang": "ttylo", "original": "talk to you later on" },
    { "slang": "ttylt", "original": "talk to you later today" },
    { "slang": "ttyn", "original": "talk to you never" },
    { "slang": "ttyna", "original": "talk to you never again" },
    { "slang": "ttynl", "original": "talk to you never loser" },
    { "slang": "ttynw", "original": "talk to you next week" },
    { "slang": "ttyo", "original": "talk to you online" },
    { "slang": "ttyob", "original": "tend to your own business" },
    { "slang": "ttyotp", "original": "talk to you on the phone" },
    { "slang": "ttyrs", "original": "talk to you really soon" },
    { "slang": "ttys", "original": "talk to you soon" },
    { "slang": "ttyt", "original": "talk to you tomorrow" },
    { "slang": "ttytm", "original": "talk to you tomorrow" },
    { "slang": "ttytt", "original": "to tell you the truth" },
    { "slang": "ttyw", "original": "talk to you whenever" },
    { "slang": "ttywl", "original": "Talk to you way later" },
    { "slang": "tu", "original": "thank you" },
    { "slang": "tuff", "original": "tough" },
    { "slang": "tuh", "original": "to" },
    { "slang": "tut", "original": "take your time" },
    { "slang": "tuvm", "original": "thank you very much" },
    { "slang": "tv", "original": "television" },
    { "slang": "tvm", "original": "thanks very much" },
    { "slang": "tw", "original": "Teacher Watching" },
    { "slang": "twajs", "original": "That was a joke, son." },
    { "slang": "twat", "original": "vagina" },
    { "slang": "twbc", "original": "that would be cool" },
    { "slang": "twdah", "original": "that was dumb as hell" },
    { "slang": "twf", "original": "That was funny" },
    { "slang": "twfaf", "original": "thats what friends are for" },
    { "slang": "twg", "original": "That was great" },
    { "slang": "twi", "original": "Texting While Intoxicated" },
    { "slang": "twis", "original": "that's what I said" },
    { "slang": "twoh", "original": "typing with one hand" },
    { "slang": "tws2wa", "original": "That was so 2 weeks ago" },
    { "slang": "twss", "original": "That's what she said" },
    { "slang": "twsy", "original": "That was so yeterday" },
    { "slang": "twttr", "original": "twitter" },
    { "slang": "twvsoy", "original": "that was very stupid of you" },
    { "slang": "twyl", "original": "Talk With You Later" },
    { "slang": "twys", "original": "Talk With You Soon" },
    { "slang": "tx", "original": "thanks" },
    { "slang": "txs", "original": "thanks" },
    { "slang": "txt", "original": "text" },
    { "slang": "txting", "original": "texting" },
    { "slang": "txtyl", "original": "text you later" },
    { "slang": "ty", "original": "thank you" },
    { "slang": "tyclos", "original": "turn your CAPS LOCK off, stupid" },
    { "slang": "tyfi", "original": "Thank You for invite" },
    { "slang": "tyfn", "original": "thank you for nothing" },
    { "slang": "tyfyc", "original": "Thank You For Your Comment" },
    { "slang": "tyfyt", "original": "Thank you for your time" },
    { "slang": "tyl", "original": "text you later" },
    { "slang": "tym", "original": "time" },
    { "slang": "tyme", "original": "time" },
    { "slang": "typ", "original": "thank you partner" },
    { "slang": "typo", "original": "typing mistake" },
    { "slang": "tyred", "original": "tired" },
    { "slang": "tys", "original": "Told You So" },
    { "slang": "tysfm", "original": "thank you so fucking much" },
    { "slang": "tysm", "original": "thank you so much" },
    { "slang": "tysvm", "original": "thank you so very much" },
    { "slang": "tyt", "original": "take your time" },
    { "slang": "tyto", "original": "take your top off" },
    { "slang": "tyty", "original": "thank you thank you" },
    { "slang": "tyvm", "original": "Thank You Very Much" },
    { "slang": "tyvvm", "original": "thank you very very much" }
  ]
}
