module.exports = {
  range: ['u', 'v', 'w', 'x', 'y', 'z'],
  words: [
    { "slang": "u", "original": "you" },
    { "slang": "u iz a 304", "original": "you is a hoe" },
    { "slang": "u'd", "original": "you would" },
    { "slang": "u'll", "original": "you will" },
    { "slang": "u'r", "original": "you're" },
    { "slang": "u'v", "original": "you have" },
    { "slang": "u've", "original": "You've" },
    { "slang": "u/l", "original": "upload" },
    { "slang": "u/n", "original": "username" },
    { "slang": "u2", "original": "You too" },
    { "slang": "u2u", "original": "up to you" },
    { "slang": "u4i", "original": "up for it" },
    { "slang": "ua", "original": "user agreement" },
    { "slang": "uaaaa", "original": "Universal Association Against Acronym Abuse" },
    { "slang": "uat", "original": "User Acceptance Testing" },
    { "slang": "uayor", "original": "Use At Your Own Risk" },
    { "slang": "ub3r", "original": "super" },
    { "slang": "uber", "original": "over" },
    { "slang": "uctaodnt", "original": "you can't teach an old dog new tricks" },
    { "slang": "udc", "original": "you don't care" },
    { "slang": "udek", "original": "you don't even know" },
    { "slang": "uds", "original": "you dumb shit" },
    { "slang": "udwk", "original": "you don't want to know" },
    { "slang": "udy", "original": "you done yet" },
    { "slang": "ufab", "original": "ugly fat ass bitch" },
    { "slang": "ufia", "original": "unsolicited finger in the anus" },
    { "slang": "UFIC", "original": "Unsolicited Finger in Chili" },
    { "slang": "ufmf", "original": "you funny mother fucker" },
    { "slang": "ufr", "original": "Upon further review" },
    { "slang": "ugba", "original": "you gay bitch ass" },
    { "slang": "ugtr", "original": "you got that right" },
    { "slang": "uhab", "original": "you have a blog" },
    { "slang": "uhems", "original": "you hardly ever make sense" },
    { "slang": "ui", "original": "User Interface" },
    { "slang": "ujds", "original": "u just did shit" },
    { "slang": "ukr", "original": "You know right" },
    { "slang": "ukwim", "original": "you know what i mean" },
    { "slang": "ul", "original": "unlucky" },
    { "slang": "ulbom", "original": "you looked better on myspace" },
    { "slang": "umfriend", "original": "sexual partner" },
    { "slang": "un2bo", "original": "you need to back off" },
    { "slang": "un4rtun8ly", "original": "unfortunately" },
    { "slang": "unt", "original": "until next time" },
    { "slang": "uom", "original": "You owe me" },
    { "slang": "upcia", "original": "unsolicited pool cue in anus" },
    { "slang": "upia", "original": "unsolicited pencil in anus" },
    { "slang": "upmo", "original": "You piss me off" },
    { "slang": "upos", "original": "you piece of shit" },
    { "slang": "upw", "original": "unidentified party wound" },
    { "slang": "ur", "original": "your" },
    { "slang": "ur2g", "original": "you are too good" },
    { "slang": "ur6c", "original": "you're sexy" },
    { "slang": "ura", "original": "you are a" },
    { "slang": "uradrk", "original": "you're a dork" },
    { "slang": "urafb", "original": "you are a fucking bitch" },
    { "slang": "uraqt", "original": "you are a cutie" },
    { "slang": "urcrzy", "original": "you are crazy" },
    { "slang": "ure", "original": "you are" },
    { "slang": "urg", "original": "you are gay" },
    { "slang": "urht", "original": "you're hot" },
    { "slang": "url8", "original": "you are late" },
    { "slang": "urms", "original": "you rock my socks" },
    { "slang": "urmw", "original": "you are my world" },
    { "slang": "urnc", "original": "you are not cool" },
    { "slang": "urs", "original": "yours" },
    { "slang": "ursab", "original": "you are such a bitch" },
    { "slang": "ursdf", "original": "you are so damn fine" },
    { "slang": "ursg", "original": "you are so gay" },
    { "slang": "ursh", "original": "you are so hot" },
    { "slang": "urssb", "original": "you are so sexy baby" },
    { "slang": "urstpid", "original": "you are stupid" },
    { "slang": "urstu", "original": "you are stupid" },
    { "slang": "urtb", "original": "you are the best" },
    { "slang": "urtbitw", "original": "You are the best in the world!" },
    { "slang": "urtrd", "original": "you retard" },
    { "slang": "urtw", "original": "you are the worst" },
    { "slang": "urw", "original": "you are weird" },
    { "slang": "uryyfm", "original": "you are too wise for me" },
    { "slang": "usck", "original": "you suck" },
    { "slang": "usd", "original": "United States Dollar" },
    { "slang": "ussr", "original": "The Union of Soviet Socialist Republics" },
    { "slang": "usuk", "original": "You Suck" },
    { "slang": "usux", "original": "you suck" },
    { "slang": "ut", "original": "unreal tournament" },
    { "slang": "ut", "original": "you there" },
    { "slang": "uta", "original": "up the ass" },
    { "slang": "utfs", "original": "Use the fucking search" },
    { "slang": "utfse", "original": "use the fucking search engine" },
    { "slang": "utm", "original": "you tell me" },
    { "slang": "uttm", "original": " you talking to me?" },
    { "slang": "utube", "original": "youtube" },
    { "slang": "utw", "original": "used to work" },
    { "slang": "uty", "original": "it's up to you" },
    { "slang": "uve", "original": "You've" },
    { "slang": "uvgtbsm", "original": "you have got to be shiting me" },
    { "slang": "uw", "original": "you're welcome" },
    { "slang": "uwc", "original": "you are welcome" },
    { "slang": "uya", "original": "up your ass" },
    { "slang": "uyab", "original": "up your ass bitch" },
    { "slang": "v4g1n4", "original": "vagina" },
    { "slang": "vag", "original": "vagina" },
    { "slang": "vajayjay", "original": "vagina" },
    { "slang": "vb", "original": "visual basic" },
    { "slang": "vbeg", "original": "very big evil grin" },
    { "slang": "vbg", "original": "very big grin" },
    { "slang": "vf", "original": "very funny" },
    { "slang": "vfe", "original": "Virgins 4 ever" },
    { "slang": "vff", "original": "Verry Fucking Funny" },
    { "slang": "vfm", "original": "value for money" },
    { "slang": "vgg", "original": "very good game" },
    { "slang": "vgh", "original": "Very good hand" },
    { "slang": "vgl", "original": "very good looking" },
    { "slang": "vgn", "original": "Video Game Nerd" },
    { "slang": "vid", "original": "Video" },
    { "slang": "vids", "original": "Videos" },
    { "slang": "vip", "original": "very important person" },
    { "slang": "vleo", "original": "Very Low Earth Orbit" },
    { "slang": "vlog", "original": "video log" },
    { "slang": "vn", "original": "very nice" },
    { "slang": "vnc", "original": "Virtual Network Computing" },
    { "slang": "vnh", "original": "Very nice hand" },
    { "slang": "voip", "original": "voice over ip" },
    { "slang": "vrsty", "original": "Varsity" },
    { "slang": "vry", "original": "very" },
    { "slang": "vs", "original": "versus" },
    { "slang": "vwd", "original": "very well done" },
    { "slang": "vweg", "original": "very wicked evil grin" },
    { "slang": "vzit", "original": "visit" },
    { "slang": "vzn", "original": "verizon" },
    { "slang": "w'sup", "original": "what's up" },
    { "slang": "w.b.s.", "original": "Write Back Soon" },
    { "slang": "w.e", "original": "Whatever" },
    { "slang": "w.e.", "original": "whatever" },
    { "slang": "w.o.w", "original": "World of Warcraft" },
    { "slang": "w.o.w.", "original": "world of warcraft" },
    { "slang": "w/", "original": "with" },
    { "slang": "w/b", "original": "write back" },
    { "slang": "w/e", "original": "whatever" },
    { "slang": "w/end", "original": "weekend" },
    { "slang": "w/eva", "original": "whatever" },
    { "slang": "w/o", "original": "with out" },
    { "slang": "w/out", "original": "without" },
    { "slang": "w/u", "original": "with you" },
    { "slang": "w00t", "original": "woohoo" },
    { "slang": "w012d", "original": "word" },
    { "slang": "w2d", "original": "what to do" },
    { "slang": "w2f", "original": "want to fuck" },
    { "slang": "w2g", "original": "Way to go" },
    { "slang": "w2ho", "original": "want to hang out" },
    { "slang": "w2m", "original": "want to meet" },
    { "slang": "w33d", "original": "weed" },
    { "slang": "w8", "original": "wait" },
    { "slang": "w8am", "original": "wait a minute" },
    { "slang": "w8ing", "original": "waiting" },
    { "slang": "w8t4me", "original": "wait for me" },
    { "slang": "w8ter", "original": "waiter" },
    { "slang": "w911", "original": "Wife in room" },
    { "slang": "wab", "original": "what a bitch" },
    { "slang": "wad", "original": "without a doubt" },
    { "slang": "wad ^", "original": "what's up?" },
    { "slang": "wadr", "original": "with all due respect" },
    { "slang": "wadzup", "original": "What's up?" },
    { "slang": "waf", "original": "weird as fuck" },
    { "slang": "wafda", "original": "What a Fucking Dumb Ass" },
    { "slang": "wafl", "original": "what a fucking loser" },
    { "slang": "wafm", "original": "wait a fucking minute" },
    { "slang": "wafn", "original": "what a fucken noob" },
    { "slang": "wai", "original": "what an idiot" },
    { "slang": "waloc", "original": "what a load of crap" },
    { "slang": "walstib", "original": "what a long strange trip it's been" },
    { "slang": "wam", "original": "wait a minute" },
    { "slang": "wamh", "original": "with all my heart" },
    { "slang": "wan2tlk", "original": "Want to talk" },
    { "slang": "wana", "original": "want to" },
    { "slang": "wanafuk", "original": "wanna fuck" },
    { "slang": "wanker", "original": "masturbater" },
    { "slang": "wanking", "original": "Masturbating" },
    { "slang": "wanna", "original": "want to" },
    { "slang": "wansta", "original": "wanna be ganster" },
    { "slang": "warez", "original": "illegally obtained software" },
    { "slang": "wassup", "original": "what's up?" },
    { "slang": "wasup", "original": "What's Up" },
    { "slang": "was^", "original": "What's Up" },
    { "slang": "wat", "original": "what" },
    { "slang": "wat's^", "original": "Whats Up" },
    { "slang": "watcha", "original": "what are you" },
    { "slang": "watev", "original": "whatever" },
    { "slang": "wateva", "original": "whatever " },
    { "slang": "watevr", "original": "whatever" },
    { "slang": "watevs", "original": "whatever" },
    { "slang": "wats", "original": "whats" },
    { "slang": "wats ^", "original": "whats up" },
    { "slang": "wats^", "original": "what's up?" },
    { "slang": "watz ^", "original": "What's up" },
    { "slang": "wau", "original": "what about you" },
    { "slang": "waug", "original": "Where are you going" },
    { "slang": "wauw", "original": "what are you wearing" },
    { "slang": "wau^2", "original": "what are you up to?" },
    { "slang": "waw", "original": "what a whore" },
    { "slang": "waycb", "original": "when are you coming back" },
    { "slang": "wayd", "original": "what are you doing" },
    { "slang": "waygow", "original": "who are you going out with" },
    { "slang": "wayh", "original": "why are you here" },
    { "slang": "wayn", "original": "Where Are You Now" },
    { "slang": "waysttm", "original": "why are you still talking to me" },
    { "slang": "waysw", "original": "Why are you so weird" },
    { "slang": "wayt", "original": "What are you thinking?" },
    { "slang": "wayta", "original": "what are you talking about" },
    { "slang": "wayut", "original": "what are you up to" },
    { "slang": "waz", "original": "what is" },
    { "slang": "waz ^", "original": "what's up" },
    { "slang": "wazz", "original": "what's" },
    { "slang": "wazza", "original": "what's up" },
    { "slang": "wazzed", "original": "drunk" },
    { "slang": "wazzup", "original": "what's up" },
    { "slang": "waz^", "original": "what's up?" },
    { "slang": "wb", "original": "welcome back" },
    { "slang": "wbagnfarb", "original": "would be a good name for a rock band" },
    { "slang": "wbb", "original": "will be back" },
    { "slang": "wbbs", "original": "will be back soon" },
    { "slang": "wbp", "original": "Welcome Back Partner" },
    { "slang": "wbrb", "original": "Will be right back" },
    { "slang": "wbs", "original": "write back soon" },
    { "slang": "wbu", "original": "what about you" },
    { "slang": "wby", "original": "what about you" },
    { "slang": "wc", "original": "who cares" },
    { "slang": "wc3", "original": "Warcraft III" },
    { "slang": "wcutm", "original": "what can you tell me" },
    { "slang": "wcw", "original": "webcam whore" },
    { "slang": "wd", "original": "well done" },
    { "slang": "wdf", "original": "Worth Dying For" },
    { "slang": "wdhlm", "original": "why doesnt he love me?" },
    { "slang": "wdidn", "original": "what do i do now" },
    { "slang": "wdim", "original": "What Did I miss" },
    { "slang": "wdtm", "original": "what does that mean" },
    { "slang": "wduc", "original": "what do you care" },
    { "slang": "wdum", "original": "what do  you mean" },
    { "slang": "wdus", "original": "What Did You Say" },
    { "slang": "wdut", "original": "what do you think?" },
    { "slang": "wdutom", "original": "what do you think of me" },
    { "slang": "wduw", "original": "what do you want" },
    { "slang": "wduwta", "original": "what do you wanna talk about" },
    { "slang": "wduwtta", "original": "what do you want to talk about" },
    { "slang": "wdwdn", "original": "what do we do now" },
    { "slang": "wdwgw", "original": "where did we go wrong" },
    { "slang": "wdya", "original": "why do you ask" },
    { "slang": "wdydt", "original": "why do you do that" },
    { "slang": "wdye", "original": "What do you expect" },
    { "slang": "wdyl", "original": "who do you like" },
    { "slang": "wdym", "original": "what do you mean" },
    { "slang": "wdys", "original": "What did you say" },
    { "slang": "wdyt", "original": "what do you think" },
    { "slang": "wdytia", "original": "who do you think i am?" },
    { "slang": "wdyw", "original": "what do you want" },
    { "slang": "wdywd", "original": "what do you want to do?" },
    { "slang": "wdywtd", "original": "what do you want to do" },
    { "slang": "wdywtdt", "original": "Why Do You Want To Do That?" },
    { "slang": "wdywtta", "original": "what do you want to talk about" },
    { "slang": "webby", "original": "webcam" },
    { "slang": "weg", "original": "wicked evil grin" },
    { "slang": "welc", "original": "welcome" },
    { "slang": "wen", "original": "when" },
    { "slang": "werkz", "original": "works" },
    { "slang": "wev", "original": "Whatever" },
    { "slang": "weve", "original": "what ever" },
    { "slang": "wevr", "original": "whatever" },
    { "slang": "wfh", "original": "Working From Home" },
    { "slang": "wfhw", "original": "what's for homework" },
    { "slang": "wfm", "original": "Works For Me" },
    { "slang": "wfyb", "original": "whatever floats your boat" },
    { "slang": "wg", "original": "wicked gril" },
    { "slang": "wgac", "original": "who gives a crap" },
    { "slang": "wgaf", "original": "Who gives a fuck" },
    { "slang": "wgas", "original": "who gives a shit" },
    { "slang": "wgasa", "original": "who gives a shit anyway" },
    { "slang": "wgo", "original": "what's going on" },
    { "slang": "wgph2", "original": "Want to go play Halo 2?" },
    { "slang": "wha", "original": "what?" },
    { "slang": "whaddya", "original": "what do you" },
    { "slang": "whaletail", "original": "thong" },
    { "slang": "whatcha", "original": "what are you" },
    { "slang": "whatev", "original": "whatever" },
    { "slang": "whatevs", "original": "whatever" },
    { "slang": "whats ^", "original": "whats up" },
    { "slang": "what^", "original": "what's up?" },
    { "slang": "whenevs", "original": "whenever" },
    { "slang": "whevah", "original": "where ever" },
    { "slang": "whever", "original": "whatever" },
    { "slang": "whf", "original": "Wanna have fun?" },
    { "slang": "whit", "original": "with" },
    { "slang": "whodi", "original": "friend" },
    { "slang": "whr", "original": "where" },
    { "slang": "whs", "original": "wanna have sex" },
    { "slang": "wht", "original": "What" },
    { "slang": "whteva", "original": "what ever" },
    { "slang": "whteve", "original": "whatever" },
    { "slang": "whtever", "original": "whatever" },
    { "slang": "whtevr", "original": "whatever" },
    { "slang": "whtvr", "original": "whatever" },
    { "slang": "wht^", "original": "what up" },
    { "slang": "whubu2", "original": "what have you been up to" },
    { "slang": "whubut", "original": "what have you been up to" },
    { "slang": "whut", "original": "what" },
    { "slang": "whyb", "original": "where have you been" },
    { "slang": "whyd", "original": "What Have You Done" },
    { "slang": "wid", "original": "with" },
    { "slang": "widout", "original": "without" },
    { "slang": "wieu2", "original": "What Is Everyone Up To" },
    { "slang": "wif", "original": "With" },
    { "slang": "wiid", "original": "what if i did" },
    { "slang": "wilco", "original": "will comply" },
    { "slang": "winnar", "original": "winner" },
    { "slang": "wio", "original": "without" },
    { "slang": "wip", "original": "Work In progress" },
    { "slang": "wit", "original": "with" },
    { "slang": "witcha", "original": "with you" },
    { "slang": "witfp", "original": "What is the fucking point" },
    { "slang": "witu", "original": "with you" },
    { "slang": "witw", "original": "what in the world" },
    { "slang": "witwct", "original": "What is the world coming too" },
    { "slang": "witwu", "original": "who is there with you" },
    { "slang": "witwwyt", "original": "what in the world were you thinking" },
    { "slang": "wiu", "original": "What is up?" },
    { "slang": "wiuwu", "original": "what is up with you" },
    { "slang": "wiv", "original": "with" },
    { "slang": "wiw", "original": "wife is watching" },
    { "slang": "wiwhu", "original": "wish I was holding you" },
    { "slang": "wiwt", "original": "wish i was there " },
    { "slang": "wiyp", "original": "what is your problem" },
    { "slang": "wjwd", "original": "What Jesus Would Do" },
    { "slang": "wk", "original": "week" },
    { "slang": "wkd", "original": "wicked" },
    { "slang": "wkend", "original": "weekend" },
    { "slang": "wl", "original": "will" },
    { "slang": "wlc", "original": "welcome" },
    { "slang": "wlcb", "original": "welcome back" },
    { "slang": "wlcm", "original": "welcome" },
    { "slang": "wld", "original": "would" },
    { "slang": "wlkd", "original": "walked" },
    { "slang": "wlos", "original": "wife looking over Shoulder" },
    { "slang": "wltm", "original": "would like to meet" },
    { "slang": "wmao", "original": "working my ass off" },
    { "slang": "wmd", "original": "Weapons Of Mass Destruction" },
    { "slang": "wmgl", "original": "wish me good luck" },
    { "slang": "wml", "original": "Wish Me Luck" },
    { "slang": "wmts", "original": "we must talk soon" },
    { "slang": "wmyb", "original": "What Makes You Beautiful" },
    { "slang": "wn", "original": "when" },
    { "slang": "wna", "original": "want to" },
    { "slang": "wnkr", "original": "wanker" },
    { "slang": "wnrn", "original": "why not right now" },
    { "slang": "wnt", "original": "want" },
    { "slang": "wntd", "original": "what not to do" },
    { "slang": "woa", "original": "word of advice" },
    { "slang": "woc", "original": "welcome on cam" },
    { "slang": "wochit", "original": "watch it" },
    { "slang": "woe", "original": "what on earth" },
    { "slang": "woft", "original": "Waste of fucking time" },
    { "slang": "wogge", "original": "what on god's green earth?" },
    { "slang": "wogs", "original": "waste of good sperm" },
    { "slang": "wolo", "original": "we only live once" },
    { "slang": "wombat", "original": "waste of money, brains, and time" },
    { "slang": "woot", "original": "woohoo" },
    { "slang": "wos", "original": "Waste of space" },
    { "slang": "wot", "original": "what" },
    { "slang": "wotevs", "original": "whatever" },
    { "slang": "wotv", "original": "What's on Television?" },
    { "slang": "wotw", "original": "word of the week" },
    { "slang": "woum", "original": "what's on your mind" },
    { "slang": "wowzers", "original": "wow" },
    { "slang": "woz", "original": "was" },
    { "slang": "wp", "original": "wrong person" },
    { "slang": "wpe", "original": "worst president ever (Bush)" },
    { "slang": "wrd", "original": "word" },
    { "slang": "wrdo", "original": "weirdo" },
    { "slang": "wrgad", "original": "who really gives a damn" },
    { "slang": "wrgaf", "original": "Who really gives a fuck?" },
    { "slang": "wrk", "original": "work" },
    { "slang": "wrm", "original": "which reminds me" },
    { "slang": "wrng", "original": "wrong" },
    { "slang": "wrt", "original": "with regard to" },
    { "slang": "wrtg", "original": "writing" },
    { "slang": "wrthls", "original": "Worthless" },
    { "slang": "wru", "original": "where are you" },
    { "slang": "wrud", "original": "what are you doing" },
    { "slang": "wruf", "original": "where are you from" },
    { "slang": "wruu2", "original": "what are you up to" },
    { "slang": "wsb", "original": "wanna cyber?" },
    { "slang": "wsf", "original": "we should fuck" },
    { "slang": "wshtf", "original": "when shit hits the fan" },
    { "slang": "wsi", "original": "why should I" },
    { "slang": "wsibt", "original": "when should i be there" },
    { "slang": "wsidi", "original": "Why Should I Do It" },
    { "slang": "wsop", "original": "world series of poker" },
    { "slang": "wswta", "original": "What shall we talk about?" },
    { "slang": "wtaf", "original": "What the actual fuck" },
    { "slang": "wtb", "original": "Want to buy" },
    { "slang": "wtbd", "original": "what's the big deal" },
    { "slang": "wtbh", "original": "What the bloody hell" },
    { "slang": "wtc", "original": "what the crap" },
    { "slang": "wtcf", "original": "what the crazy fuck" },
    { "slang": "wtd", "original": "what the deuce" },
    { "slang": "wtf", "original": "what the fuck" },
    { "slang": "wtfaud", "original": "what the fuck are you doing?" },
    { "slang": "wtfay", "original": "who the fuck are you" },
    { "slang": "wtfayd", "original": "what the fuck are you doing" },
    { "slang": "wtfayt", "original": "why the fuck are you talking" },
    { "slang": "wtfayta", "original": "What the Fuck are you talking about?" },
    { "slang": "wtfb", "original": "what the fuck bitch" },
    { "slang": "wtfbs", "original": "What the fuck bull shit" },
    { "slang": "wtfc", "original": "Who The Fuck Cares" },
    { "slang": "wtfdik", "original": "what the fuck do i know" },
    { "slang": "wtfdum", "original": "what the fuck do you mean" },
    { "slang": "wtfduw", "original": "What the fuck do you want?" },
    { "slang": "wtfdyw", "original": "what the fuck do you want" },
    { "slang": "wtfe", "original": "What The Fuck Ever" },
    { "slang": "wtfever", "original": "what the fuck ever" },
    { "slang": "wtfg", "original": "What the fucking god" },
    { "slang": "wtfh", "original": "what the fucking hell" },
    { "slang": "wtfhb", "original": "what the fucking hell bitch" },
    { "slang": "wtfhwt", "original": "what the fucking hell was that" },
    { "slang": "wtfigo", "original": "what the fuck is going on" },
    { "slang": "wtfigoh", "original": "what the fuck is going on here" },
    { "slang": "wtfit", "original": "what the fuck is that" },
    { "slang": "wtfits", "original": "what the fuck is this shit" },
    { "slang": "wtfiu", "original": "what the fuck is up" },
    { "slang": "wtfiup", "original": "what the fuck is your problem" },
    { "slang": "wtfiuwy", "original": "what the fuck is up with you" },
    { "slang": "wtfiwwu", "original": "what the fuck is wrong with you" },
    { "slang": "wtfiwwy", "original": "what the fuck is wrong with you" },
    { "slang": "wtfiyp", "original": "what the fuck is your problem" },
    { "slang": "wtfm", "original": "what the fuck, mate?" },
    { "slang": "wtfmf", "original": "what the fuck mother fucker" },
    { "slang": "wtfo", "original": "what the fuck over" },
    { "slang": "wtfru", "original": "what the fuck are you" },
    { "slang": "wtfrud", "original": "What the fuck are you doing?" },
    { "slang": "wtfrudng", "original": "what the fuck are you doing" },
    { "slang": "wtfrudoin", "original": "what the fuck are you doing" },
    { "slang": "wtfruo", "original": "what the fuck are you on?" },
    { "slang": "wtfruttd", "original": "what the fuck are you trying to do" },
    { "slang": "wtfs", "original": "what the fucking shit?" },
    { "slang": "wtfuah", "original": "what the fuck you asshole" },
    { "slang": "wtful", "original": "What the fuck you loser" },
    { "slang": "wtfwjd", "original": "what the fuck would jesus do" },
    { "slang": "wtfwt", "original": "what the fuck was that" },
    { "slang": "wtfwtd", "original": "what the fuck was that dude" },
    { "slang": "wtfwtf", "original": "what the fuck was that for?" },
    { "slang": "wtfya", "original": "what the fuck you asshole" },
    { "slang": "wtfyb", "original": "what the fuck you bitch" },
    { "slang": "wtg", "original": "way to go" },
    { "slang": "wtgds", "original": "way to go dumb shit" },
    { "slang": "wtgp", "original": "Want to go Private" },
    { "slang": "wth", "original": "what the heck" },
    { "slang": "wtharud", "original": "what the heck are you doing" },
    { "slang": "wthau", "original": "who the hell are you" },
    { "slang": "wthauwf", "original": "what the hell are you waiting for" },
    { "slang": "wthay", "original": "who the hell are you" },
    { "slang": "wthayd", "original": "what the heck are you doing" },
    { "slang": "wthaydwmgf", "original": "what the hell are you doing with my girlfriend" },
    { "slang": "wthdydt", "original": "why the hell did you do that" },
    { "slang": "wthhyb", "original": "where the hell have you been?" },
    { "slang": "wthigo", "original": "what the hell is going on" },
    { "slang": "wthiwwu", "original": "What the hell is wrong with you" },
    { "slang": "wtho", "original": "want to hang out?" },
    { "slang": "wthru", "original": "Who the heck are you" },
    { "slang": "wthrud", "original": "what the hell are you doing?" },
    { "slang": "wths", "original": "want to have sex" },
    { "slang": "wthswm", "original": "want to have sex with me" },
    { "slang": "wthwt", "original": "what the hell was that?" },
    { "slang": "wthwut", "original": "what the hell were you thinking" },
    { "slang": "wthyi", "original": "what the hell you idiot" },
    { "slang": "wtii", "original": "what time is it" },
    { "slang": "wtiiot", "original": "What time is it over there?" },
    { "slang": "wtityb", "original": "whatever, tell it to your blog" },
    { "slang": "wtly", "original": "Welcome to last year" },
    { "slang": "wtmf", "original": "what the mother fuck" },
    { "slang": "wtmfh", "original": "what the mother fucking hell" },
    { "slang": "wtmi", "original": "way too much information" },
    { "slang": "wtmtr", "original": "what's the matter" },
    { "slang": "wtp", "original": "where's the party" },
    { "slang": "wtrud", "original": "what are you doing" },
    { "slang": "wts", "original": "want to sell" },
    { "slang": "wtt", "original": "want to trade" },
    { "slang": "wttp", "original": "want to trade pictures?" },
    { "slang": "wtv", "original": "Whatever" },
    { "slang": "wtva", "original": "whatever" },
    { "slang": "wtvr", "original": "whatever" },
    { "slang": "wtwm", "original": "what time are we meeting?" },
    { "slang": "wtwr", "original": "well that was random" },
    { "slang": "wu", "original": "what's up" },
    { "slang": "wu", "original": "what's up?" },
    { "slang": "wu2kilu", "original": "want you to know I love you" },
    { "slang": "wub", "original": "love" },
    { "slang": "wubmgf", "original": "Will You Be My Girlfriend?" },
    { "slang": "wubu2", "original": "what you been up to" },
    { "slang": "wubut", "original": "what you been up too" },
    { "slang": "wud", "original": "would" },
    { "slang": "wudev", "original": "Whatever" },
    { "slang": "wudn", "original": "what you doing now" },
    { "slang": "wugowm", "original": "will you go out with me" },
    { "slang": "wula", "original": "what you looking at?" },
    { "slang": "wuld", "original": "would" },
    { "slang": "wuny", "original": "wait until next year" },
    { "slang": "wussup", "original": "What is up?" },
    { "slang": "wut", "original": "what" },
    { "slang": "wutb", "original": "What are you talking about" },
    { "slang": "wutcha", "original": "What are you" },
    { "slang": "wuteva", "original": "whatever" },
    { "slang": "wutevr", "original": "what ever" },
    { "slang": "wuts", "original": "what is" },
    { "slang": "wutup", "original": "What's Up" },
    { "slang": "wuu2", "original": "what you up too" },
    { "slang": "wuu2", "original": "what you up to" },
    { "slang": "wuu22m", "original": "what you up to tomorrow" },
    { "slang": "wuut", "original": "what you up to" },
    { "slang": "wuv", "original": "love" },
    { "slang": "wuwh", "original": "Wish you were here" },
    { "slang": "wuwt", "original": "what's up with that" },
    { "slang": "wuwta", "original": "what do you want to talk about" },
    { "slang": "wuwtab", "original": "what do you want to talk about" },
    { "slang": "wuwtb", "original": "what do you want to talk about" },
    { "slang": "wuwtta", "original": "what you want to talk about" },
    { "slang": "wuwttb", "original": "What you want to talk about " },
    { "slang": "wuwu", "original": "what up with you" },
    { "slang": "wuz", "original": "was" },
    { "slang": "wuza", "original": "what's up" },
    { "slang": "wuzup", "original": "what's up" },
    { "slang": "wwc", "original": "who would care" },
    { "slang": "wwcnd", "original": "What would Chuck Norris do" },
    { "slang": "wwdhd", "original": "What would David Hasselhoff do" },
    { "slang": "wwe", "original": "World Wrestling Entertainment" },
    { "slang": "wwgf", "original": "when we gonna fuck" },
    { "slang": "wwhw", "original": "when where how why" },
    { "slang": "wwikt", "original": "why would i know that" },
    { "slang": "wwjd", "original": "what would jesus do?" },
    { "slang": "wwt", "original": "what was that" },
    { "slang": "wwtf", "original": "what was that for" },
    { "slang": "wwudtm", "original": "what would you do to me" },
    { "slang": "wwut", "original": "what were you thinking" },
    { "slang": "www", "original": "world wide web" },
    { "slang": "wwwy", "original": "what's wrong with you" },
    { "slang": "wwy", "original": "where were you" },
    { "slang": "wwycm", "original": "when will you call me" },
    { "slang": "wwyd", "original": "what would you do?" },
    { "slang": "wwyd2m", "original": "what would you do to me" },
    { "slang": "wwyt", "original": "What were you thinking" },
    { "slang": "wy", "original": "Why?" },
    { "slang": "wyas", "original": "wow you are stupid" },
    { "slang": "wyatb", "original": "wish you all the best" },
    { "slang": "wyauimg", "original": "Why you all up in my grill?" },
    { "slang": "wybts", "original": "were you born this sexy" },
    { "slang": "wyc", "original": "will you come" },
    { "slang": "wycm", "original": "Will You Call Me" },
    { "slang": "wyd", "original": "what are you doing" },
    { "slang": "wyg", "original": "will you go" },
    { "slang": "wygac", "original": "when you get a chance" },
    { "slang": "wygam", "original": "When you get a minute" },
    { "slang": "wygowm", "original": "Will you go out with me" },
    { "slang": "wygwm", "original": "will you go with me" },
    { "slang": "wyhi", "original": "Would You Hit It?" },
    { "slang": "wyhswm", "original": "would you have sex with me" },
    { "slang": "wylion", "original": "whether you like it or not" },
    { "slang": "wyltk", "original": "wouldn't you like to know" },
    { "slang": "wylym", "original": "Watch Your Language Young Man" },
    { "slang": "wym", "original": "What You Mean?" },
    { "slang": "wyn", "original": "What's your name" },
    { "slang": "wyp", "original": "what's your problem?" },
    { "slang": "wypsu", "original": "will you please shut up" },
    { "slang": "wys", "original": "wow you're stupid" },
    { "slang": "wysiayg", "original": "what you see is all you get" },
    { "slang": "wysitwirl", "original": "what you see is totally worthless in real life" },
    { "slang": "wysiwyg", "original": "what you see is what you get" },
    { "slang": "wyw", "original": "What You Want" },
    { "slang": "wywh", "original": "wish you were here" },
    { "slang": "wywo", "original": "while you were out" },
    { "slang": "w\\e", "original": "whatever" },
    { "slang": "txtms", "original": "text me soon" },
    { "slang": "x treme", "original": "extreme" },
    { "slang": "xb36t", "original": "Xbox 360" },
    { "slang": "xbf", "original": "ex-boyfriend" },
    { "slang": "xbl", "original": "xbox live" },
    { "slang": "xcept", "original": "except" },
    { "slang": "xcpt", "original": "except" },
    { "slang": "xd", "original": "extreme droll" },
    { "slang": "xellent", "original": "excellent" },
    { "slang": "xfer", "original": "transfer" },
    { "slang": "xgf", "original": "exgirlfriend" },
    { "slang": "xing", "original": "crossing" },
    { "slang": "xit", "original": "Exit" },
    { "slang": "xl", "original": "extra large" },
    { "slang": "xlnt", "original": "Excellent" },
    { "slang": "xmas", "original": "christmas" },
    { "slang": "xmpl", "original": "example" },
    { "slang": "xoac", "original": "Christ on a crutch" },
    { "slang": "xor", "original": "hacker" },
    { "slang": "xover", "original": "crossover" },
    { "slang": "xox", "original": "hugs and kisses" },
    { "slang": "xoxo", "original": "hugs and kisses" },
    { "slang": "xp", "original": "experience" },
    { "slang": "xpect", "original": "expect" },
    { "slang": "xplaned", "original": "explained" },
    { "slang": "xpt", "original": "except" },
    { "slang": "xroads", "original": "crossroads" },
    { "slang": "xs", "original": "excess" },
    { "slang": "xtc", "original": "ecstasy" },
    { "slang": "xtra", "original": "extra" },
    { "slang": "xtreme", "original": "extreme" },
    { "slang": "xyz", "original": "examine your zipper" },
    { "slang": "xyzpdq", "original": "Examine Your Zipper Pretty Darn Quick" },
    { "slang": "y", "original": "why" },
    { "slang": "y w", "original": "you're welcome" },
    { "slang": "y!a", "original": "yahoo answers" },
    { "slang": "y'all", "original": "you all" },
    { "slang": "y/n", "original": "yes or no" },
    { "slang": "y/o", "original": "Years Old" },
    { "slang": "y00", "original": "you" },
    { "slang": "y2b", "original": "Youtube" },
    { "slang": "y2k", "original": "year 2000" },
    { "slang": "ya", "original": "yeah" },
    { "slang": "yaaf", "original": "you are a fag" },
    { "slang": "yaafm", "original": "You Are A Fucking Moron" },
    { "slang": "yaagf", "original": "you are a good friend" },
    { "slang": "yaai", "original": "You are an idiot" },
    { "slang": "yaf", "original": "you're a fag" },
    { "slang": "yafi", "original": "you're a fucking  idiot" },
    { "slang": "yag", "original": "you are gay" },
    { "slang": "yall", "original": "you all" },
    { "slang": "yapa", "original": "yet another pointless acronym" },
    { "slang": "yaqw", "original": "You are quite welcome" },
    { "slang": "yarly", "original": "yeah really" },
    { "slang": "yas", "original": "you are stupid" },
    { "slang": "yasan", "original": "You are such a nerd" },
    { "slang": "yasf", "original": "you are so funny" },
    { "slang": "yasfg", "original": "you are so fucking gay" },
    { "slang": "yasg", "original": "you are so gay" },
    { "slang": "yasw", "original": "you are so weird" },
    { "slang": "yatb", "original": "you are the best" },
    { "slang": "yatwl", "original": "you are the weakest link" },
    { "slang": "yaw", "original": "you are welcome" },
    { "slang": "yayo", "original": "cocaine" },
    { "slang": "ybbg", "original": "Your Brother By Grace" },
    { "slang": "ybs", "original": "you'll be sorry" },
    { "slang": "ybya", "original": "you bet your ass" },
    { "slang": "ycliu", "original": "You could look it up" },
    { "slang": "ycmtsu", "original": "You Can't Make This Shit Up" },
    { "slang": "ycntu", "original": "Why Cant You?" },
    { "slang": "yctwuw", "original": "you can think what you want" },
    { "slang": "ydpos", "original": "you dumb piece of shit" },
    { "slang": "ydtm", "original": "You're dead to me" },
    { "slang": "ydufc", "original": "Why do fucking care?" },
    { "slang": "yduwtk", "original": "why do you want to know" },
    { "slang": "ye", "original": "yeah" },
    { "slang": "yea", "original": "yeah" },
    { "slang": "yer", "original": "you're" },
    { "slang": "yermom", "original": "your mother" },
    { "slang": "yesh", "original": "yes" },
    { "slang": "yew", "original": "you" },
    { "slang": "yfb", "original": "you fucking bastard" },
    { "slang": "yfg", "original": "you're fucking gay" },
    { "slang": "yfi", "original": "you fucking idiot" },
    { "slang": "ygg", "original": "you go girl" },
    { "slang": "ygm", "original": "You Got Mail" },
    { "slang": "ygp", "original": "you got  punked!" },
    { "slang": "ygpm", "original": "you've got a private message" },
    { "slang": "ygrr", "original": "you got rick rolled" },
    { "slang": "ygtbfkm", "original": "you've got to be fucking kidding me" },
    { "slang": "ygtbk", "original": "you've got to be kidding" },
    { "slang": "ygtbkm", "original": "you got to be kidding me" },
    { "slang": "ygtbsm", "original": "You've got to be shitting me" },
    { "slang": "ygtsr", "original": "you got that shit right" },
    { "slang": "yh", "original": "yeah" },
    { "slang": "yhbt", "original": "you've been trolled" },
    { "slang": "yhew", "original": "you" },
    { "slang": "yhf", "original": "you have failed" },
    { "slang": "yhgtbsm", "original": "You Have Got To Be Shitting Me" },
    { "slang": "yhl", "original": "you have lost" },
    { "slang": "yhm", "original": "You have mail" },
    { "slang": "yhni", "original": "you have no idea" },
    { "slang": "yhpm", "original": "you have a private messge" },
    { "slang": "yhtbt", "original": "You Had To Be There" },
    { "slang": "yid", "original": "yes, I do" },
    { "slang": "yim", "original": "yahoo instant messenger" },
    { "slang": "yiwtgo", "original": "Yes, I want to go private" },
    { "slang": "yk", "original": "you kidding" },
    { "slang": "yki", "original": "You know it" },
    { "slang": "ykisa", "original": "Your knight in shining armor" },
    { "slang": "ykm", "original": "You're killing me" },
    { "slang": "ykn", "original": "you know nothing" },
    { "slang": "ykw", "original": "You Know What" },
    { "slang": "ykwim", "original": "you know what I mean" },
    { "slang": "ykwya", "original": "you know who you are" },
    { "slang": "ykywywm", "original": "you know you wish you were me" },
    { "slang": "ylb", "original": "you little bitch" },
    { "slang": "ym", "original": "your mom" },
    { "slang": "ymbkm", "original": "you must be kidding me" },
    { "slang": "yme", "original": "why me" },
    { "slang": "ymfp", "original": "Your Most Favorite Person" },
    { "slang": "ymg2c", "original": "your mom goes to college" },
    { "slang": "ymgtc", "original": "Your Mom Goes To college" },
    { "slang": "ymiaw", "original": "your mom is a whore" },
    { "slang": "ymislidi", "original": "you make it sound like i did it" },
    { "slang": "ymmd", "original": "You Made My Day" },
    { "slang": "ymmv", "original": "your mileage may vary" },
    { "slang": "ymrasu", "original": "Yes, My Retarded Ass Signed Up" },
    { "slang": "yn", "original": "why not" },
    { "slang": "yng", "original": "young" },
    { "slang": "ynk", "original": "you never know" },
    { "slang": "ynm", "original": "yes, no, maybe" },
    { "slang": "ynt", "original": "why not" },
    { "slang": "ynw", "original": "you know what" },
    { "slang": "yo", "original": "year old" },
    { "slang": "yo'", "original": "your" },
    { "slang": "yodo", "original": "you only die once" },
    { "slang": "yolo", "original": "you only live once" },
    { "slang": "yolt", "original": "you only live twice" },
    { "slang": "yomank", "original": "you owe me a new keyboard" },
    { "slang": "yooh", "original": "you" },
    { "slang": "yor", "original": "your" },
    { "slang": "youngin", "original": "young person" },
    { "slang": "yoy", "original": "why oh why" },
    { "slang": "ypmf", "original": "you pissed me off" },
    { "slang": "ypmo", "original": "you piss me off" },
    { "slang": "ypom", "original": "your place or mine" },
    { "slang": "yqw", "original": "you're quite welcome" },
    { "slang": "yr", "original": "year" },
    { "slang": "yrbk", "original": "Yearbook" },
    { "slang": "yrms", "original": "You Rock My Socks" },
    { "slang": "yrs", "original": "years" },
    { "slang": "yrsaf", "original": "You Are Such A Fool " },
    { "slang": "yrsm", "original": "you really scare me" },
    { "slang": "yrss", "original": "you are so sexy" },
    { "slang": "yru", "original": "why are you?" },
    { "slang": "yrubm", "original": "why are you bugging me?" },
    { "slang": "yrusm", "original": "Why are you so mean" },
    { "slang": "ys", "original": "you suck" },
    { "slang": "ysa", "original": "You Suck Ass" },
    { "slang": "ysal", "original": "you suck at life" },
    { "slang": "ysati", "original": "you suck at the internet" },
    { "slang": "ysf", "original": "you stupid fuck" },
    { "slang": "ysic", "original": "why should I care" },
    { "slang": "ysitm", "original": "your shirt is too small" },
    { "slang": "ysm", "original": "you scare me" },
    { "slang": "ysoab", "original": "You son of a bitch" },
    { "slang": "yss", "original": "you stupid shit" },
    { "slang": "yswnt", "original": "why sleep when not tired?" },
    { "slang": "yt", "original": "You there?" },
    { "slang": "ytd", "original": "year to date" },
    { "slang": "ytf", "original": "why the fuck" },
    { "slang": "ytfwudt", "original": "why the fuck would you do that?" },
    { "slang": "ythwudt", "original": "Why the hell would you do that" },
    { "slang": "ytis", "original": "You think I'm special?" },
    { "slang": "ytm", "original": "you tell me" },
    { "slang": "ytmnd", "original": "You're the man now, dog!" },
    { "slang": "yty", "original": "why thank you" },
    { "slang": "yu", "original": "You" },
    { "slang": "yua", "original": "you ugly ass" },
    { "slang": "yuo", "original": "you" },
    { "slang": "yup", "original": "yes" },
    { "slang": "yur", "original": "your" },
    { "slang": "yust", "original": "why you say that" },
    { "slang": "yvfw", "original": "you're very fucking welcome" },
    { "slang": "yvw", "original": "you're very welcome" },
    { "slang": "yw", "original": "you're welcome" },
    { "slang": "ywapom", "original": "you want a piece of me?" },
    { "slang": "ywia", "original": "You're welcome in advance" },
    { "slang": "ywic", "original": "why would i care" },
    { "slang": "yws", "original": "you want sex" },
    { "slang": "ywsyls", "original": "you win some you lose some" },
    { "slang": "ywud", "original": "yo whats up dude" },
    { "slang": "ywvm", "original": "you're welcome very much" },
    { "slang": "ywywm", "original": "you wish you were me" },
    { "slang": "yysw", "original": "yeah, yeah, sure, whatever" },
    { "slang": "z'omg", "original": "Oh my God" },
    { "slang": "z0mg", "original": "oh my god" },
    { "slang": "zex", "original": "sex" },
    { "slang": "zh", "original": "Zero Hour" },
    { "slang": "zig", "original": "cigarette" },
    { "slang": "zomfg", "original": "oh my fucking god" },
    { "slang": "zomg", "original": "Oh my God" },
    { "slang": "zomgzorrz", "original": "oh my god" },
    { "slang": "zoot", "original": "woohoo" },
    { "slang": "zot", "original": "Zero Tolerance" },
    { "slang": "zt", "original": "zoo tycoon" },
    { "slang": "zup", "original": "what's up?" }]
}
